/**
 * Progressive Discipline Record
 * COR Element 5: Workplace Behavior
 * 
 * Document disciplinary actions for safety violations.
 */

import type { FormConfig } from '../../import-forms';

export const progressiveDiscipline: FormConfig = {
  code: 'progressive_discipline',
  name: 'Progressive Discipline Record',
  description: 'Document disciplinary actions taken for safety rule violations following the progressive discipline process.',
  cor_element: 5,
  frequency: 'as_needed',
  estimated_time_minutes: 20,
  icon: 'AlertCircle',
  color: '#EF4444',
  is_mandatory: true,

  sections: [
    {
      title: 'Incident Information',
      order_index: 0,
      fields: [
        {
          code: 'incident_date',
          label: 'Date of Incident/Violation',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'incident_time',
          label: 'Time of Incident',
          field_type: 'time',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'documentation_date',
          label: 'Documentation Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'supervisor',
          label: 'Supervisor/Manager',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'employee',
          label: 'Employee',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Violation Details',
      order_index: 1,
      fields: [
        {
          code: 'violation_category',
          label: 'Violation Category',
          field_type: 'dropdown',
          options: [
            { value: 'ppe', label: 'PPE Violation' },
            { value: 'procedure', label: 'Procedure Violation' },
            { value: 'equipment', label: 'Equipment Misuse' },
            { value: 'housekeeping', label: 'Housekeeping' },
            { value: 'hazard_awareness', label: 'Hazard Awareness' },
            { value: 'substance_abuse', label: 'Substance Abuse Policy' },
            { value: 'horseplay', label: 'Horseplay/Unsafe Behavior' },
            { value: 'failure_to_report', label: 'Failure to Report' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'rule_violated',
          label: 'Specific Rule/Procedure Violated',
          field_type: 'textarea',
          placeholder: 'Identify the specific safety rule or procedure that was violated...',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'violation_description',
          label: 'Description of Violation',
          field_type: 'textarea',
          placeholder: 'Describe exactly what happened...',
          validation_rules: { required: true, min_length: 50 },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'witnesses',
          label: 'Witnesses',
          field_type: 'worker_select',
          help_text: 'Select any witnesses to the violation',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'potential_consequences',
          label: 'Potential Consequences',
          field_type: 'multiselect',
          options: [
            { value: 'injury_self', label: 'Could have caused injury to self' },
            { value: 'injury_others', label: 'Could have caused injury to others' },
            { value: 'property_damage', label: 'Could have caused property damage' },
            { value: 'environmental', label: 'Could have caused environmental damage' },
            { value: 'regulatory', label: 'Could result in regulatory violation' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'severity',
          label: 'Severity of Violation',
          field_type: 'dropdown',
          options: [
            { value: 'minor', label: 'Minor - Low risk, first occurrence' },
            { value: 'moderate', label: 'Moderate - Medium risk or repeat occurrence' },
            { value: 'serious', label: 'Serious - High risk or willful violation' },
            { value: 'critical', label: 'Critical - Immediate danger to life' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Disciplinary Action',
      order_index: 2,
      fields: [
        {
          code: 'discipline_step',
          label: 'Discipline Step',
          field_type: 'dropdown',
          options: [
            { value: 'verbal_warning', label: '1. Verbal Warning (Documented)' },
            { value: 'written_warning', label: '2. Written Warning' },
            { value: 'final_warning', label: '3. Final Written Warning' },
            { value: 'suspension', label: '4. Suspension' },
            { value: 'termination', label: '5. Termination' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'previous_violations',
          label: 'Previous Related Violations',
          field_type: 'number',
          help_text: 'Number of previous violations for same/similar issue',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'action_taken',
          label: 'Action Taken',
          field_type: 'textarea',
          placeholder: 'Describe the disciplinary action being taken...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'suspension_dates',
          label: 'Suspension Dates (if applicable)',
          field_type: 'text',
          placeholder: 'Start date - End date',
          conditional_logic: {
            field_code: 'discipline_step',
            operator: 'equals',
            value: 'suspension',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'expected_behavior',
          label: 'Expected Behavior Going Forward',
          field_type: 'textarea',
          placeholder: 'Describe what behavior is expected...',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'consequences_future',
          label: 'Consequences of Future Violations',
          field_type: 'textarea',
          placeholder: 'Explain what will happen if violation is repeated...',
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Corrective Measures',
      order_index: 3,
      fields: [
        {
          code: 'retraining_required',
          label: 'Is retraining required?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'retraining_type',
          label: 'Type of Retraining',
          field_type: 'multiselect',
          options: [
            { value: 'safety_orientation', label: 'Safety Orientation Review' },
            { value: 'specific_training', label: 'Task-Specific Training' },
            { value: 'ppe_training', label: 'PPE Training' },
            { value: 'procedure_review', label: 'Procedure Review' },
            { value: 'toolbox_talk', label: 'Toolbox Talk Attendance' },
          ],
          conditional_logic: {
            field_code: 'retraining_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'retraining_deadline',
          label: 'Retraining Completion Deadline',
          field_type: 'date',
          conditional_logic: {
            field_code: 'retraining_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'follow_up_date',
          label: 'Follow-up Review Date',
          field_type: 'date',
          help_text: 'When to review employee behavior',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Employee Response',
      order_index: 4,
      fields: [
        {
          code: 'employee_response',
          label: 'Employee Response/Comments',
          field_type: 'textarea',
          placeholder: 'Employee may provide their response or comments...',
          order_index: 0,
          width: 'full',
        },
        {
          code: 'employee_agrees',
          label: 'Does employee agree with the facts presented?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially'],
          order_index: 1,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'supervisor_signature',
          label: 'Supervisor Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'employee_signature',
          label: 'Employee Signature',
          field_type: 'signature',
          help_text: 'Signature acknowledges receipt, not necessarily agreement',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'witness_signature',
          label: 'Witness Signature (if employee refuses to sign)',
          field_type: 'signature',
          order_index: 2,
          width: 'full',
        },
        {
          code: 'hr_notification',
          label: 'HR Notified?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['admin'],
    sync_priority: 2,
    requires_approval: true,
  },
};
