/**
 * Rule Communication Record
 * COR Element 5: Workplace Behavior
 * 
 * Document communication of safety rules to workers.
 */

import type { FormConfig } from '../../import-forms';

export const ruleCommunicationRecord: FormConfig = {
  code: 'rule_communication_record',
  name: 'Safety Rule Communication Record',
  description: 'Document the communication of safety rules and expectations to workers, ensuring everyone understands workplace safety requirements.',
  cor_element: 5,
  frequency: 'as_needed',
  estimated_time_minutes: 15,
  icon: 'FileText',
  color: '#3B82F6',
  is_mandatory: true,

  sections: [
    {
      title: 'Communication Details',
      order_index: 0,
      fields: [
        {
          code: 'communication_date',
          label: 'Date of Communication',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'communication_time',
          label: 'Time',
          field_type: 'time',
          default_value: 'now',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'communicator',
          label: 'Communicated By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'communication_reason',
          label: 'Reason for Communication',
          field_type: 'dropdown',
          options: [
            { value: 'new_employee', label: 'New Employee Orientation' },
            { value: 'rule_change', label: 'Rule Change/Update' },
            { value: 'new_rule', label: 'New Rule Implementation' },
            { value: 'incident_response', label: 'Response to Incident' },
            { value: 'refresher', label: 'Periodic Refresher' },
            { value: 'regulatory_change', label: 'Regulatory Change' },
            { value: 'project_specific', label: 'Project-Specific Requirements' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'communication_method',
          label: 'Method of Communication',
          field_type: 'multiselect',
          options: [
            { value: 'safety_meeting', label: 'Safety Meeting' },
            { value: 'toolbox_talk', label: 'Toolbox Talk' },
            { value: 'one_on_one', label: 'One-on-One Discussion' },
            { value: 'posted_notice', label: 'Posted Notice' },
            { value: 'email', label: 'Email' },
            { value: 'handbook', label: 'Safety Handbook' },
            { value: 'training', label: 'Formal Training' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Rules Communicated',
      description: 'Document the specific rules that were communicated',
      order_index: 1,
      fields: [
        {
          code: 'rule_categories',
          label: 'Rule Categories',
          field_type: 'multiselect',
          options: [
            { value: 'general_safety', label: 'General Safety Rules' },
            { value: 'ppe', label: 'PPE Requirements' },
            { value: 'housekeeping', label: 'Housekeeping Standards' },
            { value: 'equipment', label: 'Equipment Operation' },
            { value: 'hazard_reporting', label: 'Hazard Reporting' },
            { value: 'emergency_procedures', label: 'Emergency Procedures' },
            { value: 'substance_abuse', label: 'Substance Abuse Policy' },
            { value: 'violence_harassment', label: 'Violence & Harassment' },
            { value: 'working_at_heights', label: 'Working at Heights' },
            { value: 'confined_space', label: 'Confined Space' },
            { value: 'lockout_tagout', label: 'Lockout/Tagout' },
            { value: 'electrical', label: 'Electrical Safety' },
            { value: 'fire_safety', label: 'Fire Safety' },
            { value: 'mobile_equipment', label: 'Mobile Equipment' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'rules_summary',
          label: 'Summary of Rules Communicated',
          field_type: 'textarea',
          placeholder: 'Provide a summary of the specific rules discussed...',
          validation_rules: { required: true, min_length: 50 },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'consequences_explained',
          label: 'Were consequences for violations explained?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'documents_provided',
          label: 'Were written materials provided?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'documents_list',
          label: 'List Materials Provided',
          field_type: 'text',
          conditional_logic: {
            field_code: 'documents_provided',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Attendees',
      description: 'Record all workers who received this communication',
      order_index: 2,
      fields: [
        {
          code: 'attendees',
          label: 'Workers Present',
          field_type: 'worker_select',
          help_text: 'Select all workers who received this communication',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'attendee_count',
          label: 'Total Attendee Count',
          field_type: 'number',
          help_text: 'Include any workers not in the system',
          validation_rules: { required: true, min_value: 1 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'duration_minutes',
          label: 'Duration (minutes)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 1 },
          order_index: 2,
          width: 'half',
        },
      ],
    },
    {
      title: 'Understanding Verification',
      order_index: 3,
      fields: [
        {
          code: 'understanding_verified',
          label: 'Was worker understanding verified?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'verification_method',
          label: 'How was understanding verified?',
          field_type: 'multiselect',
          options: [
            { value: 'verbal_questions', label: 'Verbal Questions' },
            { value: 'written_test', label: 'Written Test' },
            { value: 'demonstration', label: 'Demonstration' },
            { value: 'discussion', label: 'Group Discussion' },
          ],
          conditional_logic: {
            field_code: 'understanding_verified',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'questions_asked',
          label: 'Questions Asked by Workers',
          field_type: 'textarea',
          placeholder: 'Document any questions asked and answers given...',
          order_index: 2,
          width: 'full',
        },
        {
          code: 'follow_up_needed',
          label: 'Is follow-up communication needed?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'follow_up_details',
          label: 'Follow-up Details',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'follow_up_needed',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 4,
      fields: [
        {
          code: 'communicator_signature',
          label: 'Communicator Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
