-- ============================================================================
-- COMPREHENSIVE HAZARD LIBRARY SEED DATA
-- ============================================================================
-- 100+ construction hazards organized by category with complete data:
-- - Physical Hazards (50+)
-- - Chemical Hazards (30+)
-- - Biological Hazards (10+)
-- - Ergonomic Hazards (15+)
-- - Psychosocial Hazards (10+)
-- Plus concrete-specific hazards for NCCI focus
-- ============================================================================

-- Clear existing global hazards for clean re-seeding
DELETE FROM hazard_library WHERE company_id IS NULL;

-- ============================================================================
-- PHYSICAL HAZARDS - FALLS (15 items)
-- ============================================================================

INSERT INTO hazard_library (company_id, hazard_code, name, description, category, subcategory, applicable_trades, applicable_activities, default_severity, default_likelihood, default_risk_level, recommended_controls, required_ppe, regulatory_references) VALUES

(NULL, 'PHYS-FALL-001', 'Working at Heights', 
'Risk of falling from elevated work positions including ladders, scaffolds, roofs, and elevated platforms. Falls from heights are the leading cause of death in construction.',
'fall', 'Working at Heights',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Elevated Work'],
5, 4, 'critical',
'[{"type": "engineering", "control": "Install guardrails with top rail, mid rail, and toe board", "required": true},
{"type": "engineering", "control": "Use scaffolding with proper platforms", "required": true},
{"type": "engineering", "control": "Install safety netting below work area", "required": false},
{"type": "engineering", "control": "Use aerial work platforms (scissor lifts, boom lifts)", "required": false},
{"type": "engineering", "control": "Cover floor openings with secured covers", "required": true},
{"type": "administrative", "control": "Working at Heights training certification required", "required": true},
{"type": "administrative", "control": "Develop and follow rescue plan", "required": true},
{"type": "administrative", "control": "Conduct daily pre-use inspections", "required": true},
{"type": "administrative", "control": "Weather restrictions - no work in high wind, rain, ice", "required": true},
{"type": "administrative", "control": "Competent worker supervision required", "required": true},
{"type": "ppe", "control": "Full-body harness with shock-absorbing lanyard", "required": true}]',
ARRAY['Full Body Harness', 'Shock-Absorbing Lanyard', 'Hard Hat', 'Safety Boots', 'Hi-Vis Vest'],
'[{"regulation": "OHSA", "section": "26.1", "title": "Employer duties - fall protection"},
{"regulation": "O. Reg. 213/91", "section": "26", "title": "Fall protection requirements"},
{"regulation": "O. Reg. 213/91", "section": "139", "title": "Working at Heights training"},
{"regulation": "CSA Z259", "section": "All", "title": "Fall protection standards"}]'),

(NULL, 'PHYS-FALL-002', 'Falls from Ladders',
'Risk of falling while climbing, working on, or descending ladders. Improper setup, overreaching, and damaged equipment are common causes.',
'fall', 'Ladders',
ARRAY['General Construction', 'Electrical', 'Painting', 'Carpentry', 'HVAC'],
ARRAY['Ladder Work', 'Access/Egress'],
4, 4, 'high',
'[{"type": "engineering", "control": "Use scaffold or platform instead of ladder where possible", "required": false},
{"type": "engineering", "control": "Secure ladder at top and bottom", "required": true},
{"type": "engineering", "control": "Use ladder with proper load rating", "required": true},
{"type": "administrative", "control": "Three-point contact rule at all times", "required": true},
{"type": "administrative", "control": "Pre-use ladder inspection", "required": true},
{"type": "administrative", "control": "Never stand on top two rungs", "required": true},
{"type": "administrative", "control": "Face ladder when climbing", "required": true},
{"type": "administrative", "control": "Set at 4:1 angle (75 degrees)", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "78-84", "title": "Ladders"}]'),

(NULL, 'PHYS-FALL-003', 'Falls from Scaffolding',
'Risk of falling from scaffold platforms, climbing scaffold, or through scaffold openings. Scaffold collapse and improper assembly are additional risks.',
'fall', 'Scaffolds',
ARRAY['General Construction', 'Masonry', 'Painting', 'Drywall', 'Glazing'],
ARRAY['Scaffold Work'],
5, 3, 'high',
'[{"type": "engineering", "control": "Install guardrails on all open sides", "required": true},
{"type": "engineering", "control": "Install toe boards to prevent objects falling", "required": true},
{"type": "engineering", "control": "Use scaffold with full decking - no gaps over 25mm", "required": true},
{"type": "engineering", "control": "Proper bracing and base plates", "required": true},
{"type": "administrative", "control": "Competent person supervises erection", "required": true},
{"type": "administrative", "control": "Daily inspection before use", "required": true},
{"type": "administrative", "control": "No overloading - check load rating", "required": true},
{"type": "ppe", "control": "Fall protection where guardrails not feasible", "required": false}]',
ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "125-142", "title": "Scaffolds"}]'),

(NULL, 'PHYS-FALL-004', 'Falls through Openings',
'Risk of falling through unprotected openings in floors, roofs, skylights, or other walking surfaces.',
'fall', 'Openings',
ARRAY['General Construction', 'Roofing', 'Carpentry', 'HVAC', 'Electrical'],
ARRAY['Floor Work', 'Roof Work', 'HVAC Installation'],
5, 3, 'high',
'[{"type": "engineering", "control": "Install covers secured against displacement", "required": true},
{"type": "engineering", "control": "Install guardrails around openings", "required": true},
{"type": "engineering", "control": "Mark covers clearly - OPENING DO NOT REMOVE", "required": true},
{"type": "administrative", "control": "Daily inspection of covers", "required": true},
{"type": "administrative", "control": "No unauthorized removal of covers", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "26.3", "title": "Covers"}]'),

(NULL, 'PHYS-FALL-005', 'Falls from Roofs',
'Risk of falling from flat or sloped roofs during installation, repair, or maintenance work.',
'fall', 'Working at Heights',
ARRAY['Roofing', 'HVAC', 'Electrical', 'General Construction'],
ARRAY['Roofing', 'Equipment Installation'],
5, 4, 'critical',
'[{"type": "engineering", "control": "Install perimeter guardrails", "required": true},
{"type": "engineering", "control": "Install warning line system", "required": false},
{"type": "engineering", "control": "Install roof anchors", "required": true},
{"type": "engineering", "control": "Install safety netting", "required": false},
{"type": "administrative", "control": "Working at Heights training required", "required": true},
{"type": "administrative", "control": "Weather restrictions", "required": true},
{"type": "ppe", "control": "Fall arrest system required", "required": true}]',
ARRAY['Full Body Harness', 'Shock-Absorbing Lanyard', 'Hard Hat', 'Safety Boots', 'Roof Anchor'],
'[{"regulation": "O. Reg. 213/91", "section": "26", "title": "Fall Protection"}]'),

(NULL, 'PHYS-FALL-006', 'Falls from Elevated Work Platforms',
'Risk of falling from aerial lifts, scissor lifts, boom lifts, or other elevated work platforms.',
'fall', 'Elevated Platforms',
ARRAY['General Construction', 'Electrical', 'Painting', 'Glazing', 'HVAC'],
ARRAY['Elevated Platform Work'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Use platform with guardrails", "required": true},
{"type": "engineering", "control": "Ensure outriggers/stabilizers deployed", "required": true},
{"type": "administrative", "control": "Operator training and certification required", "required": true},
{"type": "administrative", "control": "Pre-use inspection", "required": true},
{"type": "administrative", "control": "Stay within load capacity", "required": true},
{"type": "ppe", "control": "Fall restraint required in boom lifts", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "143-149", "title": "Elevating Work Platforms"}]'),

(NULL, 'PHYS-FALL-007', 'Slips, Trips, Falls - Same Level',
'Risk of slipping on wet/icy surfaces, tripping over materials/debris, or falling on uneven surfaces.',
'fall', 'Slips/Trips',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
3, 5, 'high',
'[{"type": "engineering", "control": "Install non-slip surfaces where needed", "required": false},
{"type": "engineering", "control": "Adequate lighting in work areas", "required": true},
{"type": "engineering", "control": "Level walking surfaces", "required": true},
{"type": "administrative", "control": "Good housekeeping program", "required": true},
{"type": "administrative", "control": "Clean up spills immediately", "required": true},
{"type": "administrative", "control": "Remove snow and ice promptly", "required": true},
{"type": "administrative", "control": "Keep walkways clear of materials", "required": true}]',
ARRAY['Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "35", "title": "Housekeeping"}]'),

(NULL, 'PHYS-FALL-008', 'Falls into Excavations',
'Risk of falling into trenches, pits, shafts, or excavations.',
'fall', 'Excavations',
ARRAY['Excavation', 'General Construction', 'Plumbing', 'Electrical'],
ARRAY['Excavation Work', 'Underground Utilities'],
5, 3, 'high',
'[{"type": "engineering", "control": "Install barricades around excavation perimeter", "required": true},
{"type": "engineering", "control": "Install guardrails at edges", "required": true},
{"type": "engineering", "control": "Provide safe means of entry/exit - ladder within 8m", "required": true},
{"type": "administrative", "control": "Post warning signs", "required": true},
{"type": "administrative", "control": "Adequate lighting for night work", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Hi-Vis Vest'],
'[{"regulation": "O. Reg. 213/91", "section": "222-242", "title": "Excavations"}]'),

(NULL, 'PHYS-FALL-009', 'Falls from Formwork',
'Risk of falling during formwork erection, stripping, or working on elevated formwork.',
'fall', 'Formwork',
ARRAY['Concrete', 'Formwork'],
ARRAY['Formwork Erection', 'Form Stripping', 'Concrete Placement'],
5, 3, 'high',
'[{"type": "engineering", "control": "Install working platforms with guardrails", "required": true},
{"type": "engineering", "control": "Install fall arrest anchors", "required": true},
{"type": "engineering", "control": "Engineered formwork design", "required": true},
{"type": "administrative", "control": "Competent supervision required", "required": true},
{"type": "ppe", "control": "Fall protection required", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness', 'Safety Glasses'],
'[{"regulation": "O. Reg. 213/91", "section": "85-102", "title": "Formwork and Falsework"}]'),

(NULL, 'PHYS-FALL-010', 'Falls from Steel Structures',
'Risk of falling during structural steel erection, connection work, or decking.',
'fall', 'Structural Steel',
ARRAY['Structural Steel', 'Iron Workers'],
ARRAY['Steel Erection', 'Decking', 'Connections'],
5, 3, 'high',
'[{"type": "engineering", "control": "Install perimeter cables/guardrails", "required": true},
{"type": "engineering", "control": "Install safety netting", "required": false},
{"type": "engineering", "control": "Controlled decking zone procedures", "required": true},
{"type": "administrative", "control": "Trained iron workers only", "required": true},
{"type": "ppe", "control": "100% tie-off fall protection required", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness', 'SRL', 'Safety Gloves'],
'[{"regulation": "O. Reg. 213/91", "section": "103-124", "title": "Steel and Metal Work"}]'),

-- ============================================================================
-- PHYSICAL HAZARDS - STRUCK BY (10 items)
-- ============================================================================

(NULL, 'PHYS-STRUCK-001', 'Struck by Falling Objects',
'Risk of being struck by tools, materials, equipment, or debris falling from above.',
'struck_by', 'Falling Objects',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities Below Overhead Work'],
4, 4, 'high',
'[{"type": "engineering", "control": "Install toe boards on all elevated platforms", "required": true},
{"type": "engineering", "control": "Install debris nets/catch platforms", "required": false},
{"type": "engineering", "control": "Tool tethering/lanyards", "required": true},
{"type": "administrative", "control": "Barricade area below overhead work", "required": true},
{"type": "administrative", "control": "Establish drop zones", "required": true},
{"type": "ppe", "control": "Hard hat required in all areas", "required": true}]',
ARRAY['Hard Hat', 'Safety Glasses'],
'[{"regulation": "O. Reg. 213/91", "section": "26.5", "title": "Toe Boards"}]'),

(NULL, 'PHYS-STRUCK-002', 'Struck by Mobile Equipment',
'Risk of being struck by construction vehicles, forklifts, loaders, or other mobile equipment.',
'struck_by', 'Vehicles',
ARRAY['General Construction', 'Excavation', 'Paving', 'Demolition'],
ARRAY['Site Traffic', 'Loading/Unloading', 'Excavation'],
5, 3, 'high',
'[{"type": "engineering", "control": "Install traffic barriers and signage", "required": true},
{"type": "engineering", "control": "Backup alarms on all equipment", "required": true},
{"type": "engineering", "control": "Proximity detection systems", "required": false},
{"type": "engineering", "control": "Separate pedestrian and vehicle traffic", "required": true},
{"type": "administrative", "control": "Traffic control plan required", "required": true},
{"type": "administrative", "control": "Spotters for backing equipment", "required": true},
{"type": "administrative", "control": "Equipment operator certification", "required": true},
{"type": "ppe", "control": "High visibility clothing mandatory", "required": true}]',
ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "67-77", "title": "Vehicles and Equipment"}]'),

(NULL, 'PHYS-STRUCK-003', 'Struck by Crane Loads',
'Risk of being struck by crane loads, rigging, or boom during lifting operations.',
'struck_by', 'Lifting Operations',
ARRAY['Crane/Rigging', 'Structural Steel', 'Concrete', 'General Construction'],
ARRAY['Crane Operations', 'Rigging', 'Material Hoisting'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Establish lift zone barriers", "required": true},
{"type": "engineering", "control": "Use tag lines for load control", "required": true},
{"type": "engineering", "control": "Anti-two-block devices", "required": true},
{"type": "administrative", "control": "Never stand under suspended loads", "required": true},
{"type": "administrative", "control": "Trained signal person required", "required": true},
{"type": "administrative", "control": "Critical lift planning", "required": true},
{"type": "administrative", "control": "Wind speed limits", "required": true}]',
ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots', 'Safety Glasses'],
'[{"regulation": "O. Reg. 213/91", "section": "150-176", "title": "Cranes and Lifting Devices"}]'),

(NULL, 'PHYS-STRUCK-004', 'Struck by Flying Debris/Particles',
'Risk of being struck by particles from cutting, grinding, drilling, chipping, or power tool operations.',
'struck_by', 'Flying Particles',
ARRAY['Concrete', 'Masonry', 'Carpentry', 'Metal Work', 'Demolition'],
ARRAY['Cutting', 'Grinding', 'Drilling', 'Chipping'],
3, 5, 'high',
'[{"type": "engineering", "control": "Use guards on grinders, saws, and cutters", "required": true},
{"type": "engineering", "control": "Install barriers/screens around work area", "required": false},
{"type": "engineering", "control": "Use dust collection systems", "required": false},
{"type": "administrative", "control": "Clear area of bystanders", "required": true},
{"type": "ppe", "control": "Safety glasses minimum, goggles preferred", "required": true},
{"type": "ppe", "control": "Face shield for heavy grinding", "required": true}]',
ARRAY['Safety Glasses', 'Face Shield'],
'[{"regulation": "O. Reg. 213/91", "section": "108", "title": "Grinding"}]'),

(NULL, 'PHYS-STRUCK-005', 'Struck by Power Tool Kickback',
'Risk of being struck by power tool kickback from saws, grinders, drills, or other power tools.',
'struck_by', 'Power Tools',
ARRAY['Carpentry', 'Concrete', 'Metal Work', 'General Construction'],
ARRAY['Sawing', 'Cutting', 'Grinding'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Use anti-kickback devices", "required": true},
{"type": "engineering", "control": "Maintain sharp, properly set blades", "required": true},
{"type": "engineering", "control": "Use correct tool for material", "required": true},
{"type": "administrative", "control": "Proper tool technique training", "required": true},
{"type": "administrative", "control": "Secure workpiece before cutting", "required": true}]',
ARRAY['Safety Glasses', 'Safety Gloves'],
'[]'),

(NULL, 'PHYS-STRUCK-006', 'Struck by Nail Gun Discharge',
'Risk of being struck by nails from pneumatic or powder-actuated nail guns.',
'struck_by', 'Fastening Tools',
ARRAY['Carpentry', 'Formwork', 'Roofing', 'Framing'],
ARRAY['Framing', 'Sheathing', 'Nailing'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Use sequential trigger mechanism", "required": true},
{"type": "engineering", "control": "Use tool with safety contact tip", "required": true},
{"type": "administrative", "control": "Never point at anyone", "required": true},
{"type": "administrative", "control": "Disconnect when not in use", "required": true},
{"type": "administrative", "control": "Never bypass safety mechanisms", "required": true}]',
ARRAY['Safety Glasses', 'Hard Hat'],
'[{"regulation": "O. Reg. 213/91", "section": "116", "title": "Explosive Actuated Tools"}]'),

(NULL, 'PHYS-STRUCK-007', 'Struck by Excavator/Backhoe',
'Risk of being struck by excavator bucket, boom, or swing radius.',
'struck_by', 'Heavy Equipment',
ARRAY['Excavation', 'Demolition', 'General Construction'],
ARRAY['Excavation', 'Demolition', 'Material Moving'],
5, 3, 'high',
'[{"type": "engineering", "control": "Establish swing radius barriers", "required": true},
{"type": "administrative", "control": "Stay out of equipment operating radius", "required": true},
{"type": "administrative", "control": "Make eye contact with operator before approaching", "required": true},
{"type": "administrative", "control": "Designated walkways around equipment", "required": true}]',
ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "104", "title": "Equipment"}]'),

(NULL, 'PHYS-STRUCK-008', 'Struck by Dump Truck',
'Risk of being struck by dump trucks during backing, dumping, or travel.',
'struck_by', 'Vehicles',
ARRAY['Excavation', 'Paving', 'General Construction', 'Concrete'],
ARRAY['Material Delivery', 'Backfill', 'Concrete Delivery'],
5, 3, 'high',
'[{"type": "engineering", "control": "Backup alarm and cameras", "required": true},
{"type": "administrative", "control": "Spotter required for all backing", "required": true},
{"type": "administrative", "control": "Designated dump areas", "required": true},
{"type": "administrative", "control": "Clear area during dumping", "required": true},
{"type": "ppe", "control": "High visibility clothing", "required": true}]',
ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "67", "title": "Signallers"}]'),

(NULL, 'PHYS-STRUCK-009', 'Struck by Collapsing Materials',
'Risk of being struck by collapsing stacked materials, lumber, or supplies.',
'struck_by', 'Material Storage',
ARRAY['General Construction', 'All Trades'],
ARRAY['Material Storage', 'Warehouse'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Proper stacking and blocking", "required": true},
{"type": "engineering", "control": "Use storage racks rated for load", "required": true},
{"type": "administrative", "control": "Stack height limits", "required": true},
{"type": "administrative", "control": "Remove materials from top of stack", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Safety Gloves'],
'[{"regulation": "O. Reg. 213/91", "section": "36", "title": "Material Storage"}]'),

(NULL, 'PHYS-STRUCK-010', 'Struck by Concrete Pump Hose/Boom',
'Risk of being struck by concrete pump boom movement or hose whip.',
'struck_by', 'Concrete Pumping',
ARRAY['Concrete'],
ARRAY['Concrete Placement', 'Pumping'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Ensure proper setup and outriggers", "required": true},
{"type": "administrative", "control": "Keep clear during boom movement", "required": true},
{"type": "administrative", "control": "Communication with pump operator", "required": true},
{"type": "administrative", "control": "Hold hose securely during placement", "required": true}]',
ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots', 'Safety Glasses'],
'[]')

ON CONFLICT DO NOTHING;
