-- ============================================================================
-- HAZARD LIBRARY - PHYSICAL HAZARDS CONTINUED
-- ============================================================================
-- Caught-In/Between, Electrical, Fire/Explosion, Confined Space, Noise, etc.
-- ============================================================================

-- ============================================================================
-- PHYSICAL HAZARDS - CAUGHT IN/BETWEEN (8 items)
-- ============================================================================

INSERT INTO hazard_library (company_id, hazard_code, name, description, category, subcategory, applicable_trades, applicable_activities, default_severity, default_likelihood, default_risk_level, recommended_controls, required_ppe, regulatory_references) VALUES

(NULL, 'PHYS-CAUGHT-001', 'Trench/Excavation Cave-In',
'Risk of being caught in or buried by excavation wall collapse. Cave-ins can happen suddenly without warning and are often fatal.',
'caught_in', 'Excavation',
ARRAY['Excavation', 'Plumbing', 'Electrical', 'General Construction'],
ARRAY['Trenching', 'Excavation Work'],
5, 4, 'critical',
'[{"type": "engineering", "control": "Install trench box or shoring system", "required": true},
{"type": "engineering", "control": "Slope or bench walls to safe angle", "required": true},
{"type": "engineering", "control": "Provide safe means of exit within 8m", "required": true},
{"type": "administrative", "control": "Daily excavation inspection by competent person", "required": true},
{"type": "administrative", "control": "Soil classification required", "required": true},
{"type": "administrative", "control": "Keep spoil 1m back from edge", "required": true},
{"type": "administrative", "control": "Do not enter unprotected excavation over 1.2m", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Hi-Vis Vest'],
'[{"regulation": "O. Reg. 213/91", "section": "222-242", "title": "Excavations"},
{"regulation": "O. Reg. 213/91", "section": "234", "title": "Shoring and Support Systems"}]'),

(NULL, 'PHYS-CAUGHT-002', 'Caught in Rotating Machinery',
'Risk of entanglement in rotating gears, belts, pulleys, shafts, or other rotating equipment.',
'caught_in', 'Machinery',
ARRAY['General Construction', 'All Trades'],
ARRAY['Equipment Operation', 'Maintenance'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Install machine guards on all rotating parts", "required": true},
{"type": "engineering", "control": "Emergency stop devices", "required": true},
{"type": "administrative", "control": "Lockout/tagout before maintenance", "required": true},
{"type": "administrative", "control": "No loose clothing, jewelry, or long hair near machinery", "required": true},
{"type": "administrative", "control": "Never remove guards during operation", "required": true}]',
ARRAY['Safety Glasses', 'Safety Boots', 'Safety Gloves'],
'[{"regulation": "O. Reg. 851", "section": "24-42", "title": "Machine Guarding"}]'),

(NULL, 'PHYS-CAUGHT-003', 'Caught Between Equipment and Fixed Objects',
'Risk of being caught or crushed between moving equipment and walls, structures, or other fixed objects.',
'caught_in', 'Pinch Points',
ARRAY['General Construction', 'Excavation', 'Demolition'],
ARRAY['Equipment Operation', 'Material Moving'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Maintain minimum clearances", "required": true},
{"type": "engineering", "control": "Install proximity alarms/sensors", "required": false},
{"type": "administrative", "control": "Establish safe work zones", "required": true},
{"type": "administrative", "control": "Use spotters in tight areas", "required": true},
{"type": "ppe", "control": "High visibility clothing", "required": true}]',
ARRAY['Hi-Vis Vest', 'Hard Hat'],
'[]'),

(NULL, 'PHYS-CAUGHT-004', 'Scaffold Collapse',
'Risk of being caught in a collapsing scaffold structure.',
'caught_in', 'Structural',
ARRAY['Scaffolding', 'General Construction', 'Masonry'],
ARRAY['Scaffold Work'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Engineered scaffold design for heavy loads", "required": true},
{"type": "engineering", "control": "Proper bracing and tie-ins to structure", "required": true},
{"type": "engineering", "control": "Adequate foundations/base plates", "required": true},
{"type": "administrative", "control": "Competent person supervision", "required": true},
{"type": "administrative", "control": "Never exceed load capacity", "required": true},
{"type": "administrative", "control": "Daily inspection before use", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "125-142", "title": "Scaffolds"}]'),

(NULL, 'PHYS-CAUGHT-005', 'Structural/Building Collapse',
'Risk of being caught in collapsing building, wall, or structural element.',
'caught_in', 'Structural',
ARRAY['Demolition', 'General Construction', 'Formwork'],
ARRAY['Demolition', 'Structural Work', 'Formwork Stripping'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Engineering assessment required", "required": true},
{"type": "engineering", "control": "Temporary shoring where needed", "required": true},
{"type": "administrative", "control": "Demolition plan by competent engineer", "required": true},
{"type": "administrative", "control": "Controlled demolition sequence", "required": true},
{"type": "administrative", "control": "Exclusion zones established", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Hi-Vis Vest'],
'[{"regulation": "O. Reg. 213/91", "section": "200-218", "title": "Demolition"}]'),

(NULL, 'PHYS-CAUGHT-006', 'Formwork/Falsework Collapse',
'Risk of being caught in collapsing formwork or shoring systems.',
'caught_in', 'Formwork',
ARRAY['Formwork', 'Concrete'],
ARRAY['Formwork Erection', 'Concrete Placement', 'Form Stripping'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Engineered formwork design", "required": true},
{"type": "engineering", "control": "Proper shoring and bracing", "required": true},
{"type": "administrative", "control": "Do not strip forms prematurely", "required": true},
{"type": "administrative", "control": "Concrete strength verification before stripping", "required": true},
{"type": "administrative", "control": "Reshoring requirements", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Safety Glasses'],
'[{"regulation": "O. Reg. 213/91", "section": "85-102", "title": "Formwork and Falsework"}]'),

(NULL, 'PHYS-CAUGHT-007', 'Crushing by Material/Equipment',
'Risk of crushing injury from shifting loads, tipping equipment, or falling materials.',
'caught_in', 'Crushing',
ARRAY['General Construction', 'Warehouse', 'Material Handling'],
ARRAY['Material Handling', 'Equipment Operation'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Proper load securing", "required": true},
{"type": "engineering", "control": "Equipment stability systems", "required": true},
{"type": "administrative", "control": "Stay clear of suspended/shifting loads", "required": true},
{"type": "administrative", "control": "Proper stacking procedures", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots', 'Safety Gloves'],
'[]'),

(NULL, 'PHYS-CAUGHT-008', 'Caught in Concrete Mixer/Auger',
'Risk of entanglement in rotating concrete mixer drums or auger equipment.',
'caught_in', 'Machinery',
ARRAY['Concrete'],
ARRAY['Concrete Mixing', 'Auger Work'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Guards on all rotating components", "required": true},
{"type": "engineering", "control": "Emergency stop devices", "required": true},
{"type": "administrative", "control": "Lockout during cleaning/maintenance", "required": true},
{"type": "administrative", "control": "Never reach into operating equipment", "required": true}]',
ARRAY['Safety Glasses', 'Safety Boots'],
'[]'),

-- ============================================================================
-- PHYSICAL HAZARDS - ELECTRICAL (8 items)
-- ============================================================================

(NULL, 'PHYS-ELEC-001', 'Contact with Overhead Powerlines',
'Risk of electrocution from equipment, materials, or personnel contacting overhead electrical lines.',
'electrical', 'Powerlines',
ARRAY['Crane/Rigging', 'Excavation', 'Concrete', 'General Construction'],
ARRAY['Crane Operations', 'Material Delivery', 'Equipment Operation'],
5, 3, 'high',
'[{"type": "engineering", "control": "Maintain minimum clearance distances (3m for <750V)", "required": true},
{"type": "engineering", "control": "Use spotters when working near lines", "required": true},
{"type": "engineering", "control": "Request line de-energization or shielding", "required": false},
{"type": "administrative", "control": "Identify all overhead lines on site", "required": true},
{"type": "administrative", "control": "Powerline safety training", "required": true},
{"type": "administrative", "control": "Pre-job planning for all lifts near lines", "required": true}]',
ARRAY['Hard Hat', 'Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "188", "title": "Overhead Electrical Lines"},
{"regulation": "O. Reg. 213/91", "section": "189", "title": "Minimum Distance from Overhead Lines"}]'),

(NULL, 'PHYS-ELEC-002', 'Contact with Underground Utilities',
'Risk of electrocution from damaging underground electrical cables during excavation.',
'electrical', 'Underground',
ARRAY['Excavation', 'Plumbing', 'Electrical', 'Landscaping'],
ARRAY['Excavation', 'Trenching', 'Digging'],
5, 3, 'high',
'[{"type": "administrative", "control": "Obtain utility locates before excavation", "required": true},
{"type": "administrative", "control": "Hand dig within tolerance zone", "required": true},
{"type": "administrative", "control": "Mark located utilities clearly", "required": true},
{"type": "administrative", "control": "Call Ontario One Call (1-800-400-2255)", "required": true}]',
ARRAY['Safety Boots', 'Safety Gloves'],
'[{"regulation": "O. Reg. 213/91", "section": "228", "title": "Underground Services"}]'),

(NULL, 'PHYS-ELEC-003', 'Electrical Shock from Equipment/Tools',
'Risk of electrical shock from damaged cords, defective tools, or improper temporary wiring.',
'electrical', 'Equipment',
ARRAY['General Construction', 'All Trades'],
ARRAY['Power Tool Use', 'Temporary Power'],
4, 4, 'high',
'[{"type": "engineering", "control": "GFCI protection on all temporary circuits", "required": true},
{"type": "engineering", "control": "Use double-insulated tools", "required": false},
{"type": "engineering", "control": "Properly grounded equipment", "required": true},
{"type": "administrative", "control": "Inspect cords and tools before each use", "required": true},
{"type": "administrative", "control": "Remove damaged equipment from service", "required": true},
{"type": "administrative", "control": "Electrical safety training", "required": true}]',
ARRAY['Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "195", "title": "Electrical Equipment"}]'),

(NULL, 'PHYS-ELEC-004', 'Arc Flash/Arc Blast',
'Risk of severe burns and blast injuries from electrical arc flash during energized work.',
'electrical', 'Arc Flash',
ARRAY['Electrical'],
ARRAY['Electrical Work', 'Panel Work', 'Switching'],
5, 2, 'medium',
'[{"type": "elimination", "control": "De-energize before work whenever possible", "required": true},
{"type": "engineering", "control": "Arc flash boundary establishment", "required": true},
{"type": "engineering", "control": "Arc flash labels on equipment", "required": true},
{"type": "administrative", "control": "Arc flash hazard analysis", "required": true},
{"type": "administrative", "control": "Energized work permit", "required": true},
{"type": "ppe", "control": "Arc-rated PPE based on incident energy", "required": true}]',
ARRAY['FR Coveralls', 'Face Shield', 'Insulated Gloves', 'Safety Glasses'],
'[{"regulation": "CSA Z462", "section": "4.3", "title": "Arc Flash Protection"}]'),

(NULL, 'PHYS-ELEC-005', 'Electrocution from Live Electrical Work',
'Risk of electrocution from contact with live electrical conductors during installation or maintenance.',
'electrical', 'Live Work',
ARRAY['Electrical'],
ARRAY['Electrical Installation', 'Maintenance'],
5, 3, 'high',
'[{"type": "elimination", "control": "De-energize and lockout before work", "required": true},
{"type": "engineering", "control": "Use insulated tools", "required": true},
{"type": "engineering", "control": "Install barriers/covers on adjacent live parts", "required": true},
{"type": "administrative", "control": "Lockout/tagout procedures", "required": true},
{"type": "administrative", "control": "Verify de-energized state", "required": true},
{"type": "ppe", "control": "Insulating gloves and matting", "required": true}]',
ARRAY['Insulated Gloves', 'Safety Glasses', 'Safety Boots - Electrical Hazard'],
'[{"regulation": "O. Reg. 213/91", "section": "181-195", "title": "Electrical Hazards"}]'),

(NULL, 'PHYS-ELEC-006', 'Electrical Fire',
'Risk of fire from electrical shorts, overloaded circuits, or damaged wiring.',
'electrical', 'Fire',
ARRAY['General Construction', 'Electrical'],
ARRAY['Temporary Power', 'Electrical Work'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Properly sized circuits and breakers", "required": true},
{"type": "engineering", "control": "Correct wiring and connections", "required": true},
{"type": "administrative", "control": "Regular inspection of temporary wiring", "required": true},
{"type": "administrative", "control": "No daisy-chaining extension cords", "required": true},
{"type": "engineering", "control": "Fire extinguisher nearby", "required": true}]',
ARRAY['Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "52", "title": "Fire Prevention"}]'),

(NULL, 'PHYS-ELEC-007', 'Lightning Strike',
'Risk of lightning strike during outdoor work, especially on elevated structures or around metal.',
'electrical', 'Lightning',
ARRAY['Crane/Rigging', 'Structural Steel', 'Roofing', 'General Construction'],
ARRAY['Outdoor Work', 'Elevated Work'],
5, 2, 'medium',
'[{"type": "administrative", "control": "Monitor weather forecasts", "required": true},
{"type": "administrative", "control": "Suspend outdoor work when lightning within 10km", "required": true},
{"type": "administrative", "control": "Take shelter in enclosed structure", "required": true},
{"type": "administrative", "control": "Wait 30 minutes after last thunder before resuming", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PHYS-ELEC-008', 'Static Electricity Discharge',
'Risk of static discharge igniting flammable materials or vapours.',
'electrical', 'Static',
ARRAY['Painting', 'General Construction'],
ARRAY['Fuel Transfer', 'Spray Painting', 'Flammable Material Handling'],
4, 2, 'medium',
'[{"type": "engineering", "control": "Ground all containers during transfer", "required": true},
{"type": "engineering", "control": "Use bonding cables between containers", "required": true},
{"type": "engineering", "control": "Conductive flooring in spray areas", "required": false},
{"type": "administrative", "control": "Allow time for static dissipation", "required": true}]',
ARRAY['Safety Boots'],
'[]'),

-- ============================================================================
-- PHYSICAL HAZARDS - FIRE/EXPLOSION (6 items)
-- ============================================================================

(NULL, 'PHYS-FIRE-001', 'Fire from Hot Work (Welding/Cutting)',
'Risk of fire from sparks, slag, or heat during welding, cutting, or grinding operations.',
'fire_explosion', 'Hot Work',
ARRAY['Structural Steel', 'Plumbing', 'HVAC', 'Demolition'],
ARRAY['Welding', 'Cutting', 'Grinding'],
4, 4, 'high',
'[{"type": "engineering", "control": "Remove or protect combustibles within 11m", "required": true},
{"type": "engineering", "control": "Fire extinguisher within 6m of work", "required": true},
{"type": "engineering", "control": "Use welding blankets/curtains", "required": true},
{"type": "administrative", "control": "Hot work permit required", "required": true},
{"type": "administrative", "control": "Fire watch during and 1 hour after", "required": true},
{"type": "administrative", "control": "Inspect area before, during, and after", "required": true}]',
ARRAY['FR Coveralls', 'Welding Hood', 'Welding Gloves', 'Safety Boots'],
'[{"regulation": "O. Reg. 213/91", "section": "52-66", "title": "Fire Prevention"}]'),

(NULL, 'PHYS-FIRE-002', 'Fire from Flammable Material Storage',
'Risk of fire from improper storage of flammable liquids, gases, or materials.',
'fire_explosion', 'Storage',
ARRAY['General Construction', 'Painting', 'Roofing'],
ARRAY['Material Storage'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Approved flammable storage cabinet", "required": true},
{"type": "engineering", "control": "Proper ventilation of storage area", "required": true},
{"type": "engineering", "control": "No ignition sources near storage", "required": true},
{"type": "administrative", "control": "Limit quantities on site", "required": true},
{"type": "administrative", "control": "No smoking signs posted", "required": true}]',
ARRAY[],
'[{"regulation": "O. Reg. 213/91", "section": "56", "title": "Flammable Liquid Storage"}]'),

(NULL, 'PHYS-FIRE-003', 'Propane/Fuel Fire or Explosion',
'Risk of fire or explosion from propane heaters, tanks, or fuel handling.',
'fire_explosion', 'Fuels',
ARRAY['General Construction', 'Roofing', 'All Trades'],
ARRAY['Heating', 'Equipment Fueling'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Proper cylinder storage - upright, secured", "required": true},
{"type": "engineering", "control": "Keep away from heat sources", "required": true},
{"type": "engineering", "control": "Adequate ventilation for indoor heaters", "required": true},
{"type": "administrative", "control": "No smoking near fuel", "required": true},
{"type": "administrative", "control": "Turn off heaters when unattended", "required": true},
{"type": "administrative", "control": "Inspect hoses and regulators", "required": true}]',
ARRAY['Safety Glasses', 'Safety Gloves'],
'[]'),

(NULL, 'PHYS-FIRE-004', 'Explosion from Compressed Gas Cylinders',
'Risk of explosion from mishandled, damaged, or improperly stored compressed gas cylinders.',
'fire_explosion', 'Compressed Gas',
ARRAY['Welding', 'Plumbing', 'HVAC'],
ARRAY['Welding', 'Brazing', 'Cutting'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Store cylinders upright and secured", "required": true},
{"type": "engineering", "control": "Keep oxygen and fuel gas separated", "required": true},
{"type": "engineering", "control": "Use proper regulators and flashback arrestors", "required": true},
{"type": "administrative", "control": "No oil or grease on oxygen equipment", "required": true},
{"type": "administrative", "control": "Close valves when not in use", "required": true}]',
ARRAY['Safety Glasses', 'Safety Gloves', 'Safety Boots'],
'[]'),

(NULL, 'PHYS-FIRE-005', 'Combustible Dust Explosion',
'Risk of explosion from accumulated combustible dust (wood, metal, etc.).',
'fire_explosion', 'Dust',
ARRAY['Carpentry', 'Metal Work', 'Flooring'],
ARRAY['Sanding', 'Cutting', 'Grinding'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Dust collection systems", "required": true},
{"type": "engineering", "control": "Explosion-proof equipment in dusty areas", "required": true},
{"type": "administrative", "control": "Regular cleaning to prevent accumulation", "required": true},
{"type": "administrative", "control": "No ignition sources in dusty areas", "required": true}]',
ARRAY['N95 Respirator', 'Safety Glasses'],
'[]'),

(NULL, 'PHYS-FIRE-006', 'Hot Roofing Material Fire',
'Risk of fire from hot asphalt, tar, or propane torches during roofing operations.',
'fire_explosion', 'Hot Materials',
ARRAY['Roofing', 'Waterproofing'],
ARRAY['Hot Applied Roofing', 'Torch Roofing'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Fire extinguisher at kettle/torch location", "required": true},
{"type": "engineering", "control": "Heat-resistant drip pans", "required": true},
{"type": "administrative", "control": "Hot work permit required", "required": true},
{"type": "administrative", "control": "Fire watch during and after work", "required": true},
{"type": "administrative", "control": "Inspect roof for combustibles before work", "required": true}]',
ARRAY['Leather Work Gloves', 'Face Shield', 'Safety Boots', 'FR Coveralls'],
'[{"regulation": "O. Reg. 213/91", "section": "52", "title": "Fire Prevention"}]'),

-- ============================================================================
-- PHYSICAL HAZARDS - CONFINED SPACE (4 items)
-- ============================================================================

(NULL, 'PHYS-CONF-001', 'Confined Space - Oxygen Deficiency',
'Risk of asphyxiation from low oxygen levels (<19.5%) in confined spaces.',
'confined_space', 'Atmospheric',
ARRAY['General Construction', 'Plumbing', 'Excavation'],
ARRAY['Confined Space Entry', 'Tank Entry', 'Vault Entry'],
5, 3, 'high',
'[{"type": "engineering", "control": "Mechanical ventilation before and during entry", "required": true},
{"type": "engineering", "control": "Continuous atmospheric monitoring", "required": true},
{"type": "administrative", "control": "Atmospheric testing before entry", "required": true},
{"type": "administrative", "control": "Confined space entry permit", "required": true},
{"type": "administrative", "control": "Trained attendant at entry", "required": true},
{"type": "administrative", "control": "Rescue plan and equipment ready", "required": true},
{"type": "ppe", "control": "SCBA available for rescue", "required": true}]',
ARRAY['Full Body Harness', 'Hard Hat'],
'[{"regulation": "O. Reg. 213/91", "section": "221", "title": "Confined Spaces"}]'),

(NULL, 'PHYS-CONF-002', 'Confined Space - Toxic Atmosphere',
'Risk of poisoning from toxic gases or vapours (H2S, CO, etc.) in confined spaces.',
'confined_space', 'Atmospheric',
ARRAY['General Construction', 'Plumbing'],
ARRAY['Confined Space Entry', 'Sewer Work', 'Tank Entry'],
5, 3, 'high',
'[{"type": "engineering", "control": "Continuous mechanical ventilation", "required": true},
{"type": "engineering", "control": "Multi-gas monitors (O2, LEL, H2S, CO)", "required": true},
{"type": "administrative", "control": "Air quality testing before entry", "required": true},
{"type": "administrative", "control": "Confined space entry permit", "required": true},
{"type": "ppe", "control": "Supplied air respirator when required", "required": true}]',
ARRAY['SCBA', 'Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "221", "title": "Confined Spaces"}]'),

(NULL, 'PHYS-CONF-003', 'Confined Space - Flammable Atmosphere',
'Risk of fire or explosion from flammable gases or vapours in confined spaces.',
'confined_space', 'Atmospheric',
ARRAY['General Construction', 'Plumbing'],
ARRAY['Confined Space Entry', 'Tank Entry'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Explosion-proof ventilation and lighting", "required": true},
{"type": "engineering", "control": "Continuous LEL monitoring", "required": true},
{"type": "administrative", "control": "No entry if LEL >10% of LEL", "required": true},
{"type": "administrative", "control": "No ignition sources in space", "required": true},
{"type": "administrative", "control": "Hot work permit if required", "required": true}]',
ARRAY['Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "221", "title": "Confined Spaces"}]'),

(NULL, 'PHYS-CONF-004', 'Confined Space - Engulfment',
'Risk of being trapped or buried by material in silos, hoppers, or bins.',
'confined_space', 'Engulfment',
ARRAY['General Construction'],
ARRAY['Silo Entry', 'Bin Entry', 'Hopper Work'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Lockout all material feed systems", "required": true},
{"type": "engineering", "control": "Install retrieval system", "required": true},
{"type": "administrative", "control": "Never enter onto bridged material", "required": true},
{"type": "administrative", "control": "Trained attendant at entry", "required": true}]',
ARRAY['Full Body Harness'],
'[{"regulation": "O. Reg. 213/91", "section": "221", "title": "Confined Spaces"}]'),

-- ============================================================================
-- PHYSICAL HAZARDS - NOISE & VIBRATION (4 items)
-- ============================================================================

(NULL, 'PHYS-NOISE-001', 'Noise Exposure - Power Tools',
'Risk of hearing damage from prolonged exposure to noise from power saws, grinders, drills.',
'physical', 'Noise',
ARRAY['Carpentry', 'Concrete', 'Metal Work', 'General Construction'],
ARRAY['Cutting', 'Grinding', 'Drilling'],
3, 5, 'high',
'[{"type": "engineering", "control": "Use quieter equipment where available", "required": false},
{"type": "engineering", "control": "Sound barriers/enclosures", "required": false},
{"type": "administrative", "control": "Limit exposure duration", "required": true},
{"type": "administrative", "control": "Hearing conservation program >85 dBA", "required": true},
{"type": "administrative", "control": "Audiometric testing", "required": true},
{"type": "ppe", "control": "Hearing protection required >85 dBA", "required": true}]',
ARRAY['Ear Plugs - Disposable Foam', 'Ear Muffs - Standard'],
'[{"regulation": "O. Reg. 381/15", "section": "2", "title": "Noise"}]'),

(NULL, 'PHYS-NOISE-002', 'Noise Exposure - Heavy Equipment',
'Risk of hearing damage from excavators, loaders, compactors, and other heavy equipment.',
'physical', 'Noise',
ARRAY['Excavation', 'Paving', 'Demolition', 'General Construction'],
ARRAY['Equipment Operation'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Equipment cab enclosures", "required": false},
{"type": "administrative", "control": "Keep non-essential personnel away", "required": true},
{"type": "ppe", "control": "Hearing protection for operators and nearby workers", "required": true}]',
ARRAY['Ear Plugs - Disposable Foam', 'Ear Muffs - Standard'],
'[{"regulation": "O. Reg. 381/15", "section": "2", "title": "Noise"}]'),

(NULL, 'PHYS-NOISE-003', 'Noise Exposure - Impact Work',
'Risk of hearing damage from jack hammering, pile driving, impact tools.',
'physical', 'Noise',
ARRAY['Concrete', 'Demolition', 'Foundation'],
ARRAY['Breaking', 'Pile Driving', 'Impact Work'],
3, 5, 'high',
'[{"type": "engineering", "control": "Use hydraulic breakers where possible", "required": false},
{"type": "administrative", "control": "Limit exposure time", "required": true},
{"type": "administrative", "control": "Rotate workers", "required": true},
{"type": "ppe", "control": "Dual hearing protection for high noise", "required": true}]',
ARRAY['Ear Plugs - Disposable Foam', 'Ear Muffs - Standard'],
'[{"regulation": "O. Reg. 381/15", "section": "2", "title": "Noise"}]'),

(NULL, 'PHYS-VIB-001', 'Hand-Arm Vibration',
'Risk of hand-arm vibration syndrome (HAVS) from operating vibrating tools.',
'physical', 'Vibration',
ARRAY['Concrete', 'Demolition', 'Carpentry'],
ARRAY['Jack Hammer Use', 'Impact Tools', 'Vibrating Equipment'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Use anti-vibration tools", "required": false},
{"type": "engineering", "control": "Maintain tools to minimize vibration", "required": true},
{"type": "administrative", "control": "Limit daily exposure time", "required": true},
{"type": "administrative", "control": "Take regular breaks", "required": true},
{"type": "administrative", "control": "Keep hands warm and dry", "required": true},
{"type": "ppe", "control": "Anti-vibration gloves", "required": true}]',
ARRAY['Safety Gloves'],
'[]'),

-- ============================================================================
-- PHYSICAL HAZARDS - ENVIRONMENTAL (6 items)
-- ============================================================================

(NULL, 'PHYS-ENV-001', 'Heat Stress/Heat Stroke',
'Risk of heat-related illness from hot weather, sun exposure, or hot work environments.',
'environmental', 'Temperature',
ARRAY['General Construction', 'Roofing', 'Paving', 'Concrete'],
ARRAY['Outdoor Work', 'Hot Environments'],
4, 4, 'high',
'[{"type": "engineering", "control": "Provide shade structures", "required": true},
{"type": "engineering", "control": "Cooling stations with fans/misters", "required": false},
{"type": "administrative", "control": "Work-rest schedule based on humidex", "required": true},
{"type": "administrative", "control": "Ensure adequate hydration", "required": true},
{"type": "administrative", "control": "Train workers on heat illness symptoms", "required": true},
{"type": "administrative", "control": "Schedule heavy work for cooler hours", "required": true},
{"type": "administrative", "control": "Acclimatization for new workers", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PHYS-ENV-002', 'Cold Stress/Frostbite',
'Risk of hypothermia, frostbite, or cold-related injuries from cold weather work.',
'environmental', 'Temperature',
ARRAY['General Construction', 'All Trades'],
ARRAY['Outdoor Work', 'Winter Construction'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Heated shelters/break areas", "required": true},
{"type": "engineering", "control": "Temporary enclosures with heaters", "required": false},
{"type": "administrative", "control": "Work-warming break schedule", "required": true},
{"type": "administrative", "control": "Train workers on cold stress symptoms", "required": true},
{"type": "administrative", "control": "Buddy system to watch for symptoms", "required": true},
{"type": "ppe", "control": "Insulated clothing and boots", "required": true}]',
ARRAY['Winter/Insulated Gloves', 'Safety Boots - Winter/Insulated'],
'[]'),

(NULL, 'PHYS-ENV-003', 'UV Radiation Exposure',
'Risk of sunburn, heat stroke, and skin cancer from prolonged sun exposure.',
'environmental', 'Radiation',
ARRAY['General Construction', 'Roofing', 'Paving'],
ARRAY['Outdoor Work'],
3, 4, 'medium',
'[{"type": "administrative", "control": "Schedule work to minimize peak sun exposure", "required": false},
{"type": "administrative", "control": "Use sunscreen SPF 30+", "required": true},
{"type": "administrative", "control": "Provide shade where possible", "required": true},
{"type": "ppe", "control": "Wide-brim hard hat or neck shade", "required": false},
{"type": "ppe", "control": "Long sleeves and pants", "required": false}]',
ARRAY['Safety Glasses - Tinted'],
'[]'),

(NULL, 'PHYS-ENV-004', 'High Wind Hazards',
'Risk of injuries from high winds affecting crane operations, materials, or workers at heights.',
'environmental', 'Weather',
ARRAY['Crane/Rigging', 'Roofing', 'Structural Steel'],
ARRAY['Crane Operations', 'Elevated Work'],
4, 3, 'medium',
'[{"type": "administrative", "control": "Monitor wind speeds", "required": true},
{"type": "administrative", "control": "Secure loose materials", "required": true},
{"type": "administrative", "control": "Suspend crane operations above wind limit", "required": true},
{"type": "administrative", "control": "Suspend work at heights in high winds", "required": true}]',
ARRAY[],
'[{"regulation": "O. Reg. 213/91", "section": "159", "title": "Tower Cranes - Wind"}]'),

(NULL, 'PHYS-ENV-005', 'Poor Lighting',
'Risk of accidents from inadequate lighting in work areas.',
'environmental', 'Lighting',
ARRAY['General Construction', 'All Trades'],
ARRAY['Night Work', 'Indoor Work', 'Underground'],
3, 3, 'medium',
'[{"type": "engineering", "control": "Install adequate task lighting", "required": true},
{"type": "engineering", "control": "Emergency lighting in enclosed areas", "required": true},
{"type": "engineering", "control": "Reflective markers on hazards", "required": true},
{"type": "administrative", "control": "Regular inspection of lighting", "required": true}]',
ARRAY[],
'[{"regulation": "O. Reg. 213/91", "section": "46", "title": "Lighting"}]'),

(NULL, 'PHYS-ENV-006', 'Drowning',
'Risk of drowning when working near or over water.',
'environmental', 'Water',
ARRAY['Civil', 'Marine', 'Excavation'],
ARRAY['Work Over/Near Water'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Install guardrails near water", "required": true},
{"type": "engineering", "control": "Provide rescue boats/equipment", "required": true},
{"type": "administrative", "control": "Life jacket or PFD required", "required": true},
{"type": "administrative", "control": "Swimming ability/water safety training", "required": true},
{"type": "administrative", "control": "Rescue plan and trained rescuers", "required": true}]',
ARRAY[],
'[]')

ON CONFLICT DO NOTHING;
