-- ============================================================================
-- HAZARD LIBRARY - BIOLOGICAL & ERGONOMIC HAZARDS
-- ============================================================================

-- ============================================================================
-- BIOLOGICAL HAZARDS (12 items)
-- ============================================================================

INSERT INTO hazard_library (company_id, hazard_code, name, description, category, subcategory, applicable_trades, applicable_activities, default_severity, default_likelihood, default_risk_level, recommended_controls, required_ppe, regulatory_references) VALUES

(NULL, 'BIO-001', 'Bloodborne Pathogens',
'Risk of exposure to HIV, Hepatitis B/C, and other bloodborne diseases from contact with blood or body fluids during first aid or injury response.',
'biological', 'Pathogens',
ARRAY['General Construction', 'All Trades'],
ARRAY['First Aid', 'Injury Response', 'Emergency Response'],
5, 2, 'medium',
'[{"type": "engineering", "control": "First aid kits with barrier devices", "required": true},
{"type": "administrative", "control": "Bloodborne pathogen training", "required": true},
{"type": "administrative", "control": "Universal precautions - treat all blood as infectious", "required": true},
{"type": "administrative", "control": "Post-exposure medical evaluation", "required": true},
{"type": "administrative", "control": "Hepatitis B vaccination offered", "required": true},
{"type": "ppe", "control": "Disposable gloves for any blood contact", "required": true}]',
ARRAY['Disposable Nitrile Gloves', 'CPR Barrier Mask', 'Safety Glasses'],
'[]'),

(NULL, 'BIO-002', 'Contaminated Soil',
'Risk of exposure to pathogens, heavy metals, or chemicals in contaminated soil during excavation.',
'biological', 'Contamination',
ARRAY['Excavation', 'General Construction'],
ARRAY['Excavation', 'Site Remediation'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Phase 2 ESA before excavation in suspect areas", "required": true},
{"type": "engineering", "control": "Containment and proper disposal", "required": true},
{"type": "administrative", "control": "Contaminated site procedures", "required": true},
{"type": "administrative", "control": "Health monitoring for workers", "required": true},
{"type": "ppe", "control": "Gloves, coveralls, respirator as required", "required": true}]',
ARRAY['Chemical-Resistant Gloves', 'Coveralls', 'N95 Respirator', 'Safety Boots'],
'[{"regulation": "O. Reg. 153/04", "section": "All", "title": "Contaminated Sites"}]'),

(NULL, 'BIO-003', 'Animal/Insect Bites and Stings',
'Risk of injury, infection, or allergic reaction from bites/stings from animals, insects, or spiders.',
'biological', 'Animals/Insects',
ARRAY['General Construction', 'Excavation', 'Landscaping'],
ARRAY['Outdoor Work', 'Site Clearing'],
3, 3, 'medium',
'[{"type": "administrative", "control": "Survey area for nests/hives before work", "required": true},
{"type": "administrative", "control": "First aid kit with sting relief", "required": true},
{"type": "administrative", "control": "Emergency response for severe reactions", "required": true},
{"type": "administrative", "control": "Workers with allergies carry epinephrine", "required": true}]',
ARRAY['Safety Gloves', 'Long Sleeves', 'Safety Boots'],
'[]'),

(NULL, 'BIO-004', 'Mold Exposure',
'Risk of respiratory illness, allergic reactions from mold in buildings during renovation or demolition.',
'biological', 'Fungi',
ARRAY['Demolition', 'Renovation', 'Abatement'],
ARRAY['Renovation', 'Demolition', 'Water Damage Work'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Containment of mold-affected areas", "required": true},
{"type": "engineering", "control": "Negative air pressure", "required": true},
{"type": "engineering", "control": "HEPA filtration", "required": true},
{"type": "administrative", "control": "Mold assessment before work", "required": true},
{"type": "administrative", "control": "Mold remediation procedures", "required": true},
{"type": "ppe", "control": "N95 minimum, P100 for extensive mold", "required": true}]',
ARRAY['N100/P100 Respirator', 'Disposable Coveralls', 'Safety Gloves', 'Safety Goggles'],
'[]'),

(NULL, 'BIO-005', 'Bacteria in Standing Water',
'Risk of Legionella, E. coli, and other bacterial infections from stagnant water.',
'biological', 'Bacteria',
ARRAY['General Construction', 'Plumbing'],
ARRAY['Site Drainage', 'Plumbing Work'],
3, 2, 'low',
'[{"type": "engineering", "control": "Remove standing water", "required": true},
{"type": "engineering", "control": "Flush stagnant piping before use", "required": true},
{"type": "administrative", "control": "Avoid direct contact with stagnant water", "required": true},
{"type": "ppe", "control": "Waterproof gloves and boots", "required": true}]',
ARRAY['Rubber/Neoprene Gloves', 'Rubber Boots'],
'[]'),

(NULL, 'BIO-006', 'Sewage Exposure',
'Risk of serious infection from contact with raw sewage during plumbing or excavation work.',
'biological', 'Pathogens',
ARRAY['Plumbing', 'Excavation', 'General Construction'],
ARRAY['Sewer Work', 'Sanitary Line Repair'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Minimize direct contact", "required": true},
{"type": "engineering", "control": "Proper dewatering and disposal", "required": true},
{"type": "administrative", "control": "Hepatitis A vaccination recommended", "required": true},
{"type": "administrative", "control": "Wash thoroughly after work", "required": true},
{"type": "administrative", "control": "No eating/smoking without washing", "required": true},
{"type": "ppe", "control": "Waterproof coveralls, gloves, face shield", "required": true}]',
ARRAY['Waterproof Coveralls', 'Rubber/Neoprene Gloves', 'Face Shield', 'Rubber Boots'],
'[]'),

(NULL, 'BIO-007', 'Bird/Bat Droppings (Histoplasmosis)',
'Risk of histoplasmosis fungal infection from disturbing accumulated bird or bat droppings.',
'biological', 'Fungi',
ARRAY['Demolition', 'Renovation', 'Roofing'],
ARRAY['Demolition', 'Renovation', 'Cleanup'],
4, 2, 'medium',
'[{"type": "engineering", "control": "Wet down droppings before removal", "required": true},
{"type": "engineering", "control": "Contain work area", "required": true},
{"type": "administrative", "control": "Specialized cleanup procedures", "required": true},
{"type": "administrative", "control": "Minimize dust generation", "required": true},
{"type": "ppe", "control": "N100 respirator, coveralls, gloves", "required": true}]',
ARRAY['N100/P100 Respirator', 'Disposable Coveralls', 'Safety Gloves', 'Safety Goggles'],
'[]'),

(NULL, 'BIO-008', 'Rodent Droppings (Hantavirus)',
'Risk of hantavirus from exposure to rodent droppings, urine, or nesting materials.',
'biological', 'Pathogens',
ARRAY['Demolition', 'Renovation', 'General Construction'],
ARRAY['Demolition', 'Cleanup', 'Renovation'],
5, 2, 'medium',
'[{"type": "engineering", "control": "Wet down materials before cleanup", "required": true},
{"type": "engineering", "control": "Ventilate area before entry", "required": true},
{"type": "administrative", "control": "Never sweep or vacuum dry droppings", "required": true},
{"type": "administrative", "control": "Disinfect affected areas", "required": true},
{"type": "ppe", "control": "P100 respirator, disposable coveralls, gloves", "required": true}]',
ARRAY['N100/P100 Respirator', 'Disposable Coveralls', 'Safety Gloves', 'Safety Goggles'],
'[]'),

(NULL, 'BIO-009', 'Tick-Borne Illness (Lyme Disease)',
'Risk of Lyme disease and other tick-borne illnesses when working in wooded or grassy areas.',
'biological', 'Insects',
ARRAY['General Construction', 'Excavation', 'Landscaping', 'Civil'],
ARRAY['Site Clearing', 'Rural Construction'],
4, 3, 'medium',
'[{"type": "administrative", "control": "Wear light-colored clothing to spot ticks", "required": true},
{"type": "administrative", "control": "Tuck pants into socks", "required": true},
{"type": "administrative", "control": "Check for ticks after work in risk areas", "required": true},
{"type": "administrative", "control": "Know symptoms of Lyme disease", "required": true},
{"type": "ppe", "control": "Long sleeves and pants", "required": true}]',
ARRAY['Long Pants', 'Long Sleeves', 'Safety Boots'],
'[]'),

(NULL, 'BIO-010', 'Venomous Snakes',
'Risk of snakebite when working in areas with venomous snakes (rare in Ontario but possible).',
'biological', 'Animals',
ARRAY['General Construction', 'Excavation', 'Landscaping'],
ARRAY['Site Clearing', 'Rural Construction'],
5, 1, 'low',
'[{"type": "administrative", "control": "Survey area before work", "required": true},
{"type": "administrative", "control": "Know local snake species", "required": true},
{"type": "administrative", "control": "First aid and emergency transport plan", "required": true},
{"type": "ppe", "control": "Leather boots, snake gaiters in high-risk areas", "required": false}]',
ARRAY['Safety Boots'],
'[]'),

(NULL, 'BIO-011', 'Poison Ivy/Oak/Sumac',
'Risk of allergic contact dermatitis from contact with urushiol oil in poison ivy, oak, or sumac.',
'biological', 'Plants',
ARRAY['General Construction', 'Excavation', 'Landscaping'],
ARRAY['Site Clearing', 'Outdoor Work'],
2, 4, 'medium',
'[{"type": "administrative", "control": "Learn to identify plants", "required": true},
{"type": "administrative", "control": "Wash immediately after potential contact", "required": true},
{"type": "administrative", "control": "Clean tools that contacted plants", "required": true},
{"type": "ppe", "control": "Long sleeves, gloves when clearing brush", "required": true}]',
ARRAY['Safety Gloves', 'Long Sleeves', 'Safety Boots'],
'[]'),

(NULL, 'BIO-012', 'Giant Hogweed Burns',
'Risk of severe phototoxic burns from contact with giant hogweed sap, followed by sun exposure.',
'biological', 'Plants',
ARRAY['General Construction', 'Landscaping', 'Excavation'],
ARRAY['Site Clearing'],
5, 2, 'medium',
'[{"type": "administrative", "control": "Learn to identify giant hogweed", "required": true},
{"type": "administrative", "control": "Do not touch - report to supervisor", "required": true},
{"type": "administrative", "control": "Specialist removal required", "required": true},
{"type": "administrative", "control": "If contacted, wash immediately and avoid sunlight", "required": true}]',
ARRAY['Coveralls', 'Chemical-Resistant Gloves', 'Face Shield'],
'[]'),

-- ============================================================================
-- ERGONOMIC HAZARDS (15 items)
-- ============================================================================

(NULL, 'ERGO-001', 'Manual Material Handling - Heavy Lifting',
'Risk of back injury, sprains, strains from lifting heavy materials without mechanical assistance.',
'ergonomic', 'Lifting',
ARRAY['General Construction', 'All Trades'],
ARRAY['Material Handling', 'Loading/Unloading'],
4, 5, 'high',
'[{"type": "engineering", "control": "Use mechanical lifting aids (forklift, hoist, cart)", "required": false},
{"type": "engineering", "control": "Store materials at waist height", "required": false},
{"type": "engineering", "control": "Reduce package/unit weights", "required": false},
{"type": "administrative", "control": "Team lifting for loads over 23kg", "required": true},
{"type": "administrative", "control": "Safe lifting technique training", "required": true},
{"type": "administrative", "control": "Pre-job warm-up stretches", "required": true},
{"type": "administrative", "control": "Keep loads close to body", "required": true}]',
ARRAY['Safety Gloves', 'Safety Boots'],
'[]'),

(NULL, 'ERGO-002', 'Repetitive Motion Injuries',
'Risk of carpal tunnel, tendinitis, and other repetitive strain injuries from repeated motions.',
'ergonomic', 'Repetitive Motion',
ARRAY['General Construction', 'Carpentry', 'Drywall', 'Electrical'],
ARRAY['Fastening', 'Finishing', 'Wire Pulling'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Use power tools to reduce repetition", "required": false},
{"type": "engineering", "control": "Ergonomic tool design", "required": false},
{"type": "administrative", "control": "Job rotation", "required": true},
{"type": "administrative", "control": "Regular breaks", "required": true},
{"type": "administrative", "control": "Stretching exercises", "required": true}]',
ARRAY['Safety Gloves'],
'[]'),

(NULL, 'ERGO-003', 'Awkward Postures',
'Risk of musculoskeletal injury from working in bent, twisted, or uncomfortable positions.',
'ergonomic', 'Posture',
ARRAY['General Construction', 'Plumbing', 'Electrical', 'HVAC'],
ARRAY['Installation', 'Maintenance', 'Repair'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Design work at comfortable heights", "required": false},
{"type": "engineering", "control": "Use adjustable work platforms", "required": false},
{"type": "engineering", "control": "Pre-fabricate assemblies at bench height", "required": false},
{"type": "administrative", "control": "Take frequent posture breaks", "required": true},
{"type": "administrative", "control": "Alternate between tasks", "required": true}]',
ARRAY['Knee Pads'],
'[]'),

(NULL, 'ERGO-004', 'Prolonged Standing',
'Risk of leg, back, and foot problems from extended standing on hard surfaces.',
'ergonomic', 'Standing',
ARRAY['General Construction', 'Concrete', 'All Trades'],
ARRAY['Finish Work', 'Inspection', 'Supervision'],
2, 4, 'medium',
'[{"type": "engineering", "control": "Anti-fatigue mats where stationary work required", "required": false},
{"type": "administrative", "control": "Take seated breaks", "required": true},
{"type": "administrative", "control": "Shift weight and move regularly", "required": true},
{"type": "ppe", "control": "Supportive footwear with cushioning", "required": true}]',
ARRAY['Safety Boots'],
'[]'),

(NULL, 'ERGO-005', 'Kneeling and Squatting',
'Risk of knee injuries and musculoskeletal problems from prolonged kneeling or squatting.',
'ergonomic', 'Kneeling',
ARRAY['Concrete', 'Flooring', 'Plumbing', 'Electrical', 'Roofing'],
ARRAY['Concrete Finishing', 'Floor Installation', 'Low Work'],
3, 5, 'high',
'[{"type": "engineering", "control": "Knee boards, kneeling creepers", "required": true},
{"type": "engineering", "control": "Mechanical finishing equipment", "required": false},
{"type": "administrative", "control": "Limit kneeling duration", "required": true},
{"type": "administrative", "control": "Alternate between kneeling and standing", "required": true},
{"type": "ppe", "control": "Knee pads required for kneeling work", "required": true}]',
ARRAY['Knee Pads'],
'[]'),

(NULL, 'ERGO-006', 'Overhead Work',
'Risk of shoulder, neck, and back injuries from extended work above head height.',
'ergonomic', 'Overhead',
ARRAY['Electrical', 'Drywall', 'HVAC', 'Plumbing', 'Painting'],
ARRAY['Ceiling Work', 'Installation', 'Sprinkler Systems'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Use elevated work platforms", "required": false},
{"type": "engineering", "control": "Pre-assemble at lower levels", "required": false},
{"type": "engineering", "control": "Extension tools", "required": false},
{"type": "administrative", "control": "Frequent rest breaks", "required": true},
{"type": "administrative", "control": "Job rotation", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'ERGO-007', 'Vibrating Tool Use (Hand-Arm)',
'Risk of hand-arm vibration syndrome (HAVS), carpal tunnel from vibrating tool use.',
'ergonomic', 'Vibration',
ARRAY['Concrete', 'Demolition', 'Carpentry', 'Metal Work'],
ARRAY['Jack Hammer', 'Impact Tools', 'Concrete Vibrators'],
4, 4, 'high',
'[{"type": "engineering", "control": "Use anti-vibration tools", "required": false},
{"type": "engineering", "control": "Maintain tools to minimize vibration", "required": true},
{"type": "administrative", "control": "Limit daily trigger time", "required": true},
{"type": "administrative", "control": "Take regular breaks from vibrating tools", "required": true},
{"type": "administrative", "control": "Keep hands warm", "required": true},
{"type": "ppe", "control": "Anti-vibration gloves", "required": true}]',
ARRAY['Safety Gloves'],
'[]'),

(NULL, 'ERGO-008', 'Whole Body Vibration',
'Risk of back pain and spinal injuries from operating vibrating equipment (vehicles, compactors).',
'ergonomic', 'Vibration',
ARRAY['Excavation', 'Paving', 'Equipment Operation'],
ARRAY['Equipment Operation', 'Compacting'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Well-maintained equipment with good suspension", "required": true},
{"type": "engineering", "control": "Air-ride seats", "required": false},
{"type": "administrative", "control": "Limit daily exposure time", "required": true},
{"type": "administrative", "control": "Take breaks from equipment operation", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'ERGO-009', 'Static Postures',
'Risk of musculoskeletal discomfort from holding positions for extended periods.',
'ergonomic', 'Static Work',
ARRAY['General Construction', 'Welding', 'Painting'],
ARRAY['Welding', 'Finishing', 'Detailed Work'],
2, 4, 'medium',
'[{"type": "administrative", "control": "Change positions frequently", "required": true},
{"type": "administrative", "control": "Micro-breaks for stretching", "required": true},
{"type": "engineering", "control": "Adjustable work positioning", "required": false}]',
ARRAY[],
'[]'),

(NULL, 'ERGO-010', 'Heavy Concrete Forms (Manual Handling)',
'Risk of back and musculoskeletal injury from handling heavy formwork panels.',
'ergonomic', 'Lifting',
ARRAY['Formwork', 'Concrete'],
ARRAY['Formwork Erection', 'Form Stripping'],
4, 4, 'high',
'[{"type": "engineering", "control": "Use crane for large panels", "required": false},
{"type": "engineering", "control": "Modular formwork systems", "required": false},
{"type": "engineering", "control": "Form handling equipment", "required": false},
{"type": "administrative", "control": "Team lifting", "required": true},
{"type": "administrative", "control": "Safe lifting techniques", "required": true}]',
ARRAY['Safety Gloves', 'Safety Boots'],
'[]'),

(NULL, 'ERGO-011', 'Rebar Handling and Tying',
'Risk of back strain, cuts, and repetitive injury from handling and tying reinforcing steel.',
'ergonomic', 'Repetitive Motion',
ARRAY['Concrete', 'Rebar'],
ARRAY['Rebar Installation', 'Tying'],
3, 5, 'high',
'[{"type": "engineering", "control": "Power rebar tying tools", "required": false},
{"type": "engineering", "control": "Pre-fabricate cages off-site", "required": false},
{"type": "administrative", "control": "Rotate between tying and other tasks", "required": true},
{"type": "administrative", "control": "Use proper bending posture", "required": true}]',
ARRAY['Safety Gloves', 'Knee Pads'],
'[]'),

(NULL, 'ERGO-012', 'Screeding and Finishing (Ergonomic)',
'Risk of back, shoulder, and arm strain from manual screeding and power trowel operations.',
'ergonomic', 'Repetitive Motion',
ARRAY['Concrete'],
ARRAY['Concrete Finishing'],
3, 5, 'high',
'[{"type": "engineering", "control": "Laser screed equipment", "required": false},
{"type": "engineering", "control": "Ride-on power trowels", "required": false},
{"type": "administrative", "control": "Rotate crews", "required": true},
{"type": "administrative", "control": "Adequate rest breaks", "required": true}]',
ARRAY['Knee Pads', 'Safety Boots', 'Safety Glasses'],
'[]'),

(NULL, 'ERGO-013', 'Pushing/Pulling Heavy Loads',
'Risk of shoulder, back, and leg injuries from pushing or pulling heavy carts, equipment, or materials.',
'ergonomic', 'Force',
ARRAY['General Construction', 'All Trades'],
ARRAY['Material Moving', 'Equipment Setup'],
3, 4, 'medium',
'[{"type": "engineering", "control": "Use powered equipment where possible", "required": false},
{"type": "engineering", "control": "Ensure good caster/wheel condition", "required": true},
{"type": "engineering", "control": "Level pathways", "required": true},
{"type": "administrative", "control": "Push rather than pull where possible", "required": true},
{"type": "administrative", "control": "Get help for heavy loads", "required": true}]',
ARRAY['Safety Gloves', 'Safety Boots'],
'[]'),

(NULL, 'ERGO-014', 'Carrying Loads on Stairs/Ladders',
'Risk of falls and musculoskeletal injury from carrying loads while climbing.',
'ergonomic', 'Carrying',
ARRAY['General Construction', 'All Trades'],
ARRAY['Material Moving', 'Tool Transport'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Use hoisting equipment", "required": false},
{"type": "engineering", "control": "Material lifts/conveyors", "required": false},
{"type": "administrative", "control": "Reduce load sizes for carrying on stairs", "required": true},
{"type": "administrative", "control": "Maintain 3-point contact on ladders", "required": true},
{"type": "administrative", "control": "Use tool belts or hoist tools on ladders", "required": true}]',
ARRAY['Safety Boots'],
'[]'),

(NULL, 'ERGO-015', 'Sustained Gripping',
'Risk of hand and wrist strain from sustained gripping of tools or materials.',
'ergonomic', 'Grip',
ARRAY['Carpentry', 'Masonry', 'Plumbing', 'General Construction'],
ARRAY['Hand Tool Use', 'Material Handling'],
2, 4, 'medium',
'[{"type": "engineering", "control": "Ergonomic tool handles", "required": false},
{"type": "engineering", "control": "Spring-loaded or power tools", "required": false},
{"type": "administrative", "control": "Alternate gripping tasks", "required": true},
{"type": "administrative", "control": "Hand stretches", "required": true}]',
ARRAY['Safety Gloves'],
'[]')

ON CONFLICT DO NOTHING;
