-- ============================================================================
-- HAZARD LIBRARY - PSYCHOSOCIAL HAZARDS (12 items)
-- ============================================================================

INSERT INTO hazard_library (company_id, hazard_code, name, description, category, subcategory, applicable_trades, applicable_activities, default_severity, default_likelihood, default_risk_level, recommended_controls, required_ppe, regulatory_references) VALUES

(NULL, 'PSYCH-001', 'Workplace Violence',
'Risk of physical assault or threatening behaviour from co-workers, contractors, or the public.',
'psychosocial', 'Violence',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
5, 2, 'medium',
'[{"type": "administrative", "control": "Workplace violence policy and procedures", "required": true},
{"type": "administrative", "control": "Violence risk assessment", "required": true},
{"type": "administrative", "control": "Training on recognizing and responding to violence", "required": true},
{"type": "administrative", "control": "Reporting mechanisms", "required": true},
{"type": "administrative", "control": "Emergency response procedures", "required": true}]',
ARRAY[],
'[{"regulation": "OHSA", "section": "32.0.1-32.0.8", "title": "Workplace Violence and Harassment"}]'),

(NULL, 'PSYCH-002', 'Workplace Harassment',
'Risk of psychological harm from harassment, bullying, or discrimination.',
'psychosocial', 'Harassment',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
4, 3, 'medium',
'[{"type": "administrative", "control": "Workplace harassment policy", "required": true},
{"type": "administrative", "control": "Anti-harassment training", "required": true},
{"type": "administrative", "control": "Confidential reporting system", "required": true},
{"type": "administrative", "control": "Investigation procedures", "required": true}]',
ARRAY[],
'[{"regulation": "OHSA", "section": "32.0.1-32.0.8", "title": "Workplace Violence and Harassment"}]'),

(NULL, 'PSYCH-003', 'Fatigue from Long Hours',
'Risk of accidents and health issues from excessive work hours, inadequate rest, and fatigue.',
'psychosocial', 'Fatigue',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
4, 4, 'high',
'[{"type": "administrative", "control": "Reasonable work hour limits", "required": true},
{"type": "administrative", "control": "Adequate rest break scheduling", "required": true},
{"type": "administrative", "control": "Fatigue management training", "required": true},
{"type": "administrative", "control": "Monitor for signs of fatigue", "required": true},
{"type": "administrative", "control": "No critical tasks when fatigued", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-004', 'Work Pressure and Stress',
'Risk of psychological harm and unsafe behaviour from excessive production pressure or unrealistic deadlines.',
'psychosocial', 'Stress',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
3, 4, 'medium',
'[{"type": "administrative", "control": "Realistic scheduling and staffing", "required": true},
{"type": "administrative", "control": "Clear communication of expectations", "required": true},
{"type": "administrative", "control": "Open door policy for concerns", "required": true},
{"type": "administrative", "control": "Employee assistance program (EAP)", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-005', 'Lone Worker Hazards',
'Risk of delayed emergency response and psychological stress from working alone or in isolated locations.',
'psychosocial', 'Isolation',
ARRAY['General Construction', 'All Trades'],
ARRAY['Remote Work', 'Night Shift', 'Security'],
4, 3, 'medium',
'[{"type": "engineering", "control": "Panic alarms/man-down devices", "required": false},
{"type": "administrative", "control": "Regular check-in procedures", "required": true},
{"type": "administrative", "control": "Working alone policy", "required": true},
{"type": "administrative", "control": "Communication devices always available", "required": true},
{"type": "administrative", "control": "Emergency response plan for lone workers", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-006', 'Substance Abuse (Impairment)',
'Risk of accidents from workers impaired by alcohol, drugs, or medications.',
'psychosocial', 'Impairment',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
5, 2, 'medium',
'[{"type": "administrative", "control": "Drug and alcohol policy", "required": true},
{"type": "administrative", "control": "Fitness for duty assessments", "required": true},
{"type": "administrative", "control": "Training on recognizing impairment", "required": true},
{"type": "administrative", "control": "Access to addiction support services", "required": true},
{"type": "administrative", "control": "Clear consequences for violation", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-007', 'Mental Health Crisis',
'Risk of suicide or self-harm crisis among workers. Construction has elevated mental health and suicide rates.',
'psychosocial', 'Mental Health',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
5, 2, 'medium',
'[{"type": "administrative", "control": "Mental health awareness training", "required": true},
{"type": "administrative", "control": "Promote EAP and mental health resources", "required": true},
{"type": "administrative", "control": "Reduce stigma through open discussion", "required": true},
{"type": "administrative", "control": "Crisis intervention resources available", "required": true},
{"type": "administrative", "control": "Suicide prevention training for supervisors", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-008', 'Traumatic Event Exposure',
'Risk of PTSD, psychological harm from witnessing serious injuries, fatalities, or traumatic events.',
'psychosocial', 'Trauma',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
5, 2, 'medium',
'[{"type": "administrative", "control": "Critical incident stress debriefing", "required": true},
{"type": "administrative", "control": "Access to counseling services", "required": true},
{"type": "administrative", "control": "Follow-up support for affected workers", "required": true},
{"type": "administrative", "control": "Trained peer support", "required": false}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-009', 'Language Barrier Risks',
'Risk of accidents due to inability to understand safety instructions or communicate hazards.',
'psychosocial', 'Communication',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
4, 3, 'medium',
'[{"type": "administrative", "control": "Training in workers primary language", "required": true},
{"type": "administrative", "control": "Visual safety signage and pictograms", "required": true},
{"type": "administrative", "control": "Bilingual supervisors where needed", "required": true},
{"type": "administrative", "control": "Simple, clear communication", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-010', 'Inexperienced Worker Risk',
'Risk of accidents due to inadequate experience, training, or supervision of new workers.',
'psychosocial', 'Inexperience',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
4, 4, 'high',
'[{"type": "administrative", "control": "New worker orientation program", "required": true},
{"type": "administrative", "control": "Buddy system for new workers", "required": true},
{"type": "administrative", "control": "Close supervision for first days/weeks", "required": true},
{"type": "administrative", "control": "Progressive task assignment", "required": true},
{"type": "administrative", "control": "Verify competency before independent work", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-011', 'Seasonal/Temporary Worker Risk',
'Risk from high turnover, less familiar workers, and reduced safety culture among temporary staff.',
'psychosocial', 'Turnover',
ARRAY['General Construction', 'All Trades'],
ARRAY['All Activities'],
3, 4, 'medium',
'[{"type": "administrative", "control": "Site-specific orientation for all temp workers", "required": true},
{"type": "administrative", "control": "Verify training and competencies", "required": true},
{"type": "administrative", "control": "Include temp workers in safety meetings", "required": true},
{"type": "administrative", "control": "Clear communication of hazards", "required": true}]',
ARRAY[],
'[]'),

(NULL, 'PSYCH-012', 'Public Interface Hazards',
'Risk from interactions with public when working on occupied sites, adjacent to traffic, or public spaces.',
'psychosocial', 'Public',
ARRAY['Civil', 'General Construction', 'Utility'],
ARRAY['Roadwork', 'Public Works', 'Occupied Building Work'],
3, 3, 'medium',
'[{"type": "engineering", "control": "Clear site barriers and signage", "required": true},
{"type": "engineering", "control": "Traffic control devices", "required": true},
{"type": "administrative", "control": "Public communication and notifications", "required": true},
{"type": "administrative", "control": "Security presence where needed", "required": false}]',
ARRAY['Hi-Vis Vest'],
'[]')

ON CONFLICT DO NOTHING;
