-- ============================================================================
-- EXTENDED HAZARD LIBRARY - PART 1
-- ============================================================================
-- Additional construction hazards organized by category
-- ============================================================================

-- ============================================================================
-- FALL HAZARDS (Extended)
-- ============================================================================

INSERT INTO hazard_library (company_id, hazard_code, name, description, category, subcategory, applicable_trades, applicable_activities, default_severity, default_likelihood, default_risk_level, recommended_controls, required_ppe, regulatory_references) VALUES

-- Ladder hazards
(NULL, 'HAZ-FALL-011', 'Falls from step ladders', 'Risk of falling from step ladders due to overreaching, improper setup, or damaged equipment', 'fall', 'Ladders', ARRAY['General Construction', 'Electrical', 'Painting', 'HVAC'], ARRAY['Step Ladder Work'], 3, 3, 'medium', '[{"type": "engineering", "control": "Use platform ladder where possible", "required": false}, {"type": "administrative", "control": "Never stand on top two steps", "required": true}, {"type": "administrative", "control": "Pre-use inspection", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "78", "title": "Ladders"}]'),

(NULL, 'HAZ-FALL-012', 'Falls from A-frame ladders', 'Risk of falling from A-frame/trestle ladders during work', 'fall', 'Ladders', ARRAY['Painting', 'Drywall', 'Electrical'], ARRAY['Low Height Work'], 3, 3, 'medium', '[{"type": "engineering", "control": "Ensure spreaders fully locked", "required": true}, {"type": "administrative", "control": "Do not overreach", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "78", "title": "Ladders"}]'),

(NULL, 'HAZ-FALL-013', 'Falls from mobile scaffolds', 'Risk of falling from rolling/mobile scaffold towers', 'fall', 'Scaffolds', ARRAY['Painting', 'Drywall', 'Electrical', 'HVAC'], ARRAY['Mobile Scaffold Work'], 4, 3, 'medium', '[{"type": "engineering", "control": "Lock casters before use", "required": true}, {"type": "engineering", "control": "Install guardrails", "required": true}, {"type": "administrative", "control": "Never move with workers on platform", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "130", "title": "Rolling Scaffolds"}]'),

(NULL, 'HAZ-FALL-014', 'Falls from suspended scaffolds', 'Risk of falling from swing stage or suspended scaffolds', 'fall', 'Scaffolds', ARRAY['Painting', 'Glazing', 'Masonry'], ARRAY['Suspended Scaffold Work'], 5, 2, 'medium', '[{"type": "engineering", "control": "Independent lifeline required", "required": true}, {"type": "ppe", "control": "Fall arrest connected to lifeline", "required": true}, {"type": "administrative", "control": "Daily inspection before use", "required": true}]', ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness', 'Rope Grab'], '[{"regulation": "O. Reg. 213/91", "section": "137-142", "title": "Suspended Scaffolds"}]'),

(NULL, 'HAZ-FALL-015', 'Falls during roof access/egress', 'Risk of falling while accessing or leaving roof areas', 'fall', 'Working at Heights', ARRAY['Roofing', 'HVAC', 'General Construction'], ARRAY['Roof Access'], 4, 3, 'medium', '[{"type": "engineering", "control": "Install permanent roof access", "required": false}, {"type": "engineering", "control": "Secure ladder at roof edge", "required": true}, {"type": "ppe", "control": "Fall protection during transition", "required": true}]', ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'], '[{"regulation": "O. Reg. 213/91", "section": "26", "title": "Fall Protection"}]'),

(NULL, 'HAZ-FALL-016', 'Falls from mast climbing platforms', 'Risk of falling from mast climbing work platforms', 'fall', 'Elevated Platforms', ARRAY['Masonry', 'Glazing', 'General Construction'], ARRAY['Mast Climber Work'], 5, 2, 'medium', '[{"type": "engineering", "control": "Guardrails on all sides", "required": true}, {"type": "administrative", "control": "Trained operator only", "required": true}, {"type": "administrative", "control": "Daily inspection", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "143", "title": "Work Platforms"}]'),

(NULL, 'HAZ-FALL-017', 'Falls through fragile roofing', 'Risk of falling through skylights, fiberglass panels, or deteriorated roofing', 'fall', 'Working at Heights', ARRAY['Roofing', 'HVAC', 'General Construction'], ARRAY['Roofing Work', 'Equipment Installation'], 5, 3, 'high', '[{"type": "engineering", "control": "Install covers or guardrails around skylights", "required": true}, {"type": "administrative", "control": "Identify all fragile surfaces", "required": true}, {"type": "ppe", "control": "Fall arrest when near fragile surfaces", "required": true}]', ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'], '[{"regulation": "O. Reg. 213/91", "section": "26.3", "title": "Covers"}]'),

(NULL, 'HAZ-FALL-018', 'Falls from loading docks', 'Risk of falling from loading dock edges', 'fall', 'Slips/Trips', ARRAY['General Construction', 'General Labour'], ARRAY['Material Delivery', 'Loading/Unloading'], 3, 3, 'medium', '[{"type": "engineering", "control": "Install dock barriers", "required": false}, {"type": "administrative", "control": "Awareness of edge location", "required": true}]', ARRAY['Safety Boots', 'Hi-Vis Vest'], '[]'),

(NULL, 'HAZ-FALL-019', 'Falls into shafts/stairwells', 'Risk of falling into open elevator shafts or stairwells under construction', 'fall', 'Working at Heights', ARRAY['General Construction', 'Elevator', 'Electrical'], ARRAY['Shaft Work', 'Stairwell Construction'], 5, 3, 'high', '[{"type": "engineering", "control": "Install guardrails at all openings", "required": true}, {"type": "engineering", "control": "Install safety netting", "required": false}]', ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness'], '[{"regulation": "O. Reg. 213/91", "section": "26.1", "title": "Guardrails"}]'),

(NULL, 'HAZ-FALL-020', 'Falls from precast installation', 'Risk of falling during precast concrete panel installation', 'fall', 'Working at Heights', ARRAY['Concrete', 'Structural Steel'], ARRAY['Precast Erection'], 5, 3, 'high', '[{"type": "engineering", "control": "Install temporary guardrails on panels", "required": true}, {"type": "ppe", "control": "100% tie-off fall protection", "required": true}]', ARRAY['Hard Hat', 'Safety Boots', 'Full Body Harness', 'SRL'], '[{"regulation": "O. Reg. 213/91", "section": "103", "title": "Precast Concrete"}]'),

-- Additional slip/trip hazards
(NULL, 'HAZ-FALL-021', 'Slips on concrete form release agents', 'Risk of slipping on oily surfaces from form release agents', 'fall', 'Slips/Trips', ARRAY['Concrete', 'Formwork'], ARRAY['Form Work', 'Concrete Placement'], 3, 4, 'medium', '[{"type": "administrative", "control": "Clean up excess release agent", "required": true}, {"type": "ppe", "control": "Non-slip footwear", "required": true}]', ARRAY['Safety Boots'], '[]'),

(NULL, 'HAZ-FALL-022', 'Trips on reinforcing steel', 'Risk of tripping over rebar, mesh, or tie wire', 'fall', 'Slips/Trips', ARRAY['Concrete', 'General Construction'], ARRAY['Rebar Installation', 'Concrete Placement'], 3, 4, 'medium', '[{"type": "engineering", "control": "Cap exposed rebar ends", "required": true}, {"type": "administrative", "control": "Maintain clear walkways", "required": true}]', ARRAY['Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "35", "title": "Housekeeping"}]'),

(NULL, 'HAZ-FALL-023', 'Trips on uneven surfaces', 'Risk of tripping on uneven ground, rubble, or construction debris', 'fall', 'Slips/Trips', ARRAY['General Construction', 'Excavation', 'Demolition'], ARRAY['Site Work', 'Demolition'], 2, 4, 'medium', '[{"type": "administrative", "control": "Maintain level walking surfaces", "required": true}, {"type": "administrative", "control": "Good housekeeping", "required": true}]', ARRAY['Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "35", "title": "Housekeeping"}]'),

(NULL, 'HAZ-FALL-024', 'Falls on stairs under construction', 'Risk of falling on temporary or incomplete stairways', 'fall', 'Slips/Trips', ARRAY['General Construction', 'Carpentry'], ARRAY['Stair Installation', 'Access'], 4, 3, 'medium', '[{"type": "engineering", "control": "Install temporary handrails", "required": true}, {"type": "engineering", "control": "Ensure adequate lighting", "required": true}]', ARRAY['Safety Boots', 'Hard Hat'], '[{"regulation": "O. Reg. 213/91", "section": "73", "title": "Stairs and Landings"}]'),

-- STRUCK BY HAZARDS (Extended)
(NULL, 'HAZ-STRUCK-007', 'Struck by falling formwork', 'Risk of being struck by falling form panels, shores, or hardware', 'struck_by', 'Falling Objects', ARRAY['Formwork', 'Concrete'], ARRAY['Form Stripping', 'Form Erection'], 5, 3, 'high', '[{"type": "engineering", "control": "Use form release procedures", "required": true}, {"type": "administrative", "control": "Exclusion zone during stripping", "required": true}, {"type": "ppe", "control": "Hard hat required", "required": true}]', ARRAY['Hard Hat', 'Safety Boots', 'Safety Glasses'], '[{"regulation": "O. Reg. 213/91", "section": "93", "title": "Formwork Removal"}]'),

(NULL, 'HAZ-STRUCK-008', 'Struck by scaffold components', 'Risk of being struck by falling scaffold tubes, boards, or clamps', 'struck_by', 'Falling Objects', ARRAY['Scaffolding', 'General Construction'], ARRAY['Scaffold Erection', 'Scaffold Dismantling'], 4, 3, 'medium', '[{"type": "engineering", "control": "Use material hoisting", "required": false}, {"type": "administrative", "control": "Exclusion zone below", "required": true}, {"type": "administrative", "control": "Pass components hand-to-hand", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "125", "title": "Scaffolds"}]'),

(NULL, 'HAZ-STRUCK-009', 'Struck by excavator bucket/boom', 'Risk of being struck by excavator swing or bucket', 'struck_by', 'Moving Equipment', ARRAY['Excavation', 'General Construction'], ARRAY['Excavation', 'Material Moving'], 5, 2, 'medium', '[{"type": "engineering", "control": "Keep clear of swing radius", "required": true}, {"type": "administrative", "control": "Eye contact with operator", "required": true}, {"type": "administrative", "control": "Designated walkways around equipment", "required": true}]', ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "104", "title": "Equipment"}]'),

(NULL, 'HAZ-STRUCK-010', 'Struck by dump truck', 'Risk of being struck by dump trucks during backing or dumping', 'struck_by', 'Vehicles', ARRAY['Excavation', 'Paving', 'General Construction'], ARRAY['Material Delivery', 'Backfill'], 5, 3, 'high', '[{"type": "engineering", "control": "Backup alarm required", "required": true}, {"type": "administrative", "control": "Spotter required for backing", "required": true}, {"type": "ppe", "control": "High visibility clothing", "required": true}]', ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "67", "title": "Signallers"}]'),

(NULL, 'HAZ-STRUCK-011', 'Struck by concrete pump boom', 'Risk of being struck by concrete pump boom during positioning', 'struck_by', 'Moving Equipment', ARRAY['Concrete'], ARRAY['Concrete Placement'], 5, 2, 'medium', '[{"type": "administrative", "control": "Keep clear during boom movement", "required": true}, {"type": "administrative", "control": "Communication with pump operator", "required": true}]', ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'], '[]'),

(NULL, 'HAZ-STRUCK-012', 'Struck by nail gun discharge', 'Risk of being struck by nails from pneumatic nail guns', 'struck_by', 'Power Tools', ARRAY['Carpentry', 'Formwork', 'Roofing'], ARRAY['Framing', 'Sheathing', 'Formwork'], 4, 3, 'medium', '[{"type": "engineering", "control": "Use sequential trigger", "required": true}, {"type": "administrative", "control": "Never point at others", "required": true}, {"type": "administrative", "control": "Disconnect when not in use", "required": true}]', ARRAY['Safety Glasses', 'Hard Hat'], '[]'),

(NULL, 'HAZ-STRUCK-013', 'Struck by suspended load', 'Risk of being struck by loads during crane or hoist operations', 'struck_by', 'Moving Objects', ARRAY['Crane/Rigging', 'General Construction'], ARRAY['Lifting Operations'], 5, 2, 'medium', '[{"type": "engineering", "control": "Barricade lift zone", "required": true}, {"type": "administrative", "control": "Never stand under suspended loads", "required": true}, {"type": "administrative", "control": "Use tag lines", "required": true}]', ARRAY['Hard Hat', 'Hi-Vis Vest', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "157", "title": "Hoisting"}]'),

(NULL, 'HAZ-STRUCK-014', 'Struck by material during hoisting', 'Risk of being struck by materials being hoisted by crane or derrick', 'struck_by', 'Moving Objects', ARRAY['Crane/Rigging', 'Structural Steel', 'Concrete'], ARRAY['Material Hoisting'], 5, 2, 'medium', '[{"type": "administrative", "control": "Stay out of drop zone", "required": true}, {"type": "administrative", "control": "Secure all loads properly", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "157", "title": "Hoisting"}]'),

(NULL, 'HAZ-STRUCK-015', 'Struck by concrete during pour', 'Risk of being struck by concrete from pump hose or chute', 'struck_by', 'Materials', ARRAY['Concrete'], ARRAY['Concrete Placement'], 3, 3, 'medium', '[{"type": "administrative", "control": "Position safely during pour", "required": true}, {"type": "ppe", "control": "Face shield for pump work", "required": false}]', ARRAY['Hard Hat', 'Safety Glasses', 'Safety Boots'], '[]'),

(NULL, 'HAZ-STRUCK-016', 'Struck by breaking cable/chain', 'Risk of being struck by failed rigging components under tension', 'struck_by', 'Moving Objects', ARRAY['Crane/Rigging', 'General Construction'], ARRAY['Rigging', 'Tensioning'], 5, 2, 'medium', '[{"type": "administrative", "control": "Inspect rigging before use", "required": true}, {"type": "administrative", "control": "Never exceed WLL", "required": true}, {"type": "administrative", "control": "Stand clear of tension line", "required": true}]', ARRAY['Hard Hat', 'Safety Glasses'], '[{"regulation": "O. Reg. 213/91", "section": "172", "title": "Wire Rope"}]'),

-- CAUGHT IN/BETWEEN HAZARDS (Extended)
(NULL, 'HAZ-CAUGHT-005', 'Caught in concrete mixer', 'Risk of entanglement in rotating concrete mixer drum', 'caught_in', 'Machinery', ARRAY['Concrete'], ARRAY['Concrete Mixing'], 5, 2, 'medium', '[{"type": "engineering", "control": "Guards on rotating parts", "required": true}, {"type": "administrative", "control": "Lockout during cleaning", "required": true}, {"type": "administrative", "control": "No loose clothing", "required": true}]', ARRAY['Safety Glasses', 'Safety Boots'], '[]'),

(NULL, 'HAZ-CAUGHT-006', 'Caught in power auger', 'Risk of entanglement in rotating auger or drill', 'caught_in', 'Machinery', ARRAY['Excavation', 'Foundation'], ARRAY['Drilling', 'Auger Work'], 5, 2, 'medium', '[{"type": "engineering", "control": "Guards on rotating components", "required": true}, {"type": "administrative", "control": "Keep hands/clothing clear", "required": true}]', ARRAY['Safety Glasses', 'Safety Boots', 'Safety Gloves'], '[]'),

(NULL, 'HAZ-CAUGHT-007', 'Caught between wall and equipment', 'Risk of being caught between walls and moving equipment', 'caught_in', 'Pinch Points', ARRAY['General Construction', 'Excavation'], ARRAY['Tight Space Work'], 5, 2, 'medium', '[{"type": "administrative", "control": "Maintain safe clearances", "required": true}, {"type": "administrative", "control": "Spotter in tight areas", "required": true}]', ARRAY['Hi-Vis Vest', 'Hard Hat'], '[]'),

(NULL, 'HAZ-CAUGHT-008', 'Caught in compactor/roller', 'Risk of being caught by compaction equipment', 'caught_in', 'Machinery', ARRAY['Excavation', 'Paving'], ARRAY['Compaction'], 5, 2, 'medium', '[{"type": "engineering", "control": "Guards and emergency stops", "required": true}, {"type": "administrative", "control": "Keep clear during operation", "required": true}]', ARRAY['Hi-Vis Vest', 'Safety Boots', 'Hard Hat'], '[]'),

(NULL, 'HAZ-CAUGHT-009', 'Spoil pile collapse', 'Risk of being buried by collapse of excavated spoil piles', 'caught_in', 'Cave-In', ARRAY['Excavation'], ARRAY['Excavation', 'Stockpiling'], 4, 2, 'medium', '[{"type": "administrative", "control": "Keep spoil 1m from excavation edge", "required": true}, {"type": "administrative", "control": "Maintain safe angle of repose", "required": true}]', ARRAY['Hard Hat', 'Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "233", "title": "Excavations"}]'),

(NULL, 'HAZ-CAUGHT-010', 'Wall/structure collapse during demo', 'Risk of being caught in collapsing walls during demolition', 'caught_in', 'Structural', ARRAY['Demolition'], ARRAY['Structural Demolition'], 5, 2, 'medium', '[{"type": "engineering", "control": "Engineering assessment required", "required": true}, {"type": "administrative", "control": "Controlled demolition sequence", "required": true}, {"type": "administrative", "control": "Exclusion zones", "required": true}]', ARRAY['Hard Hat', 'Safety Boots', 'Hi-Vis Vest'], '[{"regulation": "O. Reg. 213/91", "section": "202", "title": "Demolition"}]'),

-- ELECTRICAL HAZARDS (Extended)
(NULL, 'HAZ-ELEC-006', 'Contact with buried electrical', 'Risk of contacting buried electrical cables during excavation', 'electrical', 'Underground', ARRAY['Excavation', 'Plumbing', 'Landscaping'], ARRAY['Excavation', 'Digging'], 5, 2, 'medium', '[{"type": "administrative", "control": "Utility locates required", "required": true}, {"type": "administrative", "control": "Hand dig within tolerance zone", "required": true}]', ARRAY['Safety Boots', 'Safety Gloves'], '[{"regulation": "O. Reg. 213/91", "section": "228", "title": "Underground Services"}]'),

(NULL, 'HAZ-ELEC-007', 'Electrical shock from power tools', 'Risk of shock from damaged or defective power tools', 'electrical', 'Equipment', ARRAY['General Construction', 'All Trades'], ARRAY['Power Tool Use'], 4, 3, 'medium', '[{"type": "engineering", "control": "Use GFCI protection", "required": true}, {"type": "administrative", "control": "Inspect tools before use", "required": true}, {"type": "engineering", "control": "Use double-insulated tools", "required": false}]', ARRAY['Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "195", "title": "Electrical Equipment"}]'),

(NULL, 'HAZ-ELEC-008', 'Electrical shock from temporary wiring', 'Risk of shock from temporary site electrical installations', 'electrical', 'Wiring', ARRAY['General Construction', 'Electrical'], ARRAY['Temporary Power'], 4, 3, 'medium', '[{"type": "engineering", "control": "GFCI protection on all circuits", "required": true}, {"type": "administrative", "control": "Regular inspection of temp wiring", "required": true}]', ARRAY['Safety Boots'], '[{"regulation": "O. Reg. 213/91", "section": "193", "title": "Temporary Power"}]'),

(NULL, 'HAZ-ELEC-009', 'Static electricity discharge', 'Risk of static discharge igniting flammable materials', 'electrical', 'Static', ARRAY['Painting', 'General Construction'], ARRAY['Fuel Transfer', 'Spray Painting'], 4, 2, 'medium', '[{"type": "engineering", "control": "Ground all containers", "required": true}, {"type": "engineering", "control": "Use bonding cables", "required": true}]', ARRAY['Safety Boots'], '[]'),

(NULL, 'HAZ-ELEC-010', 'Lightning strike', 'Risk of lightning strike during outdoor work', 'electrical', 'Lightning', ARRAY['Crane/Rigging', 'Structural Steel', 'Roofing'], ARRAY['Outdoor Work', 'High Work'], 5, 2, 'medium', '[{"type": "administrative", "control": "Monitor weather conditions", "required": true}, {"type": "administrative", "control": "Suspend work during storms", "required": true}]', ARRAY[], '[]')

ON CONFLICT DO NOTHING;
