-- ============================================================================
-- EXTENDED HAZARD LIBRARY - PART 2
-- ============================================================================
-- Chemical, Ergonomic, Environmental, and Other Hazards
-- ============================================================================

-- CHEMICAL HAZARDS (Extended)
INSERT INTO hazard_library (company_id, hazard_code, name, description, category, subcategory, applicable_trades, applicable_activities, default_severity, default_likelihood, default_risk_level, recommended_controls, required_ppe, regulatory_references) VALUES

(NULL, 'HAZ-CHEM-007', 'Wood dust exposure', 'Risk of respiratory issues from wood dust during cutting/sanding', 'chemical', 'Dust', ARRAY['Carpentry', 'Flooring'], ARRAY['Cutting', 'Sanding', 'Milling'], 3, 4, 'medium', '[{"type": "engineering", "control": "Dust collection system", "required": true}, {"type": "engineering", "control": "Local exhaust ventilation", "required": false}, {"type": "ppe", "control": "N95 respirator minimum", "required": true}]', ARRAY['N95 Respirator', 'Safety Glasses'], '[{"regulation": "O. Reg. 490/09", "section": "3", "title": "Dust"}]'),

(NULL, 'HAZ-CHEM-008', 'Drywall dust exposure', 'Risk from gypsum dust during drywall cutting and sanding', 'chemical', 'Dust', ARRAY['Drywall', 'Painting'], ARRAY['Drywall Sanding', 'Cutting'], 3, 4, 'medium', '[{"type": "engineering", "control": "Dustless sanding system", "required": false}, {"type": "engineering", "control": "General ventilation", "required": true}, {"type": "ppe", "control": "Dust mask required", "required": true}]', ARRAY['N95 Respirator', 'Safety Glasses'], '[]'),

(NULL, 'HAZ-CHEM-009', 'Spray paint exposure', 'Risk from inhaling paint overspray and solvent vapours', 'chemical', 'Vapours', ARRAY['Painting', 'Finishing'], ARRAY['Spray Painting'], 4, 3, 'medium', '[{"type": "engineering", "control": "Spray booth with ventilation", "required": true}, {"type": "substitution", "control": "Use HVLP spray equipment", "required": false}, {"type": "ppe", "control": "Organic vapour respirator", "required": true}]', ARRAY['Half-Face Respirator', 'Safety Glasses', 'Coveralls'], '[]'),

(NULL, 'HAZ-CHEM-010', 'Epoxy/resin exposure', 'Risk of sensitization and dermatitis from epoxy resins', 'chemical', 'Sensitizers', ARRAY['Flooring', 'Waterproofing', 'Structural'], ARRAY['Epoxy Application', 'Coating'], 3, 4, 'medium', '[{"type": "engineering", "control": "Ventilation in enclosed areas", "required": true}, {"type": "ppe", "control": "Chemical-resistant gloves", "required": true}, {"type": "ppe", "control": "Organic vapour respirator", "required": true}]', ARRAY['Chemical-Resistant Gloves - Nitrile', 'Half-Face Respirator', 'Safety Glasses'], '[]'),

(NULL, 'HAZ-CHEM-011', 'Diesel exhaust exposure', 'Risk from diesel particulate matter and exhaust gases', 'chemical', 'Fumes', ARRAY['General Construction', 'Excavation'], ARRAY['Equipment Operation', 'Enclosed Spaces'], 3, 4, 'medium', '[{"type": "engineering", "control": "Exhaust extraction in enclosed areas", "required": true}, {"type": "administrative", "control": "Minimize idling time", "required": true}, {"type": "ppe", "control": "P100 respirator in enclosed spaces", "required": true}]', ARRAY['Half-Face Respirator'], '[]'),

(NULL, 'HAZ-CHEM-012', 'Carbon monoxide exposure', 'Risk of CO poisoning from fuel-burning equipment indoors', 'chemical', 'Gases', ARRAY['General Construction', 'All Trades'], ARRAY['Indoor Equipment Use', 'Heating'], 5, 3, 'high', '[{"type": "engineering", "control": "CO monitors in enclosed areas", "required": true}, {"type": "engineering", "control": "Adequate ventilation", "required": true}, {"type": "administrative", "control": "No gas equipment indoors without ventilation", "required": true}]', ARRAY['Half-Face Respirator'], '[]'),

(NULL, 'HAZ-CHEM-013', 'Isocyanate exposure', 'Risk from spray foam insulation and polyurethane coatings', 'chemical', 'Sensitizers', ARRAY['Insulation', 'Roofing', 'Flooring'], ARRAY['Spray Foam Application', 'Polyurethane Coating'], 4, 3, 'medium', '[{"type": "engineering", "control": "Supplied air in spray area", "required": true}, {"type": "administrative", "control": "Medical surveillance", "required": true}, {"type": "ppe", "control": "Full-face supplied air respirator", "required": true}]', ARRAY['PAPR', 'Tyvek Suit', 'Chemical-Resistant Gloves - Nitrile'], '[]'),

(NULL, 'HAZ-CHEM-014', 'Muriatic acid exposure', 'Risk of burns and fumes from muriatic/hydrochloric acid', 'chemical', 'Corrosive', ARRAY['Masonry', 'Concrete'], ARRAY['Cleaning', 'Etching'], 4, 3, 'medium', '[{"type": "engineering", "control": "Outdoor use only or ventilated area", "required": true}, {"type": "ppe", "control": "Acid-resistant gloves and apron", "required": true}, {"type": "ppe", "control": "Face shield and respirator", "required": true}]', ARRAY['Chemical-Resistant Gloves - Neoprene', 'Face Shield', 'Half-Face Respirator'], '[]'),

(NULL, 'HAZ-CHEM-015', 'Adhesive vapour exposure', 'Risk from contact adhesives and flooring glues', 'chemical', 'Vapours', ARRAY['Flooring', 'Carpentry', 'Roofing'], ARRAY['Adhesive Application'], 3, 4, 'medium', '[{"type": "engineering", "control": "Ventilation during application", "required": true}, {"type": "substitution", "control": "Use low-VOC adhesives", "required": false}, {"type": "ppe", "control": "Organic vapour respirator", "required": true}]', ARRAY['Half-Face Respirator', 'Safety Gloves'], '[]'),

(NULL, 'HAZ-CHEM-016', 'Fibreglass/mineral wool exposure', 'Risk of skin and respiratory irritation from insulation fibres', 'chemical', 'Fibres', ARRAY['Insulation', 'HVAC', 'Drywall'], ARRAY['Insulation Installation'], 2, 4, 'medium', '[{"type": "ppe", "control": "Long sleeves and pants", "required": true}, {"type": "ppe", "control": "N95 respirator", "required": true}, {"type": "ppe", "control": "Safety glasses", "required": true}]', ARRAY['N95 Respirator', 'Safety Glasses', 'Safety Gloves'], '[]'),

(NULL, 'HAZ-CHEM-017', 'Pressure-treated wood exposure', 'Risk from chemicals in pressure-treated lumber', 'chemical', 'Preservatives', ARRAY['Carpentry', 'Landscaping'], ARRAY['Cutting', 'Handling PT Lumber'], 2, 4, 'low', '[{"type": "administrative", "control": "Do not burn PT wood", "required": true}, {"type": "ppe", "control": "Gloves when handling", "required": true}, {"type": "ppe", "control": "Dust mask when cutting", "required": true}]', ARRAY['N95 Respirator', 'Safety Gloves'], '[]'),

(NULL, 'HAZ-CHEM-018', 'Fuel/gasoline exposure', 'Risk from skin contact and vapour inhalation during refueling', 'chemical', 'Flammable', ARRAY['General Construction', 'All Trades'], ARRAY['Refueling Equipment'], 3, 4, 'medium', '[{"type": "administrative", "control": "No smoking during refueling", "required": true}, {"type": "engineering", "control": "Use proper fuel containers", "required": true}, {"type": "ppe", "control": "Chemical-resistant gloves", "required": true}]', ARRAY['Safety Gloves'], '[]'),

(NULL, 'HAZ-CHEM-019', 'Hydraulic fluid exposure', 'Risk from contact with hydraulic fluid leaks or failures', 'chemical', 'Oils', ARRAY['General Construction', 'Excavation'], ARRAY['Equipment Maintenance', 'Operation'], 3, 3, 'medium', '[{"type": "administrative", "control": "Regular equipment inspection", "required": true}, {"type": "ppe", "control": "Chemical-resistant gloves", "required": true}, {"type": "ppe", "control": "Face shield for pressurized work", "required": true}]', ARRAY['Safety Gloves', 'Face Shield', 'Safety Glasses'], '[]'),

(NULL, 'HAZ-CHEM-020', 'Mould exposure', 'Risk of respiratory illness from mould during renovation/demolition', 'biological', 'Mould', ARRAY['Demolition', 'Renovation', 'Remediation'], ARRAY['Water Damage Work', 'Renovation'], 3, 4, 'medium', '[{"type": "engineering", "control": "Containment and HEPA filtration", "required": true}, {"type": "administrative", "control": "Mould assessment before work", "required": true}, {"type": "ppe", "control": "N95 minimum, P100 for heavy growth", "required": true}]', ARRAY['N95 Respirator', 'Tyvek Suit', 'Safety Gloves'], '[]'),

-- ERGONOMIC HAZARDS (Extended)
(NULL, 'HAZ-ERGO-006', 'Whole-body vibration', 'Risk from operating vibrating equipment (dozers, loaders)', 'ergonomic', 'Vibration', ARRAY['Excavation', 'Paving', 'General Construction'], ARRAY['Heavy Equipment Operation'], 3, 4, 'medium', '[{"type": "engineering", "control": "Use equipment with vibration dampening", "required": false}, {"type": "administrative", "control": "Limit exposure time", "required": true}, {"type": "administrative", "control": "Maintain equipment suspension", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ERGO-007', 'Prolonged standing', 'Risk of leg/back fatigue from extended periods of standing', 'ergonomic', 'Posture', ARRAY['General Construction', 'Concrete', 'Painting'], ARRAY['Finishing Work', 'Painting'], 2, 4, 'low', '[{"type": "engineering", "control": "Anti-fatigue mats where feasible", "required": false}, {"type": "administrative", "control": "Scheduled breaks", "required": true}]', ARRAY['Safety Boots'], '[]'),

(NULL, 'HAZ-ERGO-008', 'Forceful gripping', 'Risk of hand/wrist injury from prolonged tool gripping', 'ergonomic', 'Repetitive Motion', ARRAY['Carpentry', 'Drywall', 'Painting'], ARRAY['Hand Tool Use', 'Power Tool Use'], 2, 4, 'medium', '[{"type": "substitution", "control": "Use ergonomic grip tools", "required": false}, {"type": "administrative", "control": "Job rotation", "required": true}, {"type": "administrative", "control": "Regular breaks", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ERGO-009', 'Carrying heavy loads on stairs', 'Risk of injury from carrying materials up/down stairs', 'ergonomic', 'Manual Handling', ARRAY['General Construction', 'All Trades'], ARRAY['Material Handling', 'Stair Access'], 4, 3, 'medium', '[{"type": "engineering", "control": "Use material hoists where possible", "required": false}, {"type": "administrative", "control": "Reduce load size", "required": true}, {"type": "administrative", "control": "Team lifting for heavy items", "required": true}]', ARRAY['Safety Boots', 'Safety Gloves'], '[]'),

(NULL, 'HAZ-ERGO-010', 'Reaching above shoulder height', 'Risk of shoulder injury from extended overhead reaching', 'ergonomic', 'Posture', ARRAY['Electrical', 'Plumbing', 'HVAC', 'Drywall'], ARRAY['Overhead Installation', 'Ceiling Work'], 3, 4, 'medium', '[{"type": "engineering", "control": "Use elevated work platforms", "required": true}, {"type": "administrative", "control": "Limit overhead work duration", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ERGO-011', 'Twisting while lifting', 'Risk of back injury from twisting during manual handling', 'ergonomic', 'Manual Handling', ARRAY['General Construction', 'All Trades'], ARRAY['Material Handling'], 4, 4, 'high', '[{"type": "administrative", "control": "Move feet, don''t twist", "required": true}, {"type": "administrative", "control": "Manual handling training", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ERGO-012', 'Working in cramped spaces', 'Risk of injury from working in tight or restricted positions', 'ergonomic', 'Posture', ARRAY['Plumbing', 'Electrical', 'HVAC'], ARRAY['Mechanical Room Work', 'Crawl Space Work'], 3, 3, 'medium', '[{"type": "administrative", "control": "Job rotation", "required": true}, {"type": "administrative", "control": "Frequent breaks", "required": true}]', ARRAY[], '[]'),

-- ENVIRONMENTAL HAZARDS (Extended)  
(NULL, 'HAZ-ENV-006', 'Poor air quality (smog/smoke)', 'Risk from working outdoors during poor air quality conditions', 'environmental', 'Air Quality', ARRAY['General Construction', 'Roofing', 'All Trades'], ARRAY['Outdoor Work'], 3, 2, 'low', '[{"type": "administrative", "control": "Monitor air quality index", "required": true}, {"type": "administrative", "control": "Reduce strenuous activity during poor AQ", "required": true}]', ARRAY['N95 Respirator'], '[]'),

(NULL, 'HAZ-ENV-007', 'Insect stings/bites', 'Risk of stings from wasps, bees, or mosquito-borne illness', 'environmental', 'Biological', ARRAY['General Construction', 'Landscaping', 'Excavation'], ARRAY['Outdoor Work'], 3, 3, 'medium', '[{"type": "administrative", "control": "Inspect work area for nests", "required": true}, {"type": "administrative", "control": "First aid kit with antihistamine", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ENV-008', 'Wildlife encounters', 'Risk of encounters with wildlife (snakes, bears, etc.)', 'environmental', 'Biological', ARRAY['General Construction', 'Landscaping', 'Civil'], ARRAY['Rural Site Work'], 3, 2, 'low', '[{"type": "administrative", "control": "Wildlife awareness training", "required": true}, {"type": "administrative", "control": "Secure food and waste", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ENV-009', 'Flooding/water hazards', 'Risk of drowning or injury from water on construction sites', 'environmental', 'Water', ARRAY['Excavation', 'Civil', 'General Construction'], ARRAY['Excavation', 'Near Water'], 5, 2, 'medium', '[{"type": "engineering", "control": "Dewatering systems", "required": true}, {"type": "administrative", "control": "Life jackets near water", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-ENV-010', 'Noise from traffic', 'Risk of hearing damage and communication difficulties from traffic noise', 'environmental', 'Noise', ARRAY['Civil', 'Paving', 'General Construction'], ARRAY['Roadside Work'], 3, 3, 'medium', '[{"type": "engineering", "control": "Traffic barriers", "required": false}, {"type": "ppe", "control": "Hearing protection", "required": true}]', ARRAY['Ear Plugs - Disposable Foam'], '[]'),

(NULL, 'HAZ-ENV-011', 'Terrain hazards', 'Risk of injury from uneven, steep, or unstable terrain', 'environmental', 'Terrain', ARRAY['General Construction', 'Excavation', 'Civil'], ARRAY['Site Work', 'Grading'], 3, 3, 'medium', '[{"type": "administrative", "control": "Assess terrain before work", "required": true}, {"type": "ppe", "control": "Appropriate footwear", "required": true}]', ARRAY['Safety Boots'], '[]'),

-- FIRE/EXPLOSION HAZARDS (Extended)
(NULL, 'HAZ-FIRE-004', 'Torch cutting/burning', 'Risk of fire from oxy-acetylene cutting operations', 'fire_explosion', 'Hot Work', ARRAY['Structural Steel', 'Demolition', 'Plumbing'], ARRAY['Cutting', 'Heating'], 4, 3, 'medium', '[{"type": "administrative", "control": "Hot work permit required", "required": true}, {"type": "engineering", "control": "Fire extinguisher within 20 feet", "required": true}, {"type": "administrative", "control": "Fire watch required", "required": true}]', ARRAY['Welding Hood', 'Welding Gloves', 'FR Coveralls'], '[{"regulation": "O. Reg. 213/91", "section": "52", "title": "Fire Prevention"}]'),

(NULL, 'HAZ-FIRE-005', 'Propane cylinder hazards', 'Risk of fire/explosion from propane cylinders', 'fire_explosion', 'Compressed Gas', ARRAY['Roofing', 'Plumbing', 'General Construction'], ARRAY['Torch Work', 'Heating'], 4, 2, 'medium', '[{"type": "engineering", "control": "Proper cylinder storage", "required": true}, {"type": "administrative", "control": "Inspect hoses and regulators", "required": true}, {"type": "administrative", "control": "Keep away from heat sources", "required": true}]', ARRAY['Safety Glasses', 'Safety Gloves'], '[]'),

(NULL, 'HAZ-FIRE-006', 'Combustible dust explosion', 'Risk of dust explosion from accumulated combustible dust', 'fire_explosion', 'Dust', ARRAY['Carpentry', 'Flooring'], ARRAY['Sanding', 'Cutting'], 5, 2, 'medium', '[{"type": "engineering", "control": "Dust collection systems", "required": true}, {"type": "administrative", "control": "Regular housekeeping", "required": true}, {"type": "administrative", "control": "No ignition sources near dust", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-FIRE-007', 'Oxygen-enriched atmosphere', 'Risk of accelerated fire from oxygen-enriched areas', 'fire_explosion', 'Compressed Gas', ARRAY['Welding', 'HVAC'], ARRAY['Oxy-Fuel Cutting', 'Medical Gas Work'], 5, 2, 'medium', '[{"type": "engineering", "control": "Proper ventilation", "required": true}, {"type": "administrative", "control": "No oil/grease on oxygen equipment", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-FIRE-008', 'Hot roofing materials', 'Risk of burns from hot asphalt, tar, or bitumen', 'fire_explosion', 'Hot Materials', ARRAY['Roofing', 'Waterproofing'], ARRAY['Hot Applied Roofing'], 4, 3, 'medium', '[{"type": "engineering", "control": "Fire extinguisher at kettle", "required": true}, {"type": "ppe", "control": "Heat-resistant gloves", "required": true}, {"type": "administrative", "control": "Hot kettle safety training", "required": true}]', ARRAY['Leather Work Gloves', 'Long Sleeves', 'Safety Boots', 'Face Shield'], '[]'),

-- RADIATION HAZARDS
(NULL, 'HAZ-RAD-001', 'Welding arc radiation', 'Risk of eye damage and skin burns from welding arc', 'radiation', 'Arc Radiation', ARRAY['Structural Steel', 'Plumbing', 'HVAC'], ARRAY['Welding', 'Arc Cutting'], 4, 4, 'high', '[{"type": "engineering", "control": "Welding screens/curtains", "required": true}, {"type": "ppe", "control": "Proper shade welding lens", "required": true}, {"type": "ppe", "control": "Welding jacket and gloves", "required": true}]', ARRAY['Welding Hood - Auto-Darkening', 'Welding Jacket', 'Welding Gloves'], '[{"regulation": "O. Reg. 213/91", "section": "126", "title": "Welding"}]'),

(NULL, 'HAZ-RAD-002', 'Laser exposure', 'Risk of eye damage from laser levels and measuring equipment', 'radiation', 'Laser', ARRAY['General Construction', 'Surveying'], ARRAY['Layout', 'Surveying'], 4, 2, 'medium', '[{"type": "engineering", "control": "Use lowest power necessary", "required": true}, {"type": "administrative", "control": "Never look directly into beam", "required": true}, {"type": "ppe", "control": "Laser safety glasses for Class 3/4", "required": true}]', ARRAY['Safety Glasses'], '[]'),

-- PSYCHOSOCIAL HAZARDS
(NULL, 'HAZ-PSYCH-001', 'Work-related stress', 'Risk of stress from deadlines, workload, or conflict', 'psychosocial', 'Stress', ARRAY['General Construction', 'All Trades', 'Supervision'], ARRAY['All Activities'], 3, 3, 'medium', '[{"type": "administrative", "control": "Reasonable work schedules", "required": true}, {"type": "administrative", "control": "Open communication", "required": true}]', ARRAY[], '[]'),

(NULL, 'HAZ-PSYCH-002', 'Fatigue from extended hours', 'Risk of fatigue-related incidents from long work hours', 'psychosocial', 'Fatigue', ARRAY['General Construction', 'All Trades'], ARRAY['Extended Shifts'], 4, 3, 'medium', '[{"type": "administrative", "control": "Limit shift length", "required": true}, {"type": "administrative", "control": "Adequate rest breaks", "required": true}, {"type": "administrative", "control": "No critical work at shift end", "required": false}]', ARRAY[], '[]'),

(NULL, 'HAZ-PSYCH-003', 'Isolation/working alone', 'Risk of delayed emergency response when working alone', 'psychosocial', 'Isolation', ARRAY['General Construction', 'All Trades'], ARRAY['Remote Work', 'After Hours'], 4, 2, 'medium', '[{"type": "administrative", "control": "Check-in procedures", "required": true}, {"type": "engineering", "control": "Lone worker devices", "required": false}]', ARRAY[], '[]'),

(NULL, 'HAZ-PSYCH-004', 'Workplace violence', 'Risk of violence or harassment on construction sites', 'psychosocial', 'Violence', ARRAY['General Construction', 'All Trades'], ARRAY['All Activities'], 4, 2, 'medium', '[{"type": "administrative", "control": "Violence prevention policy", "required": true}, {"type": "administrative", "control": "Reporting procedures", "required": true}]', ARRAY[], '[{"regulation": "OHSA", "section": "32.0.1", "title": "Workplace Violence"}]')

ON CONFLICT DO NOTHING;
