/**
 * Legal Posting Checklist
 * COR Element 13: Regulatory Awareness
 * 
 * Verify required legal postings are displayed.
 */

import type { FormConfig } from '../../import-forms';

export const legalPostingChecklist: FormConfig = {
  code: 'legal_posting_checklist',
  name: 'Legal Posting Checklist',
  description: 'Verify all required safety and employment postings are displayed in the workplace.',
  cor_element: 13,
  frequency: 'quarterly',
  estimated_time_minutes: 15,
  icon: 'FileText',
  color: '#0EA5E9',
  is_mandatory: true,

  sections: [
    {
      title: 'Inspection Details',
      order_index: 0,
      fields: [
        {
          code: 'inspection_date',
          label: 'Inspection Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'inspector',
          label: 'Inspector',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Location/Jobsite',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'posting_location',
          label: 'Posting Board Location',
          field_type: 'text',
          placeholder: 'e.g., Main entrance, Break room',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Required Safety Postings',
      order_index: 1,
      fields: [
        {
          code: 'ohs_act',
          label: 'OH&S Act/Regulation Summary',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'ohs_act_condition',
          label: 'Condition',
          field_type: 'dropdown',
          options: [
            { value: 'good', label: 'Good' },
            { value: 'faded', label: 'Faded/Worn' },
            { value: 'outdated', label: 'Outdated' },
          ],
          conditional_logic: {
            field_code: 'ohs_act',
            operator: 'equals',
            value: 'Posted',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'safety_policy',
          label: 'Company Safety Policy',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'jhsc_names',
          label: 'JHSC/Safety Rep Names',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'emergency_procedures',
          label: 'Emergency Procedures',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'emergency_contacts',
          label: 'Emergency Contact Numbers',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'evacuation_plan',
          label: 'Evacuation Plan/Map',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'first_aid_location',
          label: 'First Aid Station Location',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
        {
          code: 'first_aiders',
          label: 'First Aid Attendant Names',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 8,
          width: 'half',
        },
        {
          code: 'whmis_info',
          label: 'WHMIS Information',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          order_index: 9,
          width: 'half',
        },
      ],
    },
    {
      title: 'Employment/Labor Postings',
      order_index: 2,
      fields: [
        {
          code: 'employment_standards',
          label: 'Employment Standards Poster',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'workers_comp_poster',
          label: 'Workers Compensation Poster',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'human_rights',
          label: 'Human Rights Poster',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'harassment_policy',
          label: 'Harassment/Violence Policy',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'right_to_refuse',
          label: 'Right to Refuse Unsafe Work',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Other Required Postings',
      order_index: 3,
      fields: [
        {
          code: 'no_smoking',
          label: 'No Smoking Signs',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          order_index: 0,
          width: 'half',
        },
        {
          code: 'fire_safety',
          label: 'Fire Safety Information',
          field_type: 'radio',
          options: ['Posted', 'Not Posted'],
          order_index: 1,
          width: 'half',
        },
        {
          code: 'ppe_requirements',
          label: 'PPE Requirements Signs',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'hazard_warnings',
          label: 'Hazard Warning Signs (as applicable)',
          field_type: 'radio',
          options: ['Posted', 'Not Posted', 'N/A'],
          order_index: 3,
          width: 'half',
        },
        {
          code: 'other_postings',
          label: 'Other Site-Specific Postings',
          field_type: 'textarea',
          placeholder: 'List any other required postings and their status...',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Deficiencies',
      order_index: 4,
      fields: [
        {
          code: 'deficiencies_found',
          label: 'Were any deficiencies found?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'deficiency_list',
          label: 'List Deficiencies',
          field_type: 'textarea',
          placeholder: 'List all missing or deficient postings...',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'corrective_actions',
          label: 'Corrective Actions',
          field_type: 'textarea',
          placeholder: 'What actions will be taken to address deficiencies?',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'target_completion',
          label: 'Target Completion Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'next_inspection_date',
          label: 'Next Inspection Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'inspector_signature',
          label: 'Inspector Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
