/**
 * Regulatory Compliance Checklist
 * COR Element 13: Regulatory Awareness
 * 
 * Verify compliance with applicable safety regulations.
 */

import type { FormConfig } from '../../import-forms';

export const regulatoryComplianceChecklist: FormConfig = {
  code: 'regulatory_compliance_checklist',
  name: 'Regulatory Compliance Checklist',
  description: 'Periodic review of compliance with applicable occupational health and safety regulations.',
  cor_element: 13,
  frequency: 'quarterly',
  estimated_time_minutes: 45,
  icon: 'Scale',
  color: '#DC2626',
  is_mandatory: true,

  sections: [
    {
      title: 'Review Information',
      order_index: 0,
      fields: [
        {
          code: 'review_date',
          label: 'Review Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'reviewer',
          label: 'Reviewed By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Location/Jobsite',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'review_type',
          label: 'Review Type',
          field_type: 'dropdown',
          options: [
            { value: 'scheduled', label: 'Scheduled Review' },
            { value: 'regulatory_change', label: 'Response to Regulatory Change' },
            { value: 'incident_related', label: 'Incident-Related Review' },
            { value: 'pre_project', label: 'Pre-Project Review' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'General Requirements',
      order_index: 1,
      fields: [
        {
          code: 'safety_policy_posted',
          label: 'Safety Policy Posted',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'jhsc_established',
          label: 'JHSC/Safety Rep Established',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jhsc_meetings',
          label: 'JHSC Meetings Held as Required',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'worker_training',
          label: 'Workers Trained on Hazards',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'supervisor_competency',
          label: 'Supervisor Competency Training',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'whmis_compliance',
          label: 'WHMIS/GHS Compliance',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'first_aid_compliance',
          label: 'First Aid Requirements Met',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'emergency_procedures',
          label: 'Emergency Procedures Established',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
      ],
    },
    {
      title: 'Workplace-Specific Requirements',
      description: 'Check applicable requirements',
      order_index: 2,
      fields: [
        {
          code: 'fall_protection',
          label: 'Fall Protection (if heights >3m)',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 0,
          width: 'half',
        },
        {
          code: 'confined_space',
          label: 'Confined Space Entry',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 1,
          width: 'half',
        },
        {
          code: 'lockout_tagout',
          label: 'Lockout/Tagout Program',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'electrical_safety',
          label: 'Electrical Safety',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 3,
          width: 'half',
        },
        {
          code: 'machine_guarding',
          label: 'Machine Guarding',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 4,
          width: 'half',
        },
        {
          code: 'noise_hearing',
          label: 'Noise/Hearing Conservation',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 5,
          width: 'half',
        },
        {
          code: 'respiratory_protection',
          label: 'Respiratory Protection',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 6,
          width: 'half',
        },
        {
          code: 'hazardous_materials',
          label: 'Hazardous Materials Handling',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 7,
          width: 'half',
        },
        {
          code: 'excavation_trenching',
          label: 'Excavation/Trenching',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 8,
          width: 'half',
        },
        {
          code: 'scaffolding',
          label: 'Scaffolding',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 9,
          width: 'half',
        },
        {
          code: 'mobile_equipment',
          label: 'Mobile Equipment/Vehicles',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 10,
          width: 'half',
        },
        {
          code: 'lifting_hoisting',
          label: 'Lifting/Hoisting',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          order_index: 11,
          width: 'half',
        },
      ],
    },
    {
      title: 'Documentation & Records',
      order_index: 3,
      fields: [
        {
          code: 'training_records',
          label: 'Training Records Maintained',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'inspection_records',
          label: 'Inspection Records Maintained',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'incident_records',
          label: 'Incident Records Maintained',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'equipment_records',
          label: 'Equipment Maintenance Records',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'sds_available',
          label: 'SDS Sheets Available',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'N/A'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'certifications_current',
          label: 'Required Certifications Current',
          field_type: 'radio',
          options: ['Compliant', 'Non-Compliant', 'Partial'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Non-Compliance Items',
      description: 'Document any items found non-compliant',
      order_index: 4,
      is_repeatable: true,
      fields: [
        {
          code: 'nc_item',
          label: 'Non-Compliant Item',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'nc_regulation',
          label: 'Applicable Regulation/Standard',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'nc_description',
          label: 'Description of Non-Compliance',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'nc_risk_level',
          label: 'Risk Level',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Immediate action required' },
            { value: 'high', label: 'High - Action within 24 hours' },
            { value: 'medium', label: 'Medium - Action within 7 days' },
            { value: 'low', label: 'Low - Action within 30 days' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'nc_corrective_action',
          label: 'Corrective Action Required',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'nc_responsible',
          label: 'Responsible Person',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'nc_due_date',
          label: 'Due Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
      ],
    },
    {
      title: 'Summary',
      order_index: 5,
      fields: [
        {
          code: 'overall_compliance',
          label: 'Overall Compliance Status',
          field_type: 'dropdown',
          options: [
            { value: 'full', label: 'Full Compliance' },
            { value: 'substantial', label: 'Substantial Compliance (minor issues)' },
            { value: 'partial', label: 'Partial Compliance (significant issues)' },
            { value: 'non_compliant', label: 'Non-Compliant (major issues)' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'total_non_compliant',
          label: 'Total Non-Compliant Items',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'comments',
          label: 'Additional Comments',
          field_type: 'textarea',
          order_index: 2,
          width: 'full',
        },
        {
          code: 'next_review_date',
          label: 'Next Review Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 6,
      fields: [
        {
          code: 'reviewer_signature',
          label: 'Reviewer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Acknowledgment',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Address Regulatory Non-Compliance',
      priority: 'high',
      due_hours: 48,
    },
    sync_priority: 2,
    requires_approval: true,
  },
};
