/**
 * Regulatory Change Log
 * COR Element 13: Regulatory Awareness
 * 
 * Track regulatory changes and implementation.
 */

import type { FormConfig } from '../../import-forms';

export const regulatoryChangeLog: FormConfig = {
  code: 'regulatory_change_log',
  name: 'Regulatory Change Log',
  description: 'Track regulatory changes, assess impact, and document implementation of required changes.',
  cor_element: 13,
  frequency: 'as_needed',
  estimated_time_minutes: 20,
  icon: 'FileEdit',
  color: '#F59E0B',
  is_mandatory: true,

  sections: [
    {
      title: 'Change Information',
      order_index: 0,
      fields: [
        {
          code: 'log_date',
          label: 'Log Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'logged_by',
          label: 'Logged By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'regulation_name',
          label: 'Regulation/Standard Name',
          field_type: 'text',
          placeholder: 'e.g., Occupational Health and Safety Regulation',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'regulation_section',
          label: 'Section/Part Changed',
          field_type: 'text',
          placeholder: 'e.g., Part 11 - Fall Protection',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'effective_date',
          label: 'Effective Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'change_type',
          label: 'Type of Change',
          field_type: 'dropdown',
          options: [
            { value: 'new', label: 'New Regulation' },
            { value: 'amendment', label: 'Amendment to Existing' },
            { value: 'repeal', label: 'Repeal/Removal' },
            { value: 'interpretation', label: 'New Interpretation/Guidance' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Change Description',
      order_index: 1,
      fields: [
        {
          code: 'change_summary',
          label: 'Summary of Change',
          field_type: 'textarea',
          placeholder: 'Summarize what has changed...',
          validation_rules: { required: true, min_length: 50 },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'previous_requirement',
          label: 'Previous Requirement (if applicable)',
          field_type: 'textarea',
          placeholder: 'What was previously required?',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'new_requirement',
          label: 'New Requirement',
          field_type: 'textarea',
          placeholder: 'What is now required?',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'source_link',
          label: 'Source/Reference Link',
          field_type: 'text',
          placeholder: 'URL or document reference',
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Impact Assessment',
      order_index: 2,
      fields: [
        {
          code: 'applies_to_company',
          label: 'Does this change apply to our operations?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'impact_level',
          label: 'Impact Level',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Immediate action required' },
            { value: 'significant', label: 'Significant - Major changes needed' },
            { value: 'moderate', label: 'Moderate - Some changes needed' },
            { value: 'minor', label: 'Minor - Minimal changes needed' },
            { value: 'none', label: 'None - Already compliant' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'affected_areas',
          label: 'Affected Areas/Departments',
          field_type: 'textarea',
          placeholder: 'Which areas/departments are affected?',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'current_compliance',
          label: 'Current Compliance Status',
          field_type: 'dropdown',
          options: [
            { value: 'compliant', label: 'Already Compliant' },
            { value: 'partial', label: 'Partially Compliant' },
            { value: 'non_compliant', label: 'Not Yet Compliant' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'gap_analysis',
          label: 'Gap Analysis',
          field_type: 'textarea',
          placeholder: 'What gaps exist between current state and new requirements?',
          conditional_logic: {
            field_code: 'current_compliance',
            operator: 'not_equals',
            value: 'compliant',
          },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Implementation Plan',
      order_index: 3,
      fields: [
        {
          code: 'actions_required',
          label: 'Actions Required for Compliance',
          field_type: 'textarea',
          placeholder: 'List all actions needed to achieve compliance...',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'policy_changes',
          label: 'Policy/Procedure Changes Required',
          field_type: 'textarea',
          placeholder: 'What policies or procedures need to be updated?',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'training_required',
          label: 'Training Required',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'training_description',
          label: 'Training Description',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'training_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'equipment_changes',
          label: 'Equipment/PPE Changes Required',
          field_type: 'textarea',
          order_index: 4,
          width: 'full',
        },
        {
          code: 'estimated_cost',
          label: 'Estimated Implementation Cost',
          field_type: 'text',
          placeholder: '$0.00',
          order_index: 5,
          width: 'half',
        },
        {
          code: 'responsible_person',
          label: 'Person Responsible for Implementation',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'implementation_deadline',
          label: 'Implementation Deadline',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
      ],
    },
    {
      title: 'Communication',
      order_index: 4,
      fields: [
        {
          code: 'communication_plan',
          label: 'How will this change be communicated?',
          field_type: 'multiselect',
          options: [
            { value: 'safety_meeting', label: 'Safety Meeting' },
            { value: 'toolbox_talk', label: 'Toolbox Talk' },
            { value: 'email', label: 'Email' },
            { value: 'training', label: 'Training Session' },
            { value: 'posted_notice', label: 'Posted Notice' },
            { value: 'policy_update', label: 'Policy Update Distribution' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'communication_date',
          label: 'Target Communication Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
    {
      title: 'Implementation Status',
      order_index: 5,
      fields: [
        {
          code: 'implementation_status',
          label: 'Implementation Status',
          field_type: 'dropdown',
          options: [
            { value: 'not_started', label: 'Not Started' },
            { value: 'planning', label: 'Planning' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'completed', label: 'Completed' },
            { value: 'verified', label: 'Completed & Verified' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'completion_date',
          label: 'Actual Completion Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'implementation_status',
            operator: 'contains',
            value: 'completed',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'verification_notes',
          label: 'Verification Notes',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'implementation_status',
            operator: 'equals',
            value: 'verified',
          },
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 6,
      fields: [
        {
          code: 'logged_by_signature',
          label: 'Logged By Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Approval',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Implement Regulatory Change',
      priority: 'high',
      due_hours: 168,
    },
    sync_priority: 2,
    requires_approval: true,
  },
};
