/**
 * Competency Assessment Form
 * COR Element 8: Training & Communication
 * 
 * Assess worker competency for specific tasks.
 */

import type { FormConfig } from '../../import-forms';

export const competencyAssessment: FormConfig = {
  code: 'competency_assessment',
  name: 'Competency Assessment',
  description: 'Assess and document worker competency for specific tasks, equipment, or procedures.',
  cor_element: 8,
  frequency: 'as_needed',
  estimated_time_minutes: 20,
  icon: 'Award',
  color: '#10B981',
  is_mandatory: true,

  sections: [
    {
      title: 'Assessment Information',
      order_index: 0,
      fields: [
        {
          code: 'assessment_date',
          label: 'Assessment Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'assessor',
          label: 'Assessor',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'worker_assessed',
          label: 'Worker Being Assessed',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'assessment_type',
          label: 'Assessment Type',
          field_type: 'dropdown',
          options: [
            { value: 'initial', label: 'Initial Competency Assessment' },
            { value: 'refresher', label: 'Refresher Assessment' },
            { value: 'annual', label: 'Annual Assessment' },
            { value: 'post_training', label: 'Post-Training Assessment' },
            { value: 'return_to_work', label: 'Return to Work Assessment' },
            { value: 'promotion', label: 'Promotion/New Role Assessment' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'competency_area',
          label: 'Competency Area',
          field_type: 'dropdown',
          options: [
            { value: 'equipment_operation', label: 'Equipment Operation' },
            { value: 'task_procedure', label: 'Task/Procedure' },
            { value: 'emergency_response', label: 'Emergency Response' },
            { value: 'ppe_use', label: 'PPE Use' },
            { value: 'hazard_recognition', label: 'Hazard Recognition' },
            { value: 'first_aid', label: 'First Aid' },
            { value: 'supervision', label: 'Supervision Skills' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'specific_task',
          label: 'Specific Task/Equipment',
          field_type: 'text',
          placeholder: 'e.g., Forklift Operation, Confined Space Entry',
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Knowledge Assessment',
      description: 'Assess theoretical knowledge',
      order_index: 1,
      fields: [
        {
          code: 'knowledge_test_conducted',
          label: 'Was a knowledge test conducted?',
          field_type: 'radio',
          options: ['Yes - Written', 'Yes - Verbal', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'knowledge_score',
          label: 'Knowledge Test Score (%)',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          conditional_logic: {
            field_code: 'knowledge_test_conducted',
            operator: 'not_equals',
            value: 'No',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'passing_score',
          label: 'Passing Score (%)',
          field_type: 'number',
          default_value: '80',
          validation_rules: { min_value: 0, max_value: 100 },
          conditional_logic: {
            field_code: 'knowledge_test_conducted',
            operator: 'not_equals',
            value: 'No',
          },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'hazard_awareness',
          label: 'Hazard Awareness',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Identifies all hazards' },
            { value: 'developing', label: 'Developing - Identifies most hazards' },
            { value: 'not_competent', label: 'Not Competent - Misses key hazards' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'control_knowledge',
          label: 'Knowledge of Controls',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Understands all controls' },
            { value: 'developing', label: 'Developing - Understands most controls' },
            { value: 'not_competent', label: 'Not Competent - Lacks understanding' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'emergency_procedures',
          label: 'Emergency Procedure Knowledge',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Knows all procedures' },
            { value: 'developing', label: 'Developing - Knows basic procedures' },
            { value: 'not_competent', label: 'Not Competent - Lacks knowledge' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'regulatory_knowledge',
          label: 'Regulatory/Standards Knowledge',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Good understanding' },
            { value: 'developing', label: 'Developing - Basic understanding' },
            { value: 'not_competent', label: 'Not Competent - Lacks understanding' },
            { value: 'na', label: 'N/A' },
          ],
          order_index: 6,
          width: 'half',
        },
      ],
    },
    {
      title: 'Practical Skills Assessment',
      description: 'Assess hands-on ability',
      order_index: 2,
      fields: [
        {
          code: 'practical_test_conducted',
          label: 'Was a practical assessment conducted?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'pre_task_planning',
          label: 'Pre-Task Planning',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Plans work properly' },
            { value: 'developing', label: 'Developing - Needs guidance' },
            { value: 'not_competent', label: 'Not Competent - Does not plan' },
          ],
          conditional_logic: {
            field_code: 'practical_test_conducted',
            operator: 'equals',
            value: 'Yes',
          },
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'ppe_selection',
          label: 'PPE Selection & Use',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Selects/uses correctly' },
            { value: 'developing', label: 'Developing - Minor issues' },
            { value: 'not_competent', label: 'Not Competent - Major issues' },
          ],
          conditional_logic: {
            field_code: 'practical_test_conducted',
            operator: 'equals',
            value: 'Yes',
          },
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'equipment_operation',
          label: 'Equipment/Tool Operation',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Operates safely/correctly' },
            { value: 'developing', label: 'Developing - Needs supervision' },
            { value: 'not_competent', label: 'Not Competent - Unsafe operation' },
          ],
          conditional_logic: {
            field_code: 'practical_test_conducted',
            operator: 'equals',
            value: 'Yes',
          },
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'task_execution',
          label: 'Task Execution',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Performs safely/correctly' },
            { value: 'developing', label: 'Developing - Minor corrections needed' },
            { value: 'not_competent', label: 'Not Competent - Major corrections needed' },
          ],
          conditional_logic: {
            field_code: 'practical_test_conducted',
            operator: 'equals',
            value: 'Yes',
          },
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'cleanup_housekeeping',
          label: 'Cleanup/Housekeeping',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Maintains clean work area' },
            { value: 'developing', label: 'Developing - Needs reminders' },
            { value: 'not_competent', label: 'Not Competent - Poor housekeeping' },
          ],
          conditional_logic: {
            field_code: 'practical_test_conducted',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'practical_observations',
          label: 'Observations/Notes',
          field_type: 'textarea',
          placeholder: 'Note any specific observations from the practical assessment...',
          conditional_logic: {
            field_code: 'practical_test_conducted',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Overall Assessment',
      order_index: 3,
      fields: [
        {
          code: 'overall_result',
          label: 'Overall Competency Result',
          field_type: 'dropdown',
          options: [
            { value: 'competent', label: 'Competent - Can perform independently' },
            { value: 'competent_supervision', label: 'Competent with Supervision' },
            { value: 'not_yet_competent', label: 'Not Yet Competent - Requires training' },
            { value: 'not_competent', label: 'Not Competent - Cannot perform task' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'certification_issued',
          label: 'Competency Certification Issued?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'certification_expiry',
          label: 'Certification Expiry Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'certification_issued',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'restrictions',
          label: 'Any Restrictions/Limitations',
          field_type: 'textarea',
          placeholder: 'Note any restrictions on the worker\'s competency...',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'additional_training_needed',
          label: 'Additional Training Needed?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'training_requirements',
          label: 'Training Requirements',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'additional_training_needed',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'reassessment_date',
          label: 'Next Assessment Date',
          field_type: 'date',
          help_text: 'When should this worker be reassessed?',
          order_index: 6,
          width: 'half',
        },
        {
          code: 'comments',
          label: 'Additional Comments',
          field_type: 'textarea',
          order_index: 7,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 4,
      fields: [
        {
          code: 'assessor_signature',
          label: 'Assessor Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'worker_signature',
          label: 'Worker Signature',
          field_type: 'signature',
          help_text: 'I acknowledge the results of this assessment',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'supervisor_signature',
          label: 'Supervisor Signature',
          field_type: 'signature',
          order_index: 2,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
