/**
 * Library-Integrated Toolbox Talk Form Configuration
 * 
 * This form demonstrates:
 * - Task library integration with hazard auto-populate
 * - Equipment auto-listing from tasks
 * - Certification checking for assigned workers
 * - Multi-worker sign-off
 * 
 * Test Case: Test 4 from integration tests
 */

import { FormTemplate, FormSection, FormField } from '@/components/form-builder/types';

export const LIBRARY_TOOLBOX_TALK_TEMPLATE: Omit<FormTemplate, 'id' | 'company_id' | 'created_at' | 'updated_at' | 'created_by'> = {
  form_code: 'LIB-TT-001',
  name: 'Toolbox Talk (Library Integrated)',
  description: 'Pre-work safety briefing with automatic hazard and certification lookup',
  cor_element: 5,
  frequency: 'daily',
  estimated_time_minutes: 15,
  icon: 'users',
  color: '#8B5CF6',
  version: 1,
  is_active: true,
  is_mandatory: true,
};

export const LIBRARY_TOOLBOX_TALK_SECTIONS: Array<Omit<FormSection, 'id' | 'form_template_id' | 'created_at'>> = [
  {
    title: 'Meeting Details',
    description: 'Basic information about this toolbox talk',
    order_index: 0,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Task & Hazards',
    description: 'Work task for today and associated hazards',
    order_index: 1,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Equipment & Certifications',
    description: 'Required equipment and worker certifications',
    order_index: 2,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Safety Discussion',
    description: 'Topics discussed and worker questions',
    order_index: 3,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Attendance',
    description: 'Worker attendance and sign-off',
    order_index: 4,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
];

export const LIBRARY_TOOLBOX_TALK_FIELDS: Record<number, Array<Omit<FormField, 'id' | 'form_section_id' | 'created_at'>>> = {
  // Section 0: Meeting Details
  0: [
    {
      field_code: 'talk_date',
      label: 'Date',
      field_type: 'date',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'talk_time',
      label: 'Time',
      field_type: 'time',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'jobsite_id',
      label: 'Jobsite',
      field_type: 'jobsite_select',
      placeholder: 'Select jobsite',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
      library_source: 'jobsites',
      library_filters: { status: 'active' },
      auto_populate_fields: ['site_supervisor', 'site_hazards'],
    },
    {
      field_code: 'supervisor_id',
      label: 'Supervisor Conducting Talk',
      field_type: 'worker_select',
      placeholder: 'Select supervisor',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
      library_source: 'workers',
      library_filters: {},
    },
    {
      field_code: 'weather_conditions',
      label: 'Weather Conditions',
      field_type: 'dropdown',
      placeholder: null,
      help_text: 'May affect work activities',
      default_value: null,
      width: 'half',
      options: [
        { value: 'clear', label: '☀️ Clear' },
        { value: 'cloudy', label: '☁️ Cloudy' },
        { value: 'rain', label: '🌧️ Rain' },
        { value: 'snow', label: '❄️ Snow' },
        { value: 'wind', label: '💨 Windy' },
        { value: 'extreme_heat', label: '🔥 Extreme Heat' },
        { value: 'extreme_cold', label: '🥶 Extreme Cold' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'temperature',
      label: 'Temperature (°C)',
      field_type: 'number',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { min_value: -40, max_value: 50 },
      conditional_logic: null,
      order_index: 5,
    },
  ],

  // Section 1: Task & Hazards
  1: [
    {
      field_code: 'task_id',
      label: 'Task for Today',
      field_type: 'task_select',
      placeholder: 'Select the main task for today...',
      help_text: 'Hazards, equipment, and required certifications will auto-populate',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      // Task library integration
      library_source: 'tasks',
      library_filters: {},
      auto_populate_fields: [
        'task_hazards',
        'task_procedure',
        'required_equipment',
        'required_certifications',
        'required_ppe',
        'permits_required',
      ],
      use_search_mode: true,
      allow_quick_add: true,
    },
    {
      field_code: 'task_description',
      label: 'Task Description',
      field_type: 'textarea',
      placeholder: 'Describe the specific work being done today...',
      help_text: 'Add specific details for today\'s work',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'task_hazards',
      label: 'Hazards from Task Library',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated from task. Review with workers.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'additional_hazards',
      label: 'Additional Hazards Identified',
      field_type: 'hazard_multiselect',
      placeholder: 'Add any hazards specific to today\'s work...',
      help_text: 'Select any additional hazards not listed above',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 3,
      library_source: 'hazards',
      library_filters: {},
      auto_populate_fields: ['additional_ppe', 'additional_controls'],
      use_search_mode: true,
      allow_quick_add: true,
    },
    {
      field_code: 'site_hazards',
      label: 'Site-Specific Hazards',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-filled from jobsite. Review with workers.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'task_procedure',
      label: 'Safe Work Procedure',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Step-by-step procedure from task library',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 5,
    },
  ],

  // Section 2: Equipment & Certifications
  2: [
    {
      field_code: 'required_equipment',
      label: 'Required Equipment',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated from task library. Verify all equipment is available.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'equipment_inspected',
      label: 'All equipment has been pre-inspected',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'required_ppe',
      label: 'Required PPE',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated from task/hazards. Verify all workers have PPE.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'ppe_available',
      label: 'All workers have required PPE',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'required_certifications',
      label: 'Required Certifications',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated from task library. Verify workers have certifications.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'certification_issues',
      label: 'Certification Issues',
      field_type: 'textarea',
      placeholder: 'List any workers missing required certifications...',
      help_text: 'These workers cannot perform certification-required tasks',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'permits_required',
      label: 'Permits Required',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated from task library',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'permits_obtained',
      label: 'All required permits have been obtained',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 7,
    },
  ],

  // Section 3: Safety Discussion
  3: [
    {
      field_code: 'safety_topic',
      label: 'Safety Topic of the Day',
      field_type: 'text',
      placeholder: 'e.g., Fall Protection, Heat Stress, Lockout/Tagout',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'discussion_points',
      label: 'Key Discussion Points',
      field_type: 'textarea',
      placeholder: 'Summarize main points discussed...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true, min_length: 30 },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'worker_questions',
      label: 'Worker Questions/Concerns',
      field_type: 'textarea',
      placeholder: 'Document any questions or concerns raised by workers...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'near_misses_discussed',
      label: 'Near Misses/Incidents Discussed',
      field_type: 'textarea',
      placeholder: 'Any recent near misses or incidents reviewed?',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'emergency_procedures_reviewed',
      label: 'Emergency Procedures Reviewed',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'Assembly point, emergency contacts, first aid location',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
    },
  ],

  // Section 4: Attendance
  4: [
    {
      field_code: 'attendees',
      label: 'Workers Present',
      field_type: 'multiselect',
      placeholder: 'Select all workers in attendance',
      help_text: 'All workers must sign below',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      library_source: 'workers',
      library_filters: {},
      use_search_mode: true,
    },
    {
      field_code: 'attendee_count',
      label: 'Number of Attendees',
      field_type: 'number',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true, min_value: 1 },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'talk_duration',
      label: 'Duration (minutes)',
      field_type: 'number',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true, min_value: 5 },
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'all_workers_understand',
      label: 'All workers confirm they understand the hazards and controls',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'safe_to_proceed',
      label: 'It is safe to proceed with work',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'stop_work_authority',
      label: 'All workers understand they have stop work authority',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'supervisor_signature',
      label: 'Supervisor Signature',
      field_type: 'signature',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'gps_location',
      label: 'GPS Location',
      field_type: 'gps',
      placeholder: null,
      help_text: 'Verify location',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 7,
    },
  ],
};

export default {
  template: LIBRARY_TOOLBOX_TALK_TEMPLATE,
  sections: LIBRARY_TOOLBOX_TALK_SECTIONS,
  fields: LIBRARY_TOOLBOX_TALK_FIELDS,
};
