/**
 * Library-Integrated Equipment Inspection Form Configuration
 * 
 * This form demonstrates:
 * - QR code scanning for equipment lookup
 * - Equipment selection with auto-populate
 * - Dynamic inspection checklist from library
 * - Status update on defect
 * 
 * Test Case: Test 2 from integration tests
 */

import { FormTemplate, FormSection, FormField } from '@/components/form-builder/types';

export const LIBRARY_EQUIPMENT_INSPECTION_TEMPLATE: Omit<FormTemplate, 'id' | 'company_id' | 'created_at' | 'updated_at' | 'created_by'> = {
  form_code: 'LIB-EI-001',
  name: 'Equipment Pre-Use Inspection (Library Integrated)',
  description: 'Pre-use equipment inspection with dynamic checklists from equipment library',
  cor_element: 6,
  frequency: 'daily',
  estimated_time_minutes: 8,
  icon: 'wrench',
  color: '#3B82F6',
  version: 1,
  is_active: true,
  is_mandatory: true,
};

export const LIBRARY_EQUIPMENT_INSPECTION_SECTIONS: Array<Omit<FormSection, 'id' | 'form_template_id' | 'created_at'>> = [
  {
    title: 'Equipment Selection',
    description: 'Scan QR code or select equipment from inventory',
    order_index: 0,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Pre-Use Checklist',
    description: 'Complete the equipment-specific inspection checklist',
    order_index: 1,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Defects & Issues',
    description: 'Report any defects or safety concerns',
    order_index: 2,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Verification',
    description: 'Sign off on inspection completion',
    order_index: 3,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
];

export const LIBRARY_EQUIPMENT_INSPECTION_FIELDS: Record<number, Array<Omit<FormField, 'id' | 'form_section_id' | 'created_at'>>> = {
  // Section 0: Equipment Selection
  0: [
    {
      field_code: 'inspection_date',
      label: 'Inspection Date',
      field_type: 'date',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'inspection_time',
      label: 'Inspection Time',
      field_type: 'time',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'equipment_id',
      label: 'Select Equipment',
      field_type: 'equipment_select',
      placeholder: 'Scan QR code or search equipment...',
      help_text: 'Equipment details and checklist will auto-populate',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
      // Library integration
      library_source: 'equipment',
      library_filters: { status: 'in_service' },
      auto_populate_fields: [
        'equipment_type',
        'make_model',
        'serial_number',
        'last_inspection_date',
        'inspection_checklist',
        'current_location',
        'required_certifications',
      ],
      use_search_mode: true,
      allow_quick_add: false, // Equipment should be added through admin
    },
    {
      field_code: 'equipment_type',
      label: 'Equipment Type',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from equipment library',
      default_value: null,
      width: 'third',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'make_model',
      label: 'Make / Model',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from equipment library',
      default_value: null,
      width: 'third',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'serial_number',
      label: 'Serial Number',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from equipment library',
      default_value: null,
      width: 'third',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'last_inspection_date',
      label: 'Last Inspection',
      field_type: 'text',
      placeholder: null,
      help_text: 'From equipment records',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'current_location',
      label: 'Current Location',
      field_type: 'text',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 7,
    },
    {
      field_code: 'hour_meter_reading',
      label: 'Hour Meter Reading',
      field_type: 'number',
      placeholder: 'Enter current hours',
      help_text: 'If applicable',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { min_value: 0 },
      conditional_logic: null,
      order_index: 8,
    },
    {
      field_code: 'fuel_level',
      label: 'Fuel Level',
      field_type: 'slider',
      placeholder: null,
      help_text: 'Estimate fuel level (0-100%)',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { min_value: 0, max_value: 100 },
      conditional_logic: null,
      order_index: 9,
    },
  ],

  // Section 1: Pre-Use Checklist (Dynamic based on equipment type)
  1: [
    {
      field_code: 'checklist_intro',
      label: 'Inspection Checklist',
      field_type: 'text',
      placeholder: null,
      help_text: 'The checklist below is specific to the selected equipment type. Mark each item as Pass, Fail, or N/A.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 0,
    },
    // Dynamic checklist items will be rendered based on equipment_type
    // These are example items for scissor lift:
    {
      field_code: 'check_platform',
      label: 'Platform and guardrails secure',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'check_controls',
      label: 'All controls function properly',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'check_emergency_stop',
      label: 'Emergency stop button functional',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'check_battery',
      label: 'Battery charge adequate / No corrosion',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'check_hydraulics',
      label: 'Hydraulic system - no leaks',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'check_tires',
      label: 'Tires/wheels in good condition',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'check_outriggers',
      label: 'Outriggers/stabilizers functional (if applicable)',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 7,
    },
    {
      field_code: 'check_manual',
      label: 'Operator manual present',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 8,
    },
    {
      field_code: 'check_horn_alarm',
      label: 'Horn/alarm functional',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 9,
    },
    {
      field_code: 'check_general',
      label: 'No visible damage or defects',
      field_type: 'yes_no_na',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 10,
    },
  ],

  // Section 2: Defects & Issues
  2: [
    {
      field_code: 'defects_found',
      label: 'Were any defects found?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'If yes, describe defects below',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'defect_description',
      label: 'Defect Description',
      field_type: 'textarea',
      placeholder: 'Describe all defects found during inspection...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: {
        field_id: 'defects_found',
        operator: 'equals',
        value: 'yes',
      },
      order_index: 1,
    },
    {
      field_code: 'defect_photos',
      label: 'Photos of Defects',
      field_type: 'photo',
      placeholder: null,
      help_text: 'Take photos of any defects',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: {
        field_id: 'defects_found',
        operator: 'equals',
        value: 'yes',
      },
      order_index: 2,
    },
    {
      field_code: 'defect_severity',
      label: 'Defect Severity',
      field_type: 'radio',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: [
        { value: 'minor', label: '🟡 Minor - Equipment can be used with caution' },
        { value: 'moderate', label: '🟠 Moderate - Repair needed before next shift' },
        { value: 'critical', label: '🔴 Critical - Equipment must be taken out of service' },
      ],
      validation_rules: { required: true },
      conditional_logic: {
        field_id: 'defects_found',
        operator: 'equals',
        value: 'yes',
      },
      order_index: 3,
    },
    {
      field_code: 'take_out_of_service',
      label: 'Take Equipment Out of Service',
      field_type: 'checkbox',
      placeholder: null,
      help_text: 'Check this box to immediately mark equipment as out of service',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: {
        field_id: 'defect_severity',
        operator: 'equals',
        value: 'critical',
      },
      order_index: 4,
    },
    {
      field_code: 'lockout_tag_applied',
      label: 'Lockout/Tag-out Applied',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'Confirm lockout tag has been applied to equipment',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: {
        field_id: 'take_out_of_service',
        operator: 'equals',
        value: true,
      },
      order_index: 5,
    },
  ],

  // Section 3: Verification
  3: [
    {
      field_code: 'equipment_safe_to_use',
      label: 'Is this equipment safe to use?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'operator_name',
      label: 'Operator Name',
      field_type: 'worker_select',
      placeholder: 'Select the operator',
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
      library_source: 'workers',
      library_filters: {},
    },
    {
      field_code: 'operator_certified',
      label: 'Operator has required certifications',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'Verify operator is certified for this equipment type',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'inspector_signature',
      label: 'Inspector Signature',
      field_type: 'signature',
      placeholder: null,
      help_text: 'Sign to confirm inspection is complete and accurate',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
  ],
};

export default {
  template: LIBRARY_EQUIPMENT_INSPECTION_TEMPLATE,
  sections: LIBRARY_EQUIPMENT_INSPECTION_SECTIONS,
  fields: LIBRARY_EQUIPMENT_INSPECTION_FIELDS,
};
