/**
 * Library-Integrated Hazard Assessment Form Configuration
 * 
 * This form demonstrates full library integration with:
 * - Jobsite selection with auto-populate
 * - Hazard multi-select with trade filtering
 * - Worker multi-select filtered by jobsite
 * - Auto-populated controls and PPE
 * 
 * Test Case: Test 1 from integration tests
 */

import { FormTemplate, FormSection, FormField } from '@/components/form-builder/types';

export const LIBRARY_HAZARD_ASSESSMENT_TEMPLATE: Omit<FormTemplate, 'id' | 'company_id' | 'created_at' | 'updated_at' | 'created_by'> = {
  form_code: 'LIB-HA-001',
  name: 'Daily Hazard Assessment (Library Integrated)',
  description: 'Job hazard assessment with automatic population from master libraries',
  cor_element: 3,
  frequency: 'daily',
  estimated_time_minutes: 10,
  icon: 'alert-triangle',
  color: '#EF4444',
  version: 1,
  is_active: true,
  is_mandatory: true,
};

export const LIBRARY_HAZARD_ASSESSMENT_SECTIONS: Array<Omit<FormSection, 'id' | 'form_template_id' | 'created_at'>> = [
  {
    title: 'Site Information',
    description: 'Select jobsite and verify site-specific information',
    order_index: 0,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Hazard Identification',
    description: 'Identify all hazards present for today\'s work activities',
    order_index: 1,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Workers & Controls',
    description: 'Assign workers and confirm control measures',
    order_index: 2,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Verification',
    description: 'Supervisor verification and sign-off',
    order_index: 3,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
];

export const LIBRARY_HAZARD_ASSESSMENT_FIELDS: Record<number, Array<Omit<FormField, 'id' | 'form_section_id' | 'created_at'>>> = {
  // Section 0: Site Information
  0: [
    {
      field_code: 'assessment_date',
      label: 'Assessment Date',
      field_type: 'date',
      placeholder: null,
      help_text: 'Date of this hazard assessment',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      // No library integration - standard date field
    },
    {
      field_code: 'assessment_time',
      label: 'Start Time',
      field_type: 'time',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'jobsite_id',
      label: 'Select Jobsite',
      field_type: 'jobsite_select',
      placeholder: 'Search and select jobsite...',
      help_text: 'Site information will auto-populate',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
      // Library integration
      library_source: 'jobsites',
      library_filters: { status: 'active', is_active: true },
      auto_populate_fields: [
        'site_supervisor',
        'emergency_contact',
        'emergency_contact_secondary',
        'site_hazards',
        'assembly_point',
        'nearest_hospital',
      ],
      use_search_mode: true,
    },
    {
      field_code: 'site_supervisor',
      label: 'Site Supervisor',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from jobsite',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'emergency_contact',
      label: 'Emergency Contact',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from jobsite',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'site_hazards',
      label: 'Known Site Hazards',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-filled from jobsite registry. Review and add any new hazards.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 5,
    },
  ],

  // Section 1: Hazard Identification
  1: [
    {
      field_code: 'task_id',
      label: 'Task/Activity for Today',
      field_type: 'task_select',
      placeholder: 'Select main task...',
      help_text: 'Hazards and equipment will auto-populate from task library',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      // Library integration
      library_source: 'tasks',
      library_filters: { trade: 'Concrete' }, // Can be dynamic based on company
      auto_populate_fields: [
        'task_hazards',
        'required_equipment',
        'required_certifications',
        'work_procedure',
      ],
      use_search_mode: true,
      allow_quick_add: true,
    },
    {
      field_code: 'identified_hazards',
      label: 'Identify Hazards',
      field_type: 'hazard_multiselect',
      placeholder: 'Search and select hazards...',
      help_text: 'Select all hazards present. PPE and controls will auto-populate.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
      // Library integration
      library_source: 'hazards',
      library_filters: { trade: 'Concrete' },
      auto_populate_fields: [
        'required_ppe',
        'engineering_controls',
        'admin_controls',
        'all_regulations',
        'highest_risk_level',
      ],
      use_search_mode: true,
      search_mode_threshold: 30,
      allow_quick_add: true,
    },
    {
      field_code: 'additional_hazards',
      label: 'Additional Hazards (Not in Library)',
      field_type: 'textarea',
      placeholder: 'Describe any site-specific hazards not listed above...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'highest_risk_level',
      label: 'Overall Risk Level',
      field_type: 'dropdown',
      placeholder: 'Auto-calculated from hazards',
      help_text: 'Automatically set to highest risk among selected hazards',
      default_value: null,
      width: 'half',
      options: [
        { value: 'negligible', label: '🟢 Negligible' },
        { value: 'low', label: '🟡 Low' },
        { value: 'medium', label: '🟠 Medium' },
        { value: 'high', label: '🔴 High' },
        { value: 'critical', label: '⚫ Critical' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
  ],

  // Section 2: Workers & Controls
  2: [
    {
      field_code: 'workers_assigned',
      label: 'Workers on Task',
      field_type: 'multiselect',
      placeholder: 'Select workers assigned to this task...',
      help_text: 'Certification compliance will be checked automatically',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      // Library integration
      library_source: 'workers',
      library_filters: {}, // Will be filtered by jobsite_id dynamically
      use_search_mode: true,
    },
    {
      field_code: 'required_ppe',
      label: 'Required PPE',
      field_type: 'multiselect',
      placeholder: null,
      help_text: 'Auto-populated from selected hazards. Confirm all workers have PPE.',
      default_value: null,
      width: 'full',
      options: null, // Will be populated from hazard library
      validation_rules: {},
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'ppe_verified',
      label: 'All workers have required PPE',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'engineering_controls',
      label: 'Engineering Controls',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated from hazards. Confirm controls are in place.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'admin_controls',
      label: 'Administrative Controls',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-populated. Add any additional procedures.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'controls_verified',
      label: 'All controls are in place',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 5,
    },
  ],

  // Section 3: Verification
  3: [
    {
      field_code: 'workers_briefed',
      label: 'All workers have been briefed on hazards and controls',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'safe_to_proceed',
      label: 'Is it safe to proceed with work?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'If No, stop work and notify supervisor',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'stop_work_reason',
      label: 'Reason for Stop Work',
      field_type: 'textarea',
      placeholder: 'Explain why work cannot proceed safely...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: {
        field_id: 'safe_to_proceed',
        operator: 'equals',
        value: 'no',
      },
      order_index: 2,
    },
    {
      field_code: 'supervisor_signature',
      label: 'Supervisor Signature',
      field_type: 'signature',
      placeholder: null,
      help_text: 'Sign to confirm assessment is complete and accurate',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'gps_location',
      label: 'Location Verification',
      field_type: 'gps',
      placeholder: null,
      help_text: 'GPS coordinates for verification',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
  ],
};

export default {
  template: LIBRARY_HAZARD_ASSESSMENT_TEMPLATE,
  sections: LIBRARY_HAZARD_ASSESSMENT_SECTIONS,
  fields: LIBRARY_HAZARD_ASSESSMENT_FIELDS,
};
