/**
 * Library-Integrated Incident Report Form Configuration
 * 
 * This form demonstrates:
 * - SDS integration for chemical incidents
 * - Auto-populated first aid procedures
 * - WHMIS pictogram display
 * - Emergency contact integration
 * 
 * Test Case: Test 3 from integration tests
 */

import { FormTemplate, FormSection, FormField } from '@/components/form-builder/types';

export const LIBRARY_INCIDENT_REPORT_TEMPLATE: Omit<FormTemplate, 'id' | 'company_id' | 'created_at' | 'updated_at' | 'created_by'> = {
  form_code: 'LIB-IR-001',
  name: 'Incident Report (Library Integrated)',
  description: 'Report safety incidents with automatic SDS lookup and first aid procedures',
  cor_element: 9,
  frequency: 'as_needed',
  estimated_time_minutes: 15,
  icon: 'alert-octagon',
  color: '#DC2626',
  version: 1,
  is_active: true,
  is_mandatory: true,
};

export const LIBRARY_INCIDENT_REPORT_SECTIONS: Array<Omit<FormSection, 'id' | 'form_template_id' | 'created_at'>> = [
  {
    title: 'Incident Details',
    description: 'Basic information about the incident',
    order_index: 0,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Chemical Exposure Details',
    description: 'Complete if incident involved chemical exposure',
    order_index: 1,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: {
      field_id: 'incident_type',
      operator: 'equals',
      value: 'chemical_exposure',
    },
  },
  {
    title: 'Injured Person(s)',
    description: 'Details about anyone injured in the incident',
    order_index: 2,
    is_repeatable: true,
    min_repeats: 1,
    max_repeats: 10,
    conditional_logic: {
      field_id: 'injury_occurred',
      operator: 'equals',
      value: 'yes',
    },
  },
  {
    title: 'Investigation & Corrective Actions',
    description: 'Root cause analysis and prevention measures',
    order_index: 3,
    is_repeatable: false,
    min_repeats: 1,
    max_repeats: 1,
    conditional_logic: null,
  },
  {
    title: 'Witness Statements',
    description: 'Collect statements from witnesses',
    order_index: 4,
    is_repeatable: true,
    min_repeats: 0,
    max_repeats: 5,
    conditional_logic: null,
  },
];

export const LIBRARY_INCIDENT_REPORT_FIELDS: Record<number, Array<Omit<FormField, 'id' | 'form_section_id' | 'created_at'>>> = {
  // Section 0: Incident Details
  0: [
    {
      field_code: 'incident_date',
      label: 'Date of Incident',
      field_type: 'date',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
    },
    {
      field_code: 'incident_time',
      label: 'Time of Incident',
      field_type: 'time',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'jobsite_id',
      label: 'Location (Jobsite)',
      field_type: 'jobsite_select',
      placeholder: 'Select jobsite where incident occurred',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
      library_source: 'jobsites',
      library_filters: {},
      auto_populate_fields: ['site_supervisor', 'emergency_contact'],
    },
    {
      field_code: 'exact_location',
      label: 'Exact Location of Incident',
      field_type: 'text',
      placeholder: 'e.g., Second floor, near elevator shaft',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'incident_type',
      label: 'Type of Incident',
      field_type: 'dropdown',
      placeholder: 'Select incident type',
      help_text: null,
      default_value: null,
      width: 'half',
      options: [
        { value: 'near_miss', label: 'Near Miss' },
        { value: 'first_aid', label: 'First Aid Injury' },
        { value: 'medical_aid', label: 'Medical Aid Injury' },
        { value: 'lost_time', label: 'Lost Time Injury' },
        { value: 'property_damage', label: 'Property Damage' },
        { value: 'environmental', label: 'Environmental Release' },
        { value: 'chemical_exposure', label: 'Chemical Exposure' },
        { value: 'fire', label: 'Fire' },
        { value: 'vehicle', label: 'Vehicle Incident' },
        { value: 'other', label: 'Other' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'injury_occurred',
      label: 'Did an injury occur?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'incident_description',
      label: 'Incident Description',
      field_type: 'textarea',
      placeholder: 'Describe what happened in detail...',
      help_text: 'Include what the worker was doing, what went wrong, and the immediate outcome',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true, min_length: 50 },
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'incident_photos',
      label: 'Incident Photos',
      field_type: 'photo',
      placeholder: null,
      help_text: 'Take photos of the incident scene, equipment, or hazards',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 7,
    },
  ],

  // Section 1: Chemical Exposure Details (conditional)
  1: [
    {
      field_code: 'sds_product_id',
      label: 'Product Involved',
      field_type: 'dropdown',
      placeholder: 'Search for the chemical/product...',
      help_text: 'Select the product from SDS library. First aid and WHMIS info will auto-populate.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      // SDS library integration
      library_source: 'sds',
      library_filters: { is_on_site: true },
      auto_populate_fields: [
        'whmis_classification',
        'whmis_pictograms',
        'first_aid_procedure',
        'emergency_phone',
        'required_ppe',
        'hazard_statements',
      ],
      use_search_mode: true,
    },
    {
      field_code: 'whmis_classification',
      label: 'WHMIS Classification',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from SDS',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'whmis_pictograms',
      label: 'WHMIS Pictograms',
      field_type: 'text',
      placeholder: null,
      help_text: 'Hazard pictograms from SDS',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'exposure_type',
      label: 'Type of Exposure',
      field_type: 'multiselect',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: [
        { value: 'inhalation', label: 'Inhalation' },
        { value: 'skin_contact', label: 'Skin Contact' },
        { value: 'eye_contact', label: 'Eye Contact' },
        { value: 'ingestion', label: 'Ingestion' },
        { value: 'injection', label: 'Injection/Puncture' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'exposure_duration',
      label: 'Approximate Duration of Exposure',
      field_type: 'text',
      placeholder: 'e.g., 5 minutes',
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'quantity_involved',
      label: 'Quantity Involved',
      field_type: 'text',
      placeholder: 'e.g., Splash approximately 50ml',
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'first_aid_procedure',
      label: 'First Aid Procedure',
      field_type: 'textarea',
      placeholder: null,
      help_text: 'Auto-filled from SDS. Follow these procedures immediately.',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'first_aid_given',
      label: 'First Aid Administered',
      field_type: 'textarea',
      placeholder: 'Describe first aid that was given...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 7,
    },
    {
      field_code: 'emergency_phone',
      label: 'Emergency Phone (Product)',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from SDS. Call for additional guidance.',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 8,
    },
    {
      field_code: 'poison_control_called',
      label: 'Poison Control / Emergency Line Called?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 9,
    },
    {
      field_code: 'medical_attention_sought',
      label: 'Medical Attention Required?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 10,
    },
    {
      field_code: 'sds_provided_to_medical',
      label: 'SDS Provided to Medical Personnel?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'Always provide SDS to medical professionals',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: {
        field_id: 'medical_attention_sought',
        operator: 'equals',
        value: 'yes',
      },
      order_index: 11,
    },
  ],

  // Section 2: Injured Person(s)
  2: [
    {
      field_code: 'injured_worker_id',
      label: 'Injured Worker',
      field_type: 'worker_select',
      placeholder: 'Select the injured worker',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      library_source: 'workers',
      library_filters: {},
      auto_populate_fields: ['worker_position', 'emergency_contact_name', 'emergency_contact_phone'],
    },
    {
      field_code: 'injury_type',
      label: 'Type of Injury',
      field_type: 'multiselect',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: [
        { value: 'laceration', label: 'Cut/Laceration' },
        { value: 'contusion', label: 'Bruise/Contusion' },
        { value: 'fracture', label: 'Fracture/Break' },
        { value: 'sprain', label: 'Sprain/Strain' },
        { value: 'burn', label: 'Burn' },
        { value: 'chemical_burn', label: 'Chemical Burn' },
        { value: 'eye_injury', label: 'Eye Injury' },
        { value: 'respiratory', label: 'Respiratory Issue' },
        { value: 'crush', label: 'Crush Injury' },
        { value: 'electric_shock', label: 'Electric Shock' },
        { value: 'head_injury', label: 'Head Injury/Concussion' },
        { value: 'heat_illness', label: 'Heat Illness' },
        { value: 'other', label: 'Other' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'body_part_injured',
      label: 'Body Part(s) Injured',
      field_type: 'multiselect',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: [
        { value: 'head', label: 'Head' },
        { value: 'face', label: 'Face' },
        { value: 'eyes', label: 'Eyes' },
        { value: 'neck', label: 'Neck' },
        { value: 'shoulder', label: 'Shoulder' },
        { value: 'arm', label: 'Arm' },
        { value: 'elbow', label: 'Elbow' },
        { value: 'wrist', label: 'Wrist' },
        { value: 'hand', label: 'Hand' },
        { value: 'finger', label: 'Finger(s)' },
        { value: 'back', label: 'Back' },
        { value: 'chest', label: 'Chest' },
        { value: 'abdomen', label: 'Abdomen' },
        { value: 'hip', label: 'Hip' },
        { value: 'leg', label: 'Leg' },
        { value: 'knee', label: 'Knee' },
        { value: 'ankle', label: 'Ankle' },
        { value: 'foot', label: 'Foot' },
        { value: 'toe', label: 'Toe(s)' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'injury_severity',
      label: 'Injury Severity',
      field_type: 'radio',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: [
        { value: 'minor', label: '🟢 Minor - First aid only' },
        { value: 'moderate', label: '🟡 Moderate - Medical treatment, no lost time' },
        { value: 'serious', label: '🟠 Serious - Lost time expected' },
        { value: 'critical', label: '🔴 Critical - Hospitalization required' },
        { value: 'fatal', label: '⚫ Fatal' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'emergency_contact_name',
      label: 'Emergency Contact Name',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from worker profile',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 4,
    },
    {
      field_code: 'emergency_contact_phone',
      label: 'Emergency Contact Phone',
      field_type: 'text',
      placeholder: null,
      help_text: 'Auto-filled from worker profile',
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: {},
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'emergency_contact_notified',
      label: 'Emergency Contact Notified?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 6,
    },
  ],

  // Section 3: Investigation & Corrective Actions
  3: [
    {
      field_code: 'hazard_involved',
      label: 'Hazard(s) Involved',
      field_type: 'hazard_multiselect',
      placeholder: 'Select hazards that contributed to incident',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      library_source: 'hazards',
      library_filters: {},
      use_search_mode: true,
    },
    {
      field_code: 'root_cause',
      label: 'Root Cause Analysis',
      field_type: 'textarea',
      placeholder: 'What was the underlying cause of this incident?',
      help_text: 'Consider task, worker, equipment, environment, and management factors',
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true, min_length: 50 },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'contributing_factors',
      label: 'Contributing Factors',
      field_type: 'multiselect',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: [
        { value: 'inadequate_training', label: 'Inadequate Training' },
        { value: 'improper_procedure', label: 'Improper Procedure' },
        { value: 'equipment_failure', label: 'Equipment Failure' },
        { value: 'lack_of_ppe', label: 'Lack of PPE' },
        { value: 'ppe_not_used', label: 'PPE Not Used' },
        { value: 'housekeeping', label: 'Poor Housekeeping' },
        { value: 'fatigue', label: 'Fatigue' },
        { value: 'rushing', label: 'Rushing/Time Pressure' },
        { value: 'communication', label: 'Communication Breakdown' },
        { value: 'environmental', label: 'Environmental Conditions' },
        { value: 'distraction', label: 'Distraction' },
        { value: 'supervision', label: 'Inadequate Supervision' },
        { value: 'other', label: 'Other' },
      ],
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
    },
    {
      field_code: 'corrective_actions',
      label: 'Corrective Actions',
      field_type: 'textarea',
      placeholder: 'What actions will be taken to prevent recurrence?',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true, min_length: 30 },
      conditional_logic: null,
      order_index: 3,
    },
    {
      field_code: 'action_assigned_to',
      label: 'Corrective Action Assigned To',
      field_type: 'worker_select',
      placeholder: 'Select responsible person',
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 4,
      library_source: 'workers',
      library_filters: {},
    },
    {
      field_code: 'action_due_date',
      label: 'Corrective Action Due Date',
      field_type: 'date',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'half',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 5,
    },
    {
      field_code: 'supervisor_notified',
      label: 'Supervisor Notified',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'third',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 6,
    },
    {
      field_code: 'management_notified',
      label: 'Management Notified',
      field_type: 'yes_no',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'third',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 7,
    },
    {
      field_code: 'moltc_reportable',
      label: 'MOLTC Reportable?',
      field_type: 'yes_no',
      placeholder: null,
      help_text: 'Critical injuries must be reported to Ministry of Labour',
      default_value: null,
      width: 'third',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 8,
    },
  ],

  // Section 4: Witness Statements
  4: [
    {
      field_code: 'witness_worker_id',
      label: 'Witness Name',
      field_type: 'worker_select',
      placeholder: 'Select witness',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 0,
      library_source: 'workers',
      library_filters: {},
    },
    {
      field_code: 'witness_statement',
      label: 'Witness Statement',
      field_type: 'textarea',
      placeholder: 'Describe what the witness observed...',
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true, min_length: 30 },
      conditional_logic: null,
      order_index: 1,
    },
    {
      field_code: 'witness_signature',
      label: 'Witness Signature',
      field_type: 'signature',
      placeholder: null,
      help_text: null,
      default_value: null,
      width: 'full',
      options: null,
      validation_rules: { required: true },
      conditional_logic: null,
      order_index: 2,
    },
  ],
};

export default {
  template: LIBRARY_INCIDENT_REPORT_TEMPLATE,
  sections: LIBRARY_INCIDENT_REPORT_SECTIONS,
  fields: LIBRARY_INCIDENT_REPORT_FIELDS,
};
