/**
 * Emergency Equipment Inspection
 * COR Element 11: Emergency Preparedness
 * 
 * Inspect emergency response equipment.
 */

import type { FormConfig } from '../../import-forms';

export const emergencyEquipmentInspection: FormConfig = {
  code: 'emergency_equipment_inspection',
  name: 'Emergency Equipment Inspection',
  description: 'Inspect emergency response equipment including fire extinguishers, first aid kits, AEDs, eye wash stations, and emergency showers.',
  cor_element: 11,
  frequency: 'monthly',
  estimated_time_minutes: 20,
  icon: 'Shield',
  color: '#EF4444',
  is_mandatory: true,

  sections: [
    {
      title: 'Inspection Details',
      order_index: 0,
      fields: [
        {
          code: 'inspection_date',
          label: 'Inspection Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'inspector',
          label: 'Inspector',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'specific_area',
          label: 'Specific Area/Building',
          field_type: 'text',
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Fire Extinguishers',
      description: 'Inspect all fire extinguishers in the area',
      order_index: 1,
      is_repeatable: true,
      fields: [
        {
          code: 'fe_location',
          label: 'Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'fe_type',
          label: 'Type',
          field_type: 'dropdown',
          options: [
            { value: 'abc', label: 'ABC (Multi-Purpose)' },
            { value: 'co2', label: 'CO2' },
            { value: 'water', label: 'Water' },
            { value: 'class_d', label: 'Class D' },
            { value: 'class_k', label: 'Class K' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'fe_accessible',
          label: 'Accessible/Unobstructed',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'fe_sign_visible',
          label: 'Sign Visible',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'fe_pressure_ok',
          label: 'Pressure Gauge in Green',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'fe_seal_intact',
          label: 'Seal/Pin Intact',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'fe_condition',
          label: 'Physical Condition',
          field_type: 'radio',
          options: ['Good', 'Fair', 'Poor'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'fe_inspection_tag',
          label: 'Inspection Tag Current',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
        {
          code: 'fe_notes',
          label: 'Notes',
          field_type: 'text',
          order_index: 8,
          width: 'full',
        },
      ],
    },
    {
      title: 'First Aid Kits',
      description: 'Inspect all first aid kits in the area',
      order_index: 2,
      is_repeatable: true,
      fields: [
        {
          code: 'fak_location',
          label: 'Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'fak_type',
          label: 'Kit Type/Size',
          field_type: 'dropdown',
          options: [
            { value: 'type_1', label: 'Type 1 (Basic)' },
            { value: 'type_2', label: 'Type 2 (Intermediate)' },
            { value: 'type_3', label: 'Type 3 (Comprehensive)' },
            { value: 'vehicle', label: 'Vehicle Kit' },
            { value: 'custom', label: 'Custom/Specialty' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'fak_accessible',
          label: 'Accessible/Visible',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'fak_stocked',
          label: 'Properly Stocked',
          field_type: 'radio',
          options: ['Pass', 'Fail', 'Partial'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'fak_items_expired',
          label: 'Any Items Expired?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'fak_seal_intact',
          label: 'Seal Intact (if applicable)',
          field_type: 'radio',
          options: ['Pass', 'Fail', 'N/A'],
          order_index: 5,
          width: 'half',
        },
        {
          code: 'fak_items_needed',
          label: 'Items Needing Replacement',
          field_type: 'textarea',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'AED (Automated External Defibrillator)',
      description: 'Inspect AED units (if applicable)',
      order_index: 3,
      is_repeatable: true,
      fields: [
        {
          code: 'aed_location',
          label: 'Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'aed_accessible',
          label: 'Accessible/Sign Visible',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'aed_status_ok',
          label: 'Status Indicator OK',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'aed_pads_valid',
          label: 'Pads Not Expired',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'aed_battery_ok',
          label: 'Battery Status OK',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'aed_supplies',
          label: 'Supplies Present (gloves, razor, etc.)',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          order_index: 5,
          width: 'half',
        },
        {
          code: 'aed_notes',
          label: 'Notes',
          field_type: 'text',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Eye Wash Stations / Emergency Showers',
      description: 'Inspect eye wash and emergency shower stations (if applicable)',
      order_index: 4,
      is_repeatable: true,
      fields: [
        {
          code: 'ews_location',
          label: 'Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'ews_type',
          label: 'Type',
          field_type: 'dropdown',
          options: [
            { value: 'eye_wash', label: 'Eye Wash Station' },
            { value: 'emergency_shower', label: 'Emergency Shower' },
            { value: 'combination', label: 'Combination Unit' },
            { value: 'portable', label: 'Portable Eye Wash' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'ews_accessible',
          label: 'Accessible (within 10 seconds)',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'ews_sign_visible',
          label: 'Sign Visible',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'ews_tested',
          label: 'Flow Tested',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'ews_clean',
          label: 'Clean/Free of Contamination',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'ews_notes',
          label: 'Notes',
          field_type: 'text',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Other Emergency Equipment',
      order_index: 5,
      fields: [
        {
          code: 'emergency_lighting',
          label: 'Emergency Lighting Operational',
          field_type: 'radio',
          options: ['Pass', 'Fail', 'N/A'],
          order_index: 0,
          width: 'half',
        },
        {
          code: 'exit_signs',
          label: 'Exit Signs Illuminated',
          field_type: 'radio',
          options: ['Pass', 'Fail', 'N/A'],
          order_index: 1,
          width: 'half',
        },
        {
          code: 'alarm_system',
          label: 'Alarm System Status',
          field_type: 'radio',
          options: ['Operational', 'Needs Attention', 'N/A'],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'emergency_contacts_posted',
          label: 'Emergency Contacts Posted',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'evacuation_maps_posted',
          label: 'Evacuation Maps Posted',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'assembly_point_marked',
          label: 'Assembly Point Clearly Marked',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'spill_kits',
          label: 'Spill Kits Available (if required)',
          field_type: 'radio',
          options: ['Pass', 'Fail', 'N/A'],
          order_index: 6,
          width: 'half',
        },
      ],
    },
    {
      title: 'Deficiencies Found',
      order_index: 6,
      fields: [
        {
          code: 'deficiencies_found',
          label: 'Were any deficiencies found?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'deficiency_details',
          label: 'Deficiency Details',
          field_type: 'textarea',
          placeholder: 'Describe all deficiencies found...',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'corrective_actions',
          label: 'Corrective Actions Required',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'target_completion',
          label: 'Target Completion Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'photos',
          label: 'Photos of Deficiencies',
          field_type: 'photo',
          conditional_logic: {
            field_code: 'deficiencies_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'next_inspection_date',
          label: 'Next Inspection Due',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 7,
      fields: [
        {
          code: 'inspector_signature',
          label: 'Inspector Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    creates_task: true,
    task_template: {
      title: 'Address Emergency Equipment Deficiencies',
      priority: 'high',
      due_hours: 24,
    },
    sync_priority: 2,
    requires_approval: false,
  },
};
