/**
 * Injury/Illness Statistics Form
 * COR Element 12: Statistics & Records
 * 
 * Track and report injury/illness statistics.
 */

import type { FormConfig } from '../../import-forms';

export const injuryIllnessStatistics: FormConfig = {
  code: 'injury_illness_statistics',
  name: 'Injury/Illness Statistics Report',
  description: 'Compile and report workplace injury and illness statistics for the reporting period.',
  cor_element: 12,
  frequency: 'monthly',
  estimated_time_minutes: 30,
  icon: 'BarChart2',
  color: '#6366F1',
  is_mandatory: true,

  sections: [
    {
      title: 'Report Information',
      order_index: 0,
      fields: [
        {
          code: 'report_date',
          label: 'Report Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'prepared_by',
          label: 'Prepared By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'reporting_period',
          label: 'Reporting Period',
          field_type: 'dropdown',
          options: [
            { value: 'monthly', label: 'Monthly' },
            { value: 'quarterly', label: 'Quarterly' },
            { value: 'annual', label: 'Annual' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'period_start',
          label: 'Period Start Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'period_end',
          label: 'Period End Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Location/Jobsite (or Company-Wide)',
          field_type: 'jobsite_select',
          help_text: 'Leave blank for company-wide statistics',
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Workforce Data',
      order_index: 1,
      fields: [
        {
          code: 'average_employees',
          label: 'Average Number of Employees',
          field_type: 'number',
          validation_rules: { required: true, min_value: 1 },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'total_hours_worked',
          label: 'Total Hours Worked',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'half',
        },
      ],
    },
    {
      title: 'Incident Statistics',
      order_index: 2,
      fields: [
        {
          code: 'fatalities',
          label: 'Fatalities',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'lost_time_injuries',
          label: 'Lost Time Injuries',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'medical_treatment',
          label: 'Medical Treatment Injuries',
          field_type: 'number',
          help_text: 'Beyond first aid, no lost time',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'first_aid',
          label: 'First Aid Cases',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'near_misses',
          label: 'Near Misses Reported',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 4,
          width: 'quarter',
        },
        {
          code: 'property_damage',
          label: 'Property Damage Incidents',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 5,
          width: 'quarter',
        },
        {
          code: 'occupational_illnesses',
          label: 'Occupational Illnesses',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 6,
          width: 'quarter',
        },
        {
          code: 'total_recordable',
          label: 'Total Recordable Incidents',
          field_type: 'number',
          help_text: 'Fatalities + LTI + Medical Treatment',
          validation_rules: { required: true, min_value: 0 },
          order_index: 7,
          width: 'quarter',
        },
      ],
    },
    {
      title: 'Lost Time Details',
      order_index: 3,
      fields: [
        {
          code: 'lost_days',
          label: 'Total Lost Work Days',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'restricted_days',
          label: 'Total Restricted Work Days',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'days_since_lti',
          label: 'Days Since Last LTI',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'half',
        },
      ],
    },
    {
      title: 'Calculated Rates',
      description: 'Safety performance rates',
      order_index: 4,
      fields: [
        {
          code: 'trir',
          label: 'Total Recordable Incident Rate (TRIR)',
          field_type: 'number',
          help_text: '(Total Recordable × 200,000) / Hours Worked',
          order_index: 0,
          width: 'half',
        },
        {
          code: 'ltir',
          label: 'Lost Time Incident Rate (LTIR)',
          field_type: 'number',
          help_text: '(LTI × 200,000) / Hours Worked',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'severity_rate',
          label: 'Severity Rate',
          field_type: 'number',
          help_text: '(Lost Days × 200,000) / Hours Worked',
          order_index: 2,
          width: 'half',
        },
        {
          code: 'frequency_rate',
          label: 'Frequency Rate',
          field_type: 'number',
          help_text: '(Total Injuries × 1,000,000) / Hours Worked',
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Incident Breakdown',
      description: 'Categorize incidents by type',
      order_index: 5,
      fields: [
        {
          code: 'body_part_most_affected',
          label: 'Most Commonly Affected Body Part',
          field_type: 'dropdown',
          options: [
            { value: 'hands_fingers', label: 'Hands/Fingers' },
            { value: 'back', label: 'Back' },
            { value: 'eyes', label: 'Eyes' },
            { value: 'head', label: 'Head' },
            { value: 'feet_legs', label: 'Feet/Legs' },
            { value: 'arms_shoulders', label: 'Arms/Shoulders' },
            { value: 'multiple', label: 'Multiple' },
            { value: 'other', label: 'Other' },
          ],
          order_index: 0,
          width: 'half',
        },
        {
          code: 'injury_type_most_common',
          label: 'Most Common Injury Type',
          field_type: 'dropdown',
          options: [
            { value: 'strains_sprains', label: 'Strains/Sprains' },
            { value: 'cuts_lacerations', label: 'Cuts/Lacerations' },
            { value: 'bruises_contusions', label: 'Bruises/Contusions' },
            { value: 'fractures', label: 'Fractures' },
            { value: 'burns', label: 'Burns' },
            { value: 'foreign_body', label: 'Foreign Body' },
            { value: 'other', label: 'Other' },
          ],
          order_index: 1,
          width: 'half',
        },
        {
          code: 'root_cause_most_common',
          label: 'Most Common Root Cause',
          field_type: 'dropdown',
          options: [
            { value: 'unsafe_act', label: 'Unsafe Act' },
            { value: 'unsafe_condition', label: 'Unsafe Condition' },
            { value: 'equipment_failure', label: 'Equipment Failure' },
            { value: 'procedure_violation', label: 'Procedure Violation' },
            { value: 'lack_of_training', label: 'Lack of Training' },
            { value: 'other', label: 'Other' },
          ],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'department_most_incidents',
          label: 'Department with Most Incidents',
          field_type: 'text',
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Comparison & Trends',
      order_index: 6,
      fields: [
        {
          code: 'previous_period_trir',
          label: 'Previous Period TRIR',
          field_type: 'number',
          order_index: 0,
          width: 'half',
        },
        {
          code: 'trend_direction',
          label: 'Trend Direction',
          field_type: 'dropdown',
          options: [
            { value: 'improving', label: 'Improving' },
            { value: 'stable', label: 'Stable' },
            { value: 'worsening', label: 'Worsening' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'trend_analysis',
          label: 'Trend Analysis Comments',
          field_type: 'textarea',
          placeholder: 'Analyze trends and patterns in the data...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'areas_of_concern',
          label: 'Areas of Concern',
          field_type: 'textarea',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'recommendations',
          label: 'Recommendations',
          field_type: 'textarea',
          placeholder: 'What actions are recommended based on the statistics?',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 7,
      fields: [
        {
          code: 'prepared_by_signature',
          label: 'Prepared By Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'reviewed_by_signature',
          label: 'Reviewed By Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    sync_priority: 3,
    requires_approval: true,
  },
};
