/**
 * Safety Performance Summary
 * COR Element 12: Statistics & Records
 * 
 * Summarize overall safety performance metrics.
 */

import type { FormConfig } from '../../import-forms';

export const safetyPerformanceSummary: FormConfig = {
  code: 'safety_performance_summary',
  name: 'Safety Performance Summary',
  description: 'Comprehensive summary of safety performance metrics for management review.',
  cor_element: 12,
  frequency: 'monthly',
  estimated_time_minutes: 25,
  icon: 'TrendingUp',
  color: '#10B981',
  is_mandatory: true,

  sections: [
    {
      title: 'Report Information',
      order_index: 0,
      fields: [
        {
          code: 'report_date',
          label: 'Report Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'prepared_by',
          label: 'Prepared By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'period_start',
          label: 'Period Start',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'period_end',
          label: 'Period End',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Leading Indicators',
      description: 'Proactive safety measures',
      order_index: 1,
      fields: [
        {
          code: 'safety_meetings_held',
          label: 'Safety Meetings Held',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'toolbox_talks_conducted',
          label: 'Toolbox Talks Conducted',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'inspections_completed',
          label: 'Inspections Completed',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'hazards_reported',
          label: 'Hazards Reported',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'hazards_corrected',
          label: 'Hazards Corrected',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 4,
          width: 'quarter',
        },
        {
          code: 'training_sessions',
          label: 'Training Sessions Delivered',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 5,
          width: 'quarter',
        },
        {
          code: 'workers_trained',
          label: 'Workers Trained',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 6,
          width: 'quarter',
        },
        {
          code: 'safety_observations',
          label: 'Safety Observations Made',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 7,
          width: 'quarter',
        },
      ],
    },
    {
      title: 'Lagging Indicators',
      description: 'Reactive metrics',
      order_index: 2,
      fields: [
        {
          code: 'total_incidents',
          label: 'Total Incidents',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'near_misses',
          label: 'Near Misses',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'first_aid_cases',
          label: 'First Aid Cases',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'recordable_injuries',
          label: 'Recordable Injuries',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'lost_time_injuries',
          label: 'Lost Time Injuries',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 4,
          width: 'quarter',
        },
        {
          code: 'lost_work_days',
          label: 'Lost Work Days',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 5,
          width: 'quarter',
        },
        {
          code: 'regulatory_violations',
          label: 'Regulatory Violations',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 6,
          width: 'quarter',
        },
        {
          code: 'property_damage_incidents',
          label: 'Property Damage Incidents',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 7,
          width: 'quarter',
        },
      ],
    },
    {
      title: 'Compliance Metrics',
      order_index: 3,
      fields: [
        {
          code: 'inspection_completion_rate',
          label: 'Inspection Completion Rate (%)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0, max_value: 100 },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'corrective_action_closure_rate',
          label: 'Corrective Action Closure Rate (%)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0, max_value: 100 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'training_compliance_rate',
          label: 'Training Compliance Rate (%)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0, max_value: 100 },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'ppe_compliance_rate',
          label: 'PPE Compliance Rate (%)',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'overdue_corrective_actions',
          label: 'Overdue Corrective Actions',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'open_corrective_actions',
          label: 'Open Corrective Actions',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Comparison to Targets',
      order_index: 4,
      fields: [
        {
          code: 'trir_actual',
          label: 'TRIR - Actual',
          field_type: 'number',
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'trir_target',
          label: 'TRIR - Target',
          field_type: 'number',
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'ltir_actual',
          label: 'LTIR - Actual',
          field_type: 'number',
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'ltir_target',
          label: 'LTIR - Target',
          field_type: 'number',
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'targets_met',
          label: 'Are safety targets being met?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'target_variance_explanation',
          label: 'Variance Explanation',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'targets_met',
            operator: 'not_equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Key Achievements',
      order_index: 5,
      fields: [
        {
          code: 'achievements',
          label: 'Key Safety Achievements This Period',
          field_type: 'textarea',
          placeholder: 'List notable safety achievements...',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'recognitions',
          label: 'Safety Recognitions',
          field_type: 'textarea',
          placeholder: 'Note any safety awards, recognitions, or positive behaviors...',
          order_index: 1,
          width: 'full',
        },
      ],
    },
    {
      title: 'Areas for Improvement',
      order_index: 6,
      fields: [
        {
          code: 'improvement_areas',
          label: 'Areas Requiring Improvement',
          field_type: 'textarea',
          placeholder: 'Identify areas where safety performance needs improvement...',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'action_plan',
          label: 'Action Plan',
          field_type: 'textarea',
          placeholder: 'What actions will be taken to address improvement areas?',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'resources_needed',
          label: 'Resources Needed',
          field_type: 'textarea',
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 7,
      fields: [
        {
          code: 'prepared_by_signature',
          label: 'Prepared By',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Review',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    sync_priority: 3,
    requires_approval: true,
  },
};
