/**
 * Trend Analysis Report
 * COR Element 12: Statistics & Records
 * 
 * Analyze safety trends over time.
 */

import type { FormConfig } from '../../import-forms';

export const trendAnalysisReport: FormConfig = {
  code: 'trend_analysis_report',
  name: 'Safety Trend Analysis Report',
  description: 'Analyze safety trends over time to identify patterns and inform strategic decisions.',
  cor_element: 12,
  frequency: 'quarterly',
  estimated_time_minutes: 40,
  icon: 'LineChart',
  color: '#8B5CF6',
  is_mandatory: false,

  sections: [
    {
      title: 'Report Information',
      order_index: 0,
      fields: [
        {
          code: 'report_date',
          label: 'Report Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'analyst',
          label: 'Prepared By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'analysis_period',
          label: 'Analysis Period',
          field_type: 'dropdown',
          options: [
            { value: '6_months', label: 'Last 6 Months' },
            { value: '12_months', label: 'Last 12 Months' },
            { value: '2_years', label: 'Last 2 Years' },
            { value: '3_years', label: 'Last 3 Years' },
            { value: 'custom', label: 'Custom Period' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'analysis_scope',
          label: 'Analysis Scope',
          field_type: 'dropdown',
          options: [
            { value: 'company_wide', label: 'Company-Wide' },
            { value: 'division', label: 'Division/Department' },
            { value: 'jobsite', label: 'Specific Jobsite' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Incident Trends',
      order_index: 1,
      fields: [
        {
          code: 'incident_trend',
          label: 'Overall Incident Trend',
          field_type: 'dropdown',
          options: [
            { value: 'significant_decrease', label: 'Significant Decrease (>20%)' },
            { value: 'moderate_decrease', label: 'Moderate Decrease (5-20%)' },
            { value: 'stable', label: 'Stable (within 5%)' },
            { value: 'moderate_increase', label: 'Moderate Increase (5-20%)' },
            { value: 'significant_increase', label: 'Significant Increase (>20%)' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'severity_trend',
          label: 'Incident Severity Trend',
          field_type: 'dropdown',
          options: [
            { value: 'improving', label: 'Improving (less severe)' },
            { value: 'stable', label: 'Stable' },
            { value: 'worsening', label: 'Worsening (more severe)' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'incident_trend_analysis',
          label: 'Incident Trend Analysis',
          field_type: 'textarea',
          placeholder: 'Analyze the incident trends, including any patterns observed...',
          validation_rules: { required: true, min_length: 100 },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'peak_incident_months',
          label: 'Peak Incident Periods',
          field_type: 'text',
          placeholder: 'e.g., June-August, Winter months',
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Injury Type Analysis',
      order_index: 2,
      fields: [
        {
          code: 'top_injury_types',
          label: 'Top 3 Injury Types',
          field_type: 'textarea',
          placeholder: '1.\n2.\n3.',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'injury_type_trends',
          label: 'Injury Type Trend Analysis',
          field_type: 'textarea',
          placeholder: 'Are certain injury types increasing or decreasing?',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'body_part_trends',
          label: 'Body Part Injury Trends',
          field_type: 'textarea',
          placeholder: 'Which body parts are most commonly injured? Any changes?',
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Root Cause Analysis Trends',
      order_index: 3,
      fields: [
        {
          code: 'top_root_causes',
          label: 'Most Common Root Causes',
          field_type: 'multiselect',
          options: [
            { value: 'training', label: 'Training Deficiency' },
            { value: 'procedure', label: 'Procedure Issues' },
            { value: 'equipment', label: 'Equipment/Tools' },
            { value: 'environment', label: 'Work Environment' },
            { value: 'communication', label: 'Communication' },
            { value: 'supervision', label: 'Supervision' },
            { value: 'ppe', label: 'PPE Issues' },
            { value: 'human_factors', label: 'Human Factors' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'root_cause_trends',
          label: 'Root Cause Trend Analysis',
          field_type: 'textarea',
          placeholder: 'Are root causes changing? Are interventions working?',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'recurring_issues',
          label: 'Recurring Issues',
          field_type: 'textarea',
          placeholder: 'Identify issues that keep recurring despite corrective actions...',
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Leading Indicator Trends',
      order_index: 4,
      fields: [
        {
          code: 'near_miss_trend',
          label: 'Near Miss Reporting Trend',
          field_type: 'dropdown',
          options: [
            { value: 'increasing', label: 'Increasing (positive)' },
            { value: 'stable', label: 'Stable' },
            { value: 'decreasing', label: 'Decreasing (concerning)' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'hazard_reporting_trend',
          label: 'Hazard Reporting Trend',
          field_type: 'dropdown',
          options: [
            { value: 'increasing', label: 'Increasing (positive)' },
            { value: 'stable', label: 'Stable' },
            { value: 'decreasing', label: 'Decreasing (concerning)' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'leading_indicator_analysis',
          label: 'Leading Indicator Analysis',
          field_type: 'textarea',
          placeholder: 'Analyze trends in proactive safety activities...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Department/Location Comparison',
      order_index: 5,
      fields: [
        {
          code: 'highest_risk_areas',
          label: 'Highest Risk Areas/Departments',
          field_type: 'textarea',
          placeholder: 'Which areas have the highest incident rates?',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'best_performing_areas',
          label: 'Best Performing Areas',
          field_type: 'textarea',
          placeholder: 'Which areas have the best safety performance?',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'variance_analysis',
          label: 'Performance Variance Analysis',
          field_type: 'textarea',
          placeholder: 'What explains the differences between high and low performers?',
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Conclusions & Recommendations',
      order_index: 6,
      fields: [
        {
          code: 'key_findings',
          label: 'Key Findings',
          field_type: 'textarea',
          placeholder: 'Summarize the key findings from this trend analysis...',
          validation_rules: { required: true, min_length: 100 },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'positive_trends',
          label: 'Positive Trends to Maintain',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'negative_trends',
          label: 'Negative Trends Requiring Action',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'recommendations',
          label: 'Strategic Recommendations',
          field_type: 'textarea',
          placeholder: 'What strategic changes are recommended based on trend analysis?',
          validation_rules: { required: true, min_length: 100 },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'resource_allocation',
          label: 'Resource Allocation Recommendations',
          field_type: 'textarea',
          placeholder: 'Where should safety resources be focused?',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 7,
      fields: [
        {
          code: 'analyst_signature',
          label: 'Analyst Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Review',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    sync_priority: 4,
    requires_approval: true,
  },
};
