/**
 * Change Notification Form
 * COR Element 4: Competency & Training
 * 
 * Document and communicate changes that may affect worker safety.
 */

import type { FormConfig } from '../../import-forms';

export const changeNotification: FormConfig = {
  code: 'change_notification',
  name: 'Change Notification Form',
  description: 'Document and communicate changes to processes, equipment, or procedures that may affect worker safety.',
  cor_element: 4,
  frequency: 'as_needed',
  estimated_time_minutes: 20,
  icon: 'RefreshCw',
  color: '#6366F1',
  is_mandatory: true,

  sections: [
    {
      title: 'Change Information',
      order_index: 0,
      fields: [
        {
          code: 'notification_date',
          label: 'Notification Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'change_reference',
          label: 'Change Reference Number',
          field_type: 'text',
          placeholder: 'CN-2025-001',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'initiated_by',
          label: 'Change Initiated By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'jobsite',
          label: 'Affected Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'change_type',
          label: 'Type of Change',
          field_type: 'multiselect',
          options: [
            { value: 'equipment', label: 'Equipment/Machinery' },
            { value: 'process', label: 'Work Process/Procedure' },
            { value: 'materials', label: 'Materials/Chemicals' },
            { value: 'personnel', label: 'Personnel/Roles' },
            { value: 'layout', label: 'Workplace Layout' },
            { value: 'schedule', label: 'Work Schedule' },
            { value: 'ppe', label: 'PPE Requirements' },
            { value: 'regulatory', label: 'Regulatory Requirements' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'change_description',
          label: 'Description of Change',
          field_type: 'textarea',
          placeholder: 'Describe the change in detail...',
          validation_rules: { required: true, min_length: 50 },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'reason_for_change',
          label: 'Reason for Change',
          field_type: 'textarea',
          placeholder: 'Why is this change being made?',
          validation_rules: { required: true },
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Safety Impact Assessment',
      order_index: 1,
      fields: [
        {
          code: 'new_hazards',
          label: 'Does this change introduce new hazards?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Possibly'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'new_hazards_description',
          label: 'Describe New Hazards',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'new_hazards',
            operator: 'not_equals',
            value: 'No',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'existing_controls_affected',
          label: 'Are existing controls affected?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'controls_affected_description',
          label: 'How are existing controls affected?',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'existing_controls_affected',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'risk_level',
          label: 'Risk Level of Change',
          field_type: 'dropdown',
          options: [
            { value: 'low', label: 'Low - Minimal safety impact' },
            { value: 'medium', label: 'Medium - Moderate safety impact' },
            { value: 'high', label: 'High - Significant safety impact' },
            { value: 'critical', label: 'Critical - Major safety impact' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'hazard_assessment_required',
          label: 'Is a new hazard assessment required?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Training Requirements',
      order_index: 2,
      fields: [
        {
          code: 'training_required',
          label: 'Is training required for this change?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'training_type',
          label: 'Type of Training Required',
          field_type: 'multiselect',
          options: [
            { value: 'toolbox_talk', label: 'Toolbox Talk' },
            { value: 'formal_training', label: 'Formal Training Session' },
            { value: 'hands_on', label: 'Hands-on Demonstration' },
            { value: 'sop_review', label: 'SOP Review' },
            { value: 'certification', label: 'Certification/Recertification' },
            { value: 'online', label: 'Online/E-Learning' },
          ],
          conditional_logic: {
            field_code: 'training_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'training_deadline',
          label: 'Training Completion Deadline',
          field_type: 'date',
          conditional_logic: {
            field_code: 'training_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'affected_workers',
          label: 'Workers Requiring Training',
          field_type: 'worker_select',
          help_text: 'Select all workers affected by this change',
          conditional_logic: {
            field_code: 'training_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Communication Plan',
      order_index: 3,
      fields: [
        {
          code: 'communication_methods',
          label: 'How will this change be communicated?',
          field_type: 'multiselect',
          options: [
            { value: 'safety_meeting', label: 'Safety Meeting' },
            { value: 'toolbox_talk', label: 'Toolbox Talk' },
            { value: 'email', label: 'Email' },
            { value: 'posted_notice', label: 'Posted Notice' },
            { value: 'one_on_one', label: 'One-on-One' },
            { value: 'training_session', label: 'Training Session' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'implementation_date',
          label: 'Change Implementation Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'communication_deadline',
          label: 'Communication Deadline',
          field_type: 'date',
          help_text: 'When must all workers be notified?',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'responsible_person',
          label: 'Person Responsible for Communication',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'additional_notes',
          label: 'Additional Notes',
          field_type: 'textarea',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Approval',
      order_index: 4,
      fields: [
        {
          code: 'initiator_signature',
          label: 'Initiator Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'safety_approval',
          label: 'Safety Approval',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'management_approval',
          label: 'Management Approval',
          field_type: 'signature',
          help_text: 'Required for high/critical risk changes',
          order_index: 2,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin', 'internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Complete Change Communication',
      priority: 'high',
      due_hours: 48,
    },
    sync_priority: 2,
    requires_approval: true,
  },
};
