/**
 * Contractor Pre-Qualification Form
 * COR Element 4: Competency & Training
 * 
 * Evaluate contractors before engaging them for work.
 */

import type { FormConfig } from '../../import-forms';

export const contractorPrequalification: FormConfig = {
  code: 'contractor_prequalification',
  name: 'Contractor Pre-Qualification',
  description: 'Evaluate contractor safety programs and qualifications before engaging them for work on company projects.',
  cor_element: 4,
  frequency: 'as_needed',
  estimated_time_minutes: 45,
  icon: 'UserCheck',
  color: '#F59E0B',
  is_mandatory: true,

  sections: [
    {
      title: 'Contractor Information',
      order_index: 0,
      fields: [
        {
          code: 'evaluation_date',
          label: 'Evaluation Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'evaluator',
          label: 'Evaluated By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'contractor_name',
          label: 'Contractor Company Name',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'contractor_contact',
          label: 'Primary Contact Person',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'contractor_phone',
          label: 'Contact Phone',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'contractor_email',
          label: 'Contact Email',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'work_type',
          label: 'Type of Work',
          field_type: 'multiselect',
          options: [
            { value: 'electrical', label: 'Electrical' },
            { value: 'plumbing', label: 'Plumbing' },
            { value: 'hvac', label: 'HVAC' },
            { value: 'structural', label: 'Structural' },
            { value: 'roofing', label: 'Roofing' },
            { value: 'excavation', label: 'Excavation' },
            { value: 'concrete', label: 'Concrete' },
            { value: 'painting', label: 'Painting' },
            { value: 'general_construction', label: 'General Construction' },
            { value: 'demolition', label: 'Demolition' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Safety Documentation',
      description: 'Verify contractor safety program documentation',
      order_index: 1,
      fields: [
        {
          code: 'has_safety_program',
          label: 'Does contractor have a written safety program?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'safety_program_reviewed',
          label: 'Has safety program been reviewed?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          conditional_logic: {
            field_code: 'has_safety_program',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'safety_program_adequate',
          label: 'Is safety program adequate?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Needs Improvement'],
          conditional_logic: {
            field_code: 'safety_program_reviewed',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'has_wcb_coverage',
          label: 'Valid WCB/WSIB coverage?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'wcb_account_number',
          label: 'WCB/WSIB Account Number',
          field_type: 'text',
          conditional_logic: {
            field_code: 'has_wcb_coverage',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'has_liability_insurance',
          label: 'General liability insurance?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'liability_amount',
          label: 'Liability Coverage Amount',
          field_type: 'dropdown',
          options: [
            { value: 'under_1m', label: 'Under $1M' },
            { value: '1m_2m', label: '$1M - $2M' },
            { value: '2m_5m', label: '$2M - $5M' },
            { value: 'over_5m', label: 'Over $5M' },
          ],
          conditional_logic: {
            field_code: 'has_liability_insurance',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'has_cor_certification',
          label: 'COR Certified?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          order_index: 7,
          width: 'half',
        },
        {
          code: 'cor_cert_number',
          label: 'COR Certificate Number',
          field_type: 'text',
          conditional_logic: {
            field_code: 'has_cor_certification',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 8,
          width: 'half',
        },
      ],
    },
    {
      title: 'Safety Performance',
      description: 'Review contractor safety performance history',
      order_index: 2,
      fields: [
        {
          code: 'emr_rating',
          label: 'Experience Modification Rate (EMR)',
          field_type: 'number',
          help_text: 'Enter EMR value (e.g., 0.85 = 85%)',
          validation_rules: { min_value: 0, max_value: 3 },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'trir',
          label: 'Total Recordable Incident Rate (TRIR)',
          field_type: 'number',
          help_text: 'Enter TRIR value',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'fatalities_3_years',
          label: 'Fatalities in past 3 years',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'serious_incidents_3_years',
          label: 'Serious incidents in past 3 years',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'regulatory_violations',
          label: 'Any regulatory violations in past 3 years?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'violation_details',
          label: 'Violation Details',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'regulatory_violations',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Training & Competency',
      description: 'Verify contractor worker training',
      order_index: 3,
      fields: [
        {
          code: 'workers_trained',
          label: 'Are all workers trained for assigned tasks?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'safety_orientation',
          label: 'Does contractor provide safety orientation?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'toolbox_talks',
          label: 'Does contractor conduct toolbox talks?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'certifications_verified',
          label: 'Worker certifications verified?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partial'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'training_records_available',
          label: 'Training records available upon request?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Evaluation Summary',
      order_index: 4,
      fields: [
        {
          code: 'overall_rating',
          label: 'Overall Safety Rating',
          field_type: 'dropdown',
          options: [
            { value: 'excellent', label: 'Excellent - Exceeds requirements' },
            { value: 'good', label: 'Good - Meets all requirements' },
            { value: 'acceptable', label: 'Acceptable - Meets minimum requirements' },
            { value: 'poor', label: 'Poor - Does not meet requirements' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'recommendation',
          label: 'Recommendation',
          field_type: 'dropdown',
          options: [
            { value: 'approved', label: 'Approved - No conditions' },
            { value: 'approved_conditions', label: 'Approved with Conditions' },
            { value: 'probationary', label: 'Probationary Approval' },
            { value: 'not_approved', label: 'Not Approved' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'conditions',
          label: 'Conditions/Requirements',
          field_type: 'textarea',
          placeholder: 'List any conditions or requirements for approval...',
          conditional_logic: {
            field_code: 'recommendation',
            operator: 'not_equals',
            value: 'approved',
          },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'areas_of_concern',
          label: 'Areas of Concern',
          field_type: 'textarea',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'reevaluation_date',
          label: 'Re-evaluation Date',
          field_type: 'date',
          help_text: 'When should this contractor be re-evaluated?',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'evaluator_signature',
          label: 'Evaluator Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'manager_signature',
          label: 'Manager Approval',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['supervisor', 'internal_auditor'],
    sync_priority: 3,
    requires_approval: true,
  },
};
