/**
 * Joint Health & Safety Inspection
 * COR Element 9: Workplace Inspections
 * 
 * Formal inspection conducted by JHSC members.
 */

import type { FormConfig } from '../../import-forms';

export const jointHealthSafetyInspection: FormConfig = {
  code: 'joint_health_safety_inspection',
  name: 'Joint Health & Safety Committee Inspection',
  description: 'Formal workplace inspection conducted by Joint Health & Safety Committee (JHSC) members.',
  cor_element: 9,
  frequency: 'monthly',
  estimated_time_minutes: 45,
  icon: 'Users',
  color: '#3B82F6',
  is_mandatory: true,

  sections: [
    {
      title: 'Inspection Details',
      order_index: 0,
      fields: [
        {
          code: 'inspection_date',
          label: 'Inspection Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'inspection_time',
          label: 'Start Time',
          field_type: 'time',
          default_value: 'now',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'areas_inspected',
          label: 'Areas Inspected',
          field_type: 'textarea',
          placeholder: 'List all areas/departments inspected...',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'worker_rep',
          label: 'Worker Representative',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'management_rep',
          label: 'Management Representative',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'additional_inspectors',
          label: 'Additional Inspectors',
          field_type: 'worker_select',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'General Workplace Conditions',
      order_index: 1,
      fields: [
        {
          code: 'housekeeping',
          label: 'Housekeeping/Cleanliness',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'housekeeping_notes',
          label: 'Housekeeping Notes',
          field_type: 'text',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'walkways_clear',
          label: 'Walkways/Aisles Clear',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'walkways_notes',
          label: 'Walkways Notes',
          field_type: 'text',
          order_index: 3,
          width: 'half',
        },
        {
          code: 'lighting',
          label: 'Lighting Adequate',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'lighting_notes',
          label: 'Lighting Notes',
          field_type: 'text',
          order_index: 5,
          width: 'half',
        },
        {
          code: 'ventilation',
          label: 'Ventilation',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory', 'N/A'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'ventilation_notes',
          label: 'Ventilation Notes',
          field_type: 'text',
          order_index: 7,
          width: 'half',
        },
        {
          code: 'noise_levels',
          label: 'Noise Levels',
          field_type: 'radio',
          options: ['Acceptable', 'Elevated', 'Excessive', 'N/A'],
          validation_rules: { required: true },
          order_index: 8,
          width: 'half',
        },
        {
          code: 'noise_notes',
          label: 'Noise Notes',
          field_type: 'text',
          order_index: 9,
          width: 'half',
        },
      ],
    },
    {
      title: 'Safety Equipment & Signage',
      order_index: 2,
      fields: [
        {
          code: 'fire_extinguishers',
          label: 'Fire Extinguishers Accessible/Inspected',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'fire_ext_notes',
          label: 'Fire Extinguisher Notes',
          field_type: 'text',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'first_aid_kits',
          label: 'First Aid Kits Stocked/Accessible',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'first_aid_notes',
          label: 'First Aid Notes',
          field_type: 'text',
          order_index: 3,
          width: 'half',
        },
        {
          code: 'emergency_exits',
          label: 'Emergency Exits Clear/Marked',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'exit_notes',
          label: 'Emergency Exit Notes',
          field_type: 'text',
          order_index: 5,
          width: 'half',
        },
        {
          code: 'safety_signage',
          label: 'Safety Signage Visible/Current',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'signage_notes',
          label: 'Signage Notes',
          field_type: 'text',
          order_index: 7,
          width: 'half',
        },
        {
          code: 'eyewash_stations',
          label: 'Eye Wash Stations (if applicable)',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory', 'N/A'],
          order_index: 8,
          width: 'half',
        },
        {
          code: 'eyewash_notes',
          label: 'Eye Wash Notes',
          field_type: 'text',
          order_index: 9,
          width: 'half',
        },
      ],
    },
    {
      title: 'PPE & Worker Practices',
      order_index: 3,
      fields: [
        {
          code: 'ppe_usage',
          label: 'PPE Being Used Correctly',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'ppe_notes',
          label: 'PPE Notes',
          field_type: 'text',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'ppe_condition',
          label: 'PPE in Good Condition',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'ppe_condition_notes',
          label: 'PPE Condition Notes',
          field_type: 'text',
          order_index: 3,
          width: 'half',
        },
        {
          code: 'safe_work_practices',
          label: 'Safe Work Practices Observed',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'practice_notes',
          label: 'Work Practice Notes',
          field_type: 'text',
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Equipment & Machinery',
      order_index: 4,
      fields: [
        {
          code: 'machine_guarding',
          label: 'Machine Guarding in Place',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'guarding_notes',
          label: 'Guarding Notes',
          field_type: 'text',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'lockout_tagout',
          label: 'Lockout/Tagout Procedures Followed',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory', 'N/A'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'loto_notes',
          label: 'LOTO Notes',
          field_type: 'text',
          order_index: 3,
          width: 'half',
        },
        {
          code: 'equipment_condition',
          label: 'Equipment Condition',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'equipment_notes',
          label: 'Equipment Notes',
          field_type: 'text',
          order_index: 5,
          width: 'half',
        },
        {
          code: 'tools_condition',
          label: 'Hand/Power Tools Condition',
          field_type: 'radio',
          options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory', 'N/A'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'tools_notes',
          label: 'Tools Notes',
          field_type: 'text',
          order_index: 7,
          width: 'half',
        },
      ],
    },
    {
      title: 'Hazards Identified',
      description: 'Document all hazards identified during the inspection',
      order_index: 5,
      is_repeatable: true,
      fields: [
        {
          code: 'hazard_location',
          label: 'Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'hazard_description',
          label: 'Hazard Description',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'hazard_priority',
          label: 'Priority',
          field_type: 'dropdown',
          options: [
            { value: 'immediate', label: 'Immediate - Stop work' },
            { value: 'high', label: 'High - 24 hours' },
            { value: 'medium', label: 'Medium - 7 days' },
            { value: 'low', label: 'Low - 30 days' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'recommended_action',
          label: 'Recommended Corrective Action',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'responsible_person',
          label: 'Assigned To',
          field_type: 'worker_select',
          order_index: 4,
          width: 'half',
        },
        {
          code: 'target_date',
          label: 'Target Completion Date',
          field_type: 'date',
          order_index: 5,
          width: 'half',
        },
        {
          code: 'hazard_photo',
          label: 'Photo',
          field_type: 'photo',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Summary',
      order_index: 6,
      fields: [
        {
          code: 'total_hazards',
          label: 'Total Hazards Identified',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'immediate_hazards',
          label: 'Immediate Priority',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'high_hazards',
          label: 'High Priority',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'previous_items_reviewed',
          label: 'Previous Items Reviewed',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'overall_assessment',
          label: 'Overall Workplace Assessment',
          field_type: 'dropdown',
          options: [
            { value: 'excellent', label: 'Excellent - No significant issues' },
            { value: 'good', label: 'Good - Minor issues only' },
            { value: 'satisfactory', label: 'Satisfactory - Some issues to address' },
            { value: 'needs_improvement', label: 'Needs Improvement - Multiple issues' },
            { value: 'unsatisfactory', label: 'Unsatisfactory - Significant concerns' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'positive_observations',
          label: 'Positive Observations',
          field_type: 'textarea',
          placeholder: 'Note any positive safety practices or improvements observed...',
          order_index: 5,
          width: 'full',
        },
        {
          code: 'general_recommendations',
          label: 'General Recommendations',
          field_type: 'textarea',
          order_index: 6,
          width: 'full',
        },
        {
          code: 'next_inspection_date',
          label: 'Next Inspection Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 7,
      fields: [
        {
          code: 'worker_rep_signature',
          label: 'Worker Representative Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_rep_signature',
          label: 'Management Representative Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['supervisor', 'internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Review JHSC Inspection Findings',
      priority: 'high',
      due_hours: 48,
    },
    sync_priority: 2,
    requires_approval: false,
  },
};
