/**
 * Corrective Action Log
 * COR Element 10: Incident Investigation
 * 
 * Track corrective actions from incident investigations.
 */

import type { FormConfig } from '../../import-forms';

export const correctiveActionLog: FormConfig = {
  code: 'corrective_action_log',
  name: 'Corrective Action Log',
  description: 'Track the status and completion of corrective actions from incident investigations.',
  cor_element: 10,
  frequency: 'weekly',
  estimated_time_minutes: 15,
  icon: 'ListChecks',
  color: '#F59E0B',
  is_mandatory: true,

  sections: [
    {
      title: 'Review Information',
      order_index: 0,
      fields: [
        {
          code: 'review_date',
          label: 'Review Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'reviewer',
          label: 'Reviewed By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'review_period',
          label: 'Review Period',
          field_type: 'dropdown',
          options: [
            { value: 'weekly', label: 'Weekly' },
            { value: 'bi_weekly', label: 'Bi-Weekly' },
            { value: 'monthly', label: 'Monthly' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
      ],
    },
    {
      title: 'Corrective Action Status',
      description: 'Update status of outstanding corrective actions',
      order_index: 1,
      is_repeatable: true,
      fields: [
        {
          code: 'action_reference',
          label: 'Action Reference',
          field_type: 'text',
          placeholder: 'CA-2025-001',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'source',
          label: 'Source',
          field_type: 'dropdown',
          options: [
            { value: 'incident', label: 'Incident Investigation' },
            { value: 'inspection', label: 'Inspection' },
            { value: 'audit', label: 'Audit' },
            { value: 'hazard_report', label: 'Hazard Report' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'source_reference',
          label: 'Source Reference Number',
          field_type: 'text',
          placeholder: 'INV-2025-001',
          order_index: 2,
          width: 'half',
        },
        {
          code: 'action_description',
          label: 'Action Description',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'responsible_person',
          label: 'Responsible Person',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'original_due_date',
          label: 'Original Due Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'current_status',
          label: 'Current Status',
          field_type: 'dropdown',
          options: [
            { value: 'not_started', label: 'Not Started' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'on_hold', label: 'On Hold' },
            { value: 'completed', label: 'Completed' },
            { value: 'verified', label: 'Completed & Verified' },
            { value: 'overdue', label: 'Overdue' },
          ],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'percent_complete',
          label: 'Percent Complete',
          field_type: 'dropdown',
          options: [
            { value: '0', label: '0%' },
            { value: '25', label: '25%' },
            { value: '50', label: '50%' },
            { value: '75', label: '75%' },
            { value: '100', label: '100%' },
          ],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
        {
          code: 'revised_due_date',
          label: 'Revised Due Date (if applicable)',
          field_type: 'date',
          order_index: 8,
          width: 'half',
        },
        {
          code: 'completion_date',
          label: 'Actual Completion Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'current_status',
            operator: 'contains',
            value: 'completed',
          },
          order_index: 9,
          width: 'half',
        },
        {
          code: 'status_notes',
          label: 'Status Notes',
          field_type: 'textarea',
          placeholder: 'Provide update on progress or reason for delay...',
          order_index: 10,
          width: 'full',
        },
        {
          code: 'verification_completed',
          label: 'Effectiveness Verified?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Pending'],
          conditional_logic: {
            field_code: 'current_status',
            operator: 'contains',
            value: 'completed',
          },
          order_index: 11,
          width: 'half',
        },
      ],
    },
    {
      title: 'Summary',
      order_index: 2,
      fields: [
        {
          code: 'total_actions',
          label: 'Total Actions Tracked',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'completed_actions',
          label: 'Completed',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'in_progress_actions',
          label: 'In Progress',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'overdue_actions',
          label: 'Overdue',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'escalation_required',
          label: 'Are any items requiring escalation?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'escalation_details',
          label: 'Escalation Details',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'escalation_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'general_comments',
          label: 'General Comments',
          field_type: 'textarea',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 3,
      fields: [
        {
          code: 'reviewer_signature',
          label: 'Reviewer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
