/**
 * Incident Investigation Form
 * COR Element 10: Incident Investigation
 * 
 * Formal investigation of workplace incidents.
 */

import type { FormConfig } from '../../import-forms';

export const incidentInvestigation: FormConfig = {
  code: 'incident_investigation',
  name: 'Incident Investigation Form',
  description: 'Formal investigation of workplace incidents to determine root causes and prevent recurrence.',
  cor_element: 10,
  frequency: 'as_needed',
  estimated_time_minutes: 45,
  icon: 'Search',
  color: '#DC2626',
  is_mandatory: true,

  sections: [
    {
      title: 'Investigation Details',
      order_index: 0,
      fields: [
        {
          code: 'investigation_date',
          label: 'Investigation Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'investigation_number',
          label: 'Investigation Number',
          field_type: 'text',
          placeholder: 'INV-2025-001',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'incident_report_ref',
          label: 'Incident Report Reference',
          field_type: 'text',
          placeholder: 'IR-2025-001',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'lead_investigator',
          label: 'Lead Investigator',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'investigation_team',
          label: 'Investigation Team Members',
          field_type: 'worker_select',
          help_text: 'Select all team members involved in investigation',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Incident Summary',
      order_index: 1,
      fields: [
        {
          code: 'incident_date',
          label: 'Date of Incident',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'incident_time',
          label: 'Time of Incident',
          field_type: 'time',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'specific_location',
          label: 'Specific Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'incident_type',
          label: 'Incident Type',
          field_type: 'dropdown',
          options: [
            { value: 'injury', label: 'Injury/Illness' },
            { value: 'near_miss', label: 'Near Miss' },
            { value: 'property_damage', label: 'Property Damage' },
            { value: 'environmental', label: 'Environmental' },
            { value: 'vehicle', label: 'Vehicle Incident' },
            { value: 'fire', label: 'Fire/Explosion' },
            { value: 'security', label: 'Security' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'severity',
          label: 'Incident Severity',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Fatality/Permanent disability' },
            { value: 'serious', label: 'Serious - Lost time injury' },
            { value: 'moderate', label: 'Moderate - Medical treatment' },
            { value: 'minor', label: 'Minor - First aid' },
            { value: 'near_miss', label: 'Near Miss - No injury' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'injured_workers',
          label: 'Injured/Affected Workers',
          field_type: 'worker_select',
          order_index: 6,
          width: 'full',
        },
        {
          code: 'incident_description',
          label: 'Incident Description',
          field_type: 'textarea',
          placeholder: 'Describe what happened in detail...',
          validation_rules: { required: true, min_length: 100 },
          order_index: 7,
          width: 'full',
        },
      ],
    },
    {
      title: 'Evidence Gathered',
      order_index: 2,
      fields: [
        {
          code: 'witnesses_interviewed',
          label: 'Witnesses Interviewed',
          field_type: 'worker_select',
          order_index: 0,
          width: 'full',
        },
        {
          code: 'witness_statements_obtained',
          label: 'Written witness statements obtained?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Pending'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'photos_taken',
          label: 'Photos/Videos taken?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'site_preserved',
          label: 'Was incident site preserved?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'documents_reviewed',
          label: 'Documents Reviewed',
          field_type: 'multiselect',
          options: [
            { value: 'sop', label: 'SOPs/Procedures' },
            { value: 'training_records', label: 'Training Records' },
            { value: 'maintenance_logs', label: 'Maintenance Logs' },
            { value: 'inspection_reports', label: 'Inspection Reports' },
            { value: 'jha', label: 'JHA/Risk Assessments' },
            { value: 'previous_incidents', label: 'Previous Incident Reports' },
            { value: 'equipment_manuals', label: 'Equipment Manuals' },
            { value: 'other', label: 'Other' },
          ],
          order_index: 4,
          width: 'full',
        },
        {
          code: 'physical_evidence',
          label: 'Physical Evidence Collected',
          field_type: 'textarea',
          placeholder: 'Describe any physical evidence collected...',
          order_index: 5,
          width: 'full',
        },
        {
          code: 'investigation_photos',
          label: 'Investigation Photos',
          field_type: 'photo',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Root Cause Analysis',
      description: 'Identify the underlying causes of the incident',
      order_index: 3,
      fields: [
        {
          code: 'immediate_cause',
          label: 'Immediate Cause(s)',
          field_type: 'textarea',
          placeholder: 'What was the direct cause of the incident?',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'contributing_factors',
          label: 'Contributing Factors',
          field_type: 'multiselect',
          options: [
            { value: 'inadequate_training', label: 'Inadequate Training' },
            { value: 'improper_ppe', label: 'Improper/Missing PPE' },
            { value: 'equipment_failure', label: 'Equipment Failure' },
            { value: 'procedure_violation', label: 'Procedure Violation' },
            { value: 'no_procedure', label: 'No Procedure Existed' },
            { value: 'inadequate_supervision', label: 'Inadequate Supervision' },
            { value: 'communication_failure', label: 'Communication Failure' },
            { value: 'environmental_conditions', label: 'Environmental Conditions' },
            { value: 'fatigue', label: 'Fatigue' },
            { value: 'rushing', label: 'Rushing/Time Pressure' },
            { value: 'inadequate_maintenance', label: 'Inadequate Maintenance' },
            { value: 'design_deficiency', label: 'Design Deficiency' },
            { value: 'complacency', label: 'Complacency' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'contributing_factors_details',
          label: 'Contributing Factors Details',
          field_type: 'textarea',
          placeholder: 'Explain how each contributing factor played a role...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'root_cause_method',
          label: 'Root Cause Analysis Method Used',
          field_type: 'dropdown',
          options: [
            { value: '5_why', label: '5 Whys' },
            { value: 'fishbone', label: 'Fishbone/Ishikawa' },
            { value: 'fault_tree', label: 'Fault Tree Analysis' },
            { value: 'barrier_analysis', label: 'Barrier Analysis' },
            { value: 'taproot', label: 'TapRooT' },
            { value: 'other', label: 'Other' },
          ],
          order_index: 3,
          width: 'half',
        },
        {
          code: 'root_causes',
          label: 'Root Cause(s) Identified',
          field_type: 'textarea',
          placeholder: 'What are the underlying root causes?',
          validation_rules: { required: true, min_length: 50 },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Corrective Actions',
      description: 'Actions to prevent recurrence',
      order_index: 4,
      is_repeatable: true,
      fields: [
        {
          code: 'action_description',
          label: 'Corrective Action',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'action_type',
          label: 'Action Type',
          field_type: 'dropdown',
          options: [
            { value: 'elimination', label: 'Elimination' },
            { value: 'substitution', label: 'Substitution' },
            { value: 'engineering', label: 'Engineering Control' },
            { value: 'administrative', label: 'Administrative Control' },
            { value: 'ppe', label: 'PPE' },
            { value: 'training', label: 'Training' },
            { value: 'procedure', label: 'Procedure Change' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'responsible_person',
          label: 'Responsible Person',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'target_date',
          label: 'Target Completion Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'action_priority',
          label: 'Priority',
          field_type: 'dropdown',
          options: [
            { value: 'immediate', label: 'Immediate' },
            { value: 'high', label: 'High' },
            { value: 'medium', label: 'Medium' },
            { value: 'low', label: 'Low' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Communication & Sharing',
      order_index: 5,
      fields: [
        {
          code: 'lessons_learned',
          label: 'Lessons Learned',
          field_type: 'textarea',
          placeholder: 'What lessons can be learned from this incident?',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'similar_risks',
          label: 'Are similar risks present at other locations?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Unknown'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'communication_plan',
          label: 'Communication Plan',
          field_type: 'multiselect',
          options: [
            { value: 'safety_meeting', label: 'Safety Meeting/Toolbox Talk' },
            { value: 'safety_alert', label: 'Safety Alert/Bulletin' },
            { value: 'training', label: 'Training Session' },
            { value: 'all_sites', label: 'Share with All Sites' },
            { value: 'jhsc', label: 'JHSC Meeting' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'regulatory_report_required',
          label: 'Regulatory Report Required?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'regulatory_report_submitted',
          label: 'Regulatory Report Submitted?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          conditional_logic: {
            field_code: 'regulatory_report_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Investigation Conclusions',
      order_index: 6,
      fields: [
        {
          code: 'investigation_findings',
          label: 'Investigation Findings Summary',
          field_type: 'textarea',
          validation_rules: { required: true, min_length: 100 },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'preventable',
          label: 'Was this incident preventable?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'investigation_complete',
          label: 'Investigation Status',
          field_type: 'dropdown',
          options: [
            { value: 'complete', label: 'Complete' },
            { value: 'pending_actions', label: 'Complete - Pending Actions' },
            { value: 'ongoing', label: 'Ongoing - Additional Info Needed' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'follow_up_date',
          label: 'Follow-up Review Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 7,
      fields: [
        {
          code: 'investigator_signature',
          label: 'Lead Investigator Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'supervisor_signature',
          label: 'Supervisor Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'safety_manager_signature',
          label: 'Safety Manager Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Signature',
          field_type: 'signature',
          help_text: 'Required for serious/critical incidents',
          order_index: 3,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['supervisor', 'internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Review Incident Investigation',
      priority: 'high',
      due_hours: 24,
    },
    sync_priority: 1,
    requires_approval: true,
  },
};
