/**
 * Post-Incident Training Record
 * COR Element 10: Incident Investigation
 * 
 * Document training conducted following an incident.
 */

import type { FormConfig } from '../../import-forms';

export const postIncidentTrainingRecord: FormConfig = {
  code: 'post_incident_training_record',
  name: 'Post-Incident Training Record',
  description: 'Document training conducted following an incident to prevent recurrence and share lessons learned.',
  cor_element: 10,
  frequency: 'as_needed',
  estimated_time_minutes: 15,
  icon: 'BookOpen',
  color: '#8B5CF6',
  is_mandatory: true,

  sections: [
    {
      title: 'Training Details',
      order_index: 0,
      fields: [
        {
          code: 'training_date',
          label: 'Training Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'training_time',
          label: 'Training Time',
          field_type: 'time',
          default_value: 'now',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'trainer',
          label: 'Trainer/Presenter',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'incident_reference',
          label: 'Incident Reference',
          field_type: 'text',
          placeholder: 'IR-2025-001 or INV-2025-001',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Training Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'training_format',
          label: 'Training Format',
          field_type: 'dropdown',
          options: [
            { value: 'toolbox_talk', label: 'Toolbox Talk' },
            { value: 'safety_meeting', label: 'Safety Meeting' },
            { value: 'classroom', label: 'Classroom Training' },
            { value: 'hands_on', label: 'Hands-On Demonstration' },
            { value: 'online', label: 'Online/E-Learning' },
            { value: 'one_on_one', label: 'One-on-One' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'duration_minutes',
          label: 'Duration (minutes)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 5 },
          order_index: 6,
          width: 'half',
        },
      ],
    },
    {
      title: 'Incident Overview',
      description: 'Summary of the incident discussed',
      order_index: 1,
      fields: [
        {
          code: 'incident_date',
          label: 'Incident Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'incident_type',
          label: 'Incident Type',
          field_type: 'dropdown',
          options: [
            { value: 'injury', label: 'Injury/Illness' },
            { value: 'near_miss', label: 'Near Miss' },
            { value: 'property_damage', label: 'Property Damage' },
            { value: 'environmental', label: 'Environmental' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'incident_summary',
          label: 'Incident Summary (for training purposes)',
          field_type: 'textarea',
          placeholder: 'Summarize the incident for training discussion...',
          help_text: 'Do not include identifying information about injured workers',
          validation_rules: { required: true, min_length: 50 },
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Training Content',
      order_index: 2,
      fields: [
        {
          code: 'root_causes_discussed',
          label: 'Root Causes Discussed',
          field_type: 'textarea',
          placeholder: 'What root causes were discussed?',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'lessons_learned',
          label: 'Lessons Learned',
          field_type: 'textarea',
          placeholder: 'What lessons were shared with workers?',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'corrective_actions_explained',
          label: 'Corrective Actions Explained',
          field_type: 'textarea',
          placeholder: 'What corrective actions were explained?',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'prevention_measures',
          label: 'Prevention Measures Discussed',
          field_type: 'textarea',
          placeholder: 'What can workers do to prevent similar incidents?',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'procedures_reviewed',
          label: 'Were any procedures reviewed or updated?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'procedures_list',
          label: 'List Procedures Reviewed',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'procedures_reviewed',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Attendance',
      order_index: 3,
      fields: [
        {
          code: 'attendees',
          label: 'Attendees',
          field_type: 'worker_select',
          help_text: 'Select all workers who attended this training',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'attendee_count',
          label: 'Total Attendee Count',
          field_type: 'number',
          validation_rules: { required: true, min_value: 1 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'target_audience_covered',
          label: 'Was the target audience covered?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'follow_up_training_needed',
          label: 'Is follow-up training needed for others?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Worker Feedback',
      order_index: 4,
      fields: [
        {
          code: 'questions_asked',
          label: 'Questions/Concerns Raised',
          field_type: 'textarea',
          placeholder: 'Document any questions or concerns raised by workers...',
          order_index: 0,
          width: 'full',
        },
        {
          code: 'worker_suggestions',
          label: 'Worker Suggestions',
          field_type: 'textarea',
          placeholder: 'Any suggestions from workers for preventing similar incidents?',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'understanding_confirmed',
          label: 'Worker understanding confirmed?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'trainer_signature',
          label: 'Trainer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
