/**
 * Corrective Action Form
 * COR Element 7: Maintenance
 * 
 * Document corrective actions for equipment deficiencies.
 */

import type { FormConfig } from '../../import-forms';

export const correctiveActionForm: FormConfig = {
  code: 'corrective_action_form',
  name: 'Corrective Action Form',
  description: 'Document corrective actions taken to address equipment deficiencies, safety hazards, or maintenance issues.',
  cor_element: 7,
  frequency: 'as_needed',
  estimated_time_minutes: 15,
  icon: 'CheckCircle',
  color: '#22C55E',
  is_mandatory: true,

  sections: [
    {
      title: 'Issue Identification',
      order_index: 0,
      fields: [
        {
          code: 'identification_date',
          label: 'Date Issue Identified',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'reported_by',
          label: 'Reported By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'car_number',
          label: 'CAR Number',
          field_type: 'text',
          placeholder: 'CAR-2025-001',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'source',
          label: 'Source of Issue',
          field_type: 'dropdown',
          options: [
            { value: 'inspection', label: 'Inspection Finding' },
            { value: 'incident', label: 'Incident/Near Miss' },
            { value: 'worker_report', label: 'Worker Report' },
            { value: 'audit', label: 'Audit Finding' },
            { value: 'maintenance', label: 'Maintenance Discovery' },
            { value: 'regulatory', label: 'Regulatory Requirement' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'issue_category',
          label: 'Issue Category',
          field_type: 'dropdown',
          options: [
            { value: 'equipment', label: 'Equipment/Machinery' },
            { value: 'facility', label: 'Facility/Infrastructure' },
            { value: 'process', label: 'Process/Procedure' },
            { value: 'training', label: 'Training/Competency' },
            { value: 'ppe', label: 'PPE' },
            { value: 'environmental', label: 'Environmental' },
            { value: 'documentation', label: 'Documentation' },
          ],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'priority',
          label: 'Priority',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Immediate action required' },
            { value: 'high', label: 'High - Within 24 hours' },
            { value: 'medium', label: 'Medium - Within 7 days' },
            { value: 'low', label: 'Low - Within 30 days' },
          ],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
      ],
    },
    {
      title: 'Issue Description',
      order_index: 1,
      fields: [
        {
          code: 'issue_description',
          label: 'Description of Issue',
          field_type: 'textarea',
          placeholder: 'Describe the issue in detail...',
          validation_rules: { required: true, min_length: 50 },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'equipment_involved',
          label: 'Equipment Involved (if applicable)',
          field_type: 'text',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'root_cause',
          label: 'Root Cause Analysis',
          field_type: 'textarea',
          placeholder: 'What is the underlying cause of this issue?',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'risk_if_uncorrected',
          label: 'Risk if Not Corrected',
          field_type: 'textarea',
          placeholder: 'What could happen if this issue is not addressed?',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'photos',
          label: 'Photos of Issue',
          field_type: 'photo',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Immediate Actions',
      description: 'Actions taken immediately to address the issue',
      order_index: 2,
      fields: [
        {
          code: 'immediate_actions_taken',
          label: 'Were immediate actions taken?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'immediate_actions_description',
          label: 'Describe Immediate Actions',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'immediate_actions_taken',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'equipment_tagged_out',
          label: 'Was equipment tagged out/locked out?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'area_secured',
          label: 'Was area secured/restricted?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Corrective Action Plan',
      order_index: 3,
      fields: [
        {
          code: 'corrective_action',
          label: 'Corrective Action Required',
          field_type: 'textarea',
          placeholder: 'Describe the corrective action to permanently resolve this issue...',
          validation_rules: { required: true, min_length: 50 },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'responsible_person',
          label: 'Person Responsible',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'target_completion',
          label: 'Target Completion Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'resources_required',
          label: 'Resources Required',
          field_type: 'textarea',
          placeholder: 'List any parts, equipment, training, or other resources needed...',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'estimated_cost',
          label: 'Estimated Cost',
          field_type: 'text',
          placeholder: '$0.00',
          order_index: 4,
          width: 'half',
        },
        {
          code: 'preventive_measures',
          label: 'Preventive Measures',
          field_type: 'textarea',
          placeholder: 'What measures will prevent this issue from recurring?',
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Completion & Verification',
      order_index: 4,
      fields: [
        {
          code: 'action_status',
          label: 'Action Status',
          field_type: 'dropdown',
          options: [
            { value: 'open', label: 'Open - Not Started' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'completed', label: 'Completed' },
            { value: 'verified', label: 'Completed & Verified' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'actual_completion_date',
          label: 'Actual Completion Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'action_status',
            operator: 'not_equals',
            value: 'open',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'completion_notes',
          label: 'Completion Notes',
          field_type: 'textarea',
          placeholder: 'Describe what was done to complete the corrective action...',
          conditional_logic: {
            field_code: 'action_status',
            operator: 'not_equals',
            value: 'open',
          },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'verified_by',
          label: 'Verified By',
          field_type: 'worker_select',
          conditional_logic: {
            field_code: 'action_status',
            operator: 'equals',
            value: 'verified',
          },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'verification_date',
          label: 'Verification Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'action_status',
            operator: 'equals',
            value: 'verified',
          },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'photos_after',
          label: 'Photos After Completion',
          field_type: 'photo',
          conditional_logic: {
            field_code: 'action_status',
            operator: 'not_equals',
            value: 'open',
          },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'initiator_signature',
          label: 'Initiator Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'supervisor_signature',
          label: 'Supervisor Approval',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin', 'internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Complete Corrective Action',
      priority: 'high',
      due_hours: 168,
    },
    sync_priority: 2,
    requires_approval: true,
  },
};
