/**
 * Control Implementation Form
 * COR Element 3: Hazard Control
 * 
 * Document the implementation of hazard controls following a risk assessment.
 */

import type { FormConfig } from '../../import-forms';

export const controlImplementation: FormConfig = {
  code: 'control_implementation',
  name: 'Control Implementation Form',
  description: 'Document the implementation of hazard controls following a risk assessment, including the hierarchy of controls applied.',
  cor_element: 3,
  frequency: 'as_needed',
  estimated_time_minutes: 20,
  icon: 'Shield',
  color: '#10B981',
  is_mandatory: true,

  sections: [
    {
      title: 'Hazard Information',
      order_index: 0,
      fields: [
        {
          code: 'implementation_date',
          label: 'Implementation Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'hazard_assessment_ref',
          label: 'Hazard Assessment Reference',
          field_type: 'text',
          placeholder: 'HA-2025-001',
          help_text: 'Reference number of the related hazard assessment',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'hazard_description',
          label: 'Hazard Description',
          field_type: 'textarea',
          placeholder: 'Describe the hazard that requires control...',
          validation_rules: { required: true, min_length: 20 },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'risk_level',
          label: 'Initial Risk Level',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Immediate danger' },
            { value: 'high', label: 'High - Significant risk' },
            { value: 'medium', label: 'Medium - Moderate risk' },
            { value: 'low', label: 'Low - Minor risk' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'affected_workers',
          label: 'Workers Potentially Affected',
          field_type: 'worker_select',
          help_text: 'Select all workers who may be exposed to this hazard',
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'Hierarchy of Controls Applied',
      description: 'Document which controls from the hierarchy have been implemented',
      order_index: 1,
      fields: [
        {
          code: 'elimination_applied',
          label: '1. Elimination - Can the hazard be eliminated?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'elimination_details',
          label: 'Elimination Details',
          field_type: 'textarea',
          placeholder: 'Describe how the hazard was/will be eliminated...',
          conditional_logic: {
            field_code: 'elimination_applied',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'substitution_applied',
          label: '2. Substitution - Can a less hazardous alternative be used?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially', 'N/A'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'substitution_details',
          label: 'Substitution Details',
          field_type: 'textarea',
          placeholder: 'Describe the substitution made...',
          conditional_logic: {
            field_code: 'substitution_applied',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'engineering_applied',
          label: '3. Engineering Controls - Physical changes to the workplace?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially', 'N/A'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'engineering_details',
          label: 'Engineering Control Details',
          field_type: 'textarea',
          placeholder: 'Describe engineering controls implemented (guards, ventilation, barriers, etc.)...',
          conditional_logic: {
            field_code: 'engineering_applied',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'administrative_applied',
          label: '4. Administrative Controls - Procedures, training, signage?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially', 'N/A'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'full',
        },
        {
          code: 'administrative_details',
          label: 'Administrative Control Details',
          field_type: 'textarea',
          placeholder: 'Describe administrative controls (SOPs, training, rotation, signage, etc.)...',
          conditional_logic: {
            field_code: 'administrative_applied',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 7,
          width: 'full',
        },
        {
          code: 'ppe_applied',
          label: '5. PPE - Personal protective equipment required?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          validation_rules: { required: true },
          order_index: 8,
          width: 'full',
        },
        {
          code: 'ppe_details',
          label: 'PPE Requirements',
          field_type: 'multiselect',
          options: [
            { value: 'hard_hat', label: 'Hard Hat' },
            { value: 'safety_glasses', label: 'Safety Glasses' },
            { value: 'face_shield', label: 'Face Shield' },
            { value: 'hearing_protection', label: 'Hearing Protection' },
            { value: 'respirator', label: 'Respirator' },
            { value: 'gloves', label: 'Gloves' },
            { value: 'safety_boots', label: 'Safety Boots' },
            { value: 'hi_vis', label: 'High Visibility Clothing' },
            { value: 'fall_protection', label: 'Fall Protection' },
            { value: 'other', label: 'Other' },
          ],
          conditional_logic: {
            field_code: 'ppe_applied',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 9,
          width: 'full',
        },
      ],
    },
    {
      title: 'Implementation Status',
      order_index: 2,
      fields: [
        {
          code: 'implementation_status',
          label: 'Implementation Status',
          field_type: 'dropdown',
          options: [
            { value: 'planned', label: 'Planned - Not yet started' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'completed', label: 'Completed' },
            { value: 'verified', label: 'Completed & Verified' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'target_completion_date',
          label: 'Target Completion Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'implementation_status',
            operator: 'not_equals',
            value: 'completed',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'responsible_person',
          label: 'Responsible Person',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'residual_risk_level',
          label: 'Residual Risk Level (after controls)',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Still unacceptable' },
            { value: 'high', label: 'High - Needs more controls' },
            { value: 'medium', label: 'Medium - Acceptable with monitoring' },
            { value: 'low', label: 'Low - Acceptable' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'verification_date',
          label: 'Verification Date',
          field_type: 'date',
          conditional_logic: {
            field_code: 'implementation_status',
            operator: 'equals',
            value: 'verified',
          },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'photos',
          label: 'Photos of Controls Implemented',
          field_type: 'photo',
          help_text: 'Take photos showing the controls in place',
          order_index: 5,
          width: 'full',
        },
        {
          code: 'additional_notes',
          label: 'Additional Notes',
          field_type: 'textarea',
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 3,
      fields: [
        {
          code: 'implementer_signature',
          label: 'Implementer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'supervisor_signature',
          label: 'Supervisor Approval',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin', 'internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Verify Control Implementation',
      priority: 'high',
      due_hours: 48,
    },
    sync_priority: 2,
    requires_approval: true,
  },
};
