/**
 * Control Review & Approval Form
 * COR Element 3: Hazard Control
 * 
 * Formal review and approval of hazard controls by management.
 */

import type { FormConfig } from '../../import-forms';

export const controlReviewApproval: FormConfig = {
  code: 'control_review_approval',
  name: 'Control Review & Approval',
  description: 'Formal management review and approval of implemented hazard controls to ensure adequacy and effectiveness.',
  cor_element: 3,
  frequency: 'as_needed',
  estimated_time_minutes: 25,
  icon: 'CheckSquare',
  color: '#059669',
  is_mandatory: true,

  sections: [
    {
      title: 'Review Information',
      order_index: 0,
      fields: [
        {
          code: 'review_date',
          label: 'Review Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'control_implementation_ref',
          label: 'Control Implementation Reference',
          field_type: 'text',
          placeholder: 'CI-2025-001',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'reviewer',
          label: 'Reviewer',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'reviewer_role',
          label: 'Reviewer Role/Title',
          field_type: 'dropdown',
          options: [
            { value: 'supervisor', label: 'Supervisor' },
            { value: 'safety_officer', label: 'Safety Officer' },
            { value: 'project_manager', label: 'Project Manager' },
            { value: 'operations_manager', label: 'Operations Manager' },
            { value: 'safety_manager', label: 'Safety Manager' },
            { value: 'director', label: 'Director' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Control Summary',
      order_index: 1,
      fields: [
        {
          code: 'hazard_description',
          label: 'Hazard Description',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'controls_implemented',
          label: 'Controls Implemented',
          field_type: 'textarea',
          placeholder: 'Summarize all controls that have been implemented...',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'initial_risk_level',
          label: 'Initial Risk Level',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical' },
            { value: 'high', label: 'High' },
            { value: 'medium', label: 'Medium' },
            { value: 'low', label: 'Low' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'residual_risk_level',
          label: 'Residual Risk Level',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical' },
            { value: 'high', label: 'High' },
            { value: 'medium', label: 'Medium' },
            { value: 'low', label: 'Low' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Review Assessment',
      description: 'Assess the adequacy of implemented controls',
      order_index: 2,
      fields: [
        {
          code: 'hierarchy_followed',
          label: 'Was the hierarchy of controls properly followed?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          help_text: 'Elimination > Substitution > Engineering > Administrative > PPE',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'hierarchy_comments',
          label: 'Hierarchy Comments',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'hierarchy_followed',
            operator: 'not_equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'controls_adequate',
          label: 'Are the controls adequate for the hazard?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'adequacy_comments',
          label: 'Adequacy Comments',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'controls_adequate',
            operator: 'not_equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'workers_trained',
          label: 'Have affected workers been trained on controls?',
          field_type: 'radio',
          options: ['Yes', 'In Progress', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'controls_communicated',
          label: 'Have controls been properly communicated?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'monitoring_in_place',
          label: 'Is monitoring/verification in place?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Approval Decision',
      order_index: 3,
      fields: [
        {
          code: 'approval_decision',
          label: 'Approval Decision',
          field_type: 'dropdown',
          options: [
            { value: 'approved', label: 'Approved - Controls are adequate' },
            { value: 'approved_with_conditions', label: 'Approved with Conditions' },
            { value: 'not_approved', label: 'Not Approved - Additional controls required' },
            { value: 'deferred', label: 'Deferred - More information needed' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'conditions',
          label: 'Conditions/Requirements',
          field_type: 'textarea',
          placeholder: 'List any conditions for approval or additional requirements...',
          conditional_logic: {
            field_code: 'approval_decision',
            operator: 'not_equals',
            value: 'approved',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'additional_controls_required',
          label: 'Additional Controls Required',
          field_type: 'textarea',
          placeholder: 'Describe additional controls needed...',
          conditional_logic: {
            field_code: 'approval_decision',
            operator: 'equals',
            value: 'not_approved',
          },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'next_review_date',
          label: 'Next Review Date',
          field_type: 'date',
          help_text: 'When should these controls be reviewed again?',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'overall_comments',
          label: 'Overall Comments',
          field_type: 'textarea',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 4,
      fields: [
        {
          code: 'reviewer_signature',
          label: 'Reviewer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Approval',
          field_type: 'signature',
          help_text: 'Required for high/critical risk controls',
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['supervisor', 'internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Implement Additional Controls',
      priority: 'high',
      due_hours: 72,
    },
    sync_priority: 2,
    requires_approval: true,
  },
};
