/**
 * Control Communication Record
 * COR Element 3: Hazard Control
 * 
 * Document communication of hazard controls to affected workers.
 */

import type { FormConfig } from '../../import-forms';

export const controlCommunicationRecord: FormConfig = {
  code: 'control_communication_record',
  name: 'Control Communication Record',
  description: 'Document the communication of hazard controls to affected workers, ensuring everyone understands the controls in place.',
  cor_element: 3,
  frequency: 'as_needed',
  estimated_time_minutes: 15,
  icon: 'MessageSquare',
  color: '#8B5CF6',
  is_mandatory: true,

  sections: [
    {
      title: 'Communication Details',
      order_index: 0,
      fields: [
        {
          code: 'communication_date',
          label: 'Date of Communication',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'communication_time',
          label: 'Time',
          field_type: 'time',
          default_value: 'now',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'jobsite',
          label: 'Jobsite/Location',
          field_type: 'jobsite_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'communicator',
          label: 'Communicated By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'communication_method',
          label: 'Method of Communication',
          field_type: 'multiselect',
          options: [
            { value: 'toolbox_talk', label: 'Toolbox Talk' },
            { value: 'safety_meeting', label: 'Safety Meeting' },
            { value: 'one_on_one', label: 'One-on-One Discussion' },
            { value: 'posted_notice', label: 'Posted Notice' },
            { value: 'email', label: 'Email' },
            { value: 'training_session', label: 'Training Session' },
            { value: 'sop_review', label: 'SOP Review' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Control Information',
      order_index: 1,
      fields: [
        {
          code: 'control_ref',
          label: 'Control Implementation Reference',
          field_type: 'text',
          placeholder: 'CI-2025-001',
          help_text: 'Reference to the related control implementation form',
          order_index: 0,
          width: 'half',
        },
        {
          code: 'hazard_description',
          label: 'Hazard Being Controlled',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'controls_communicated',
          label: 'Controls Communicated',
          field_type: 'textarea',
          placeholder: 'List all controls that were communicated...',
          validation_rules: { required: true, min_length: 20 },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'worker_responsibilities',
          label: 'Worker Responsibilities',
          field_type: 'textarea',
          placeholder: 'What are workers expected to do?',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'ppe_requirements',
          label: 'PPE Requirements Communicated',
          field_type: 'multiselect',
          options: [
            { value: 'hard_hat', label: 'Hard Hat' },
            { value: 'safety_glasses', label: 'Safety Glasses' },
            { value: 'face_shield', label: 'Face Shield' },
            { value: 'hearing_protection', label: 'Hearing Protection' },
            { value: 'respirator', label: 'Respirator' },
            { value: 'gloves', label: 'Gloves' },
            { value: 'safety_boots', label: 'Safety Boots' },
            { value: 'hi_vis', label: 'High Visibility Clothing' },
            { value: 'fall_protection', label: 'Fall Protection' },
            { value: 'none', label: 'No PPE Required' },
          ],
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Attendees',
      description: 'Record all workers who received this communication',
      order_index: 2,
      fields: [
        {
          code: 'attendees',
          label: 'Workers Communicated To',
          field_type: 'worker_select',
          help_text: 'Select all workers who received this communication',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'attendee_count',
          label: 'Total Attendee Count',
          field_type: 'number',
          help_text: 'Include any workers not in the system',
          validation_rules: { required: true, min_value: 1 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'duration_minutes',
          label: 'Duration (minutes)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 1 },
          order_index: 2,
          width: 'half',
        },
      ],
    },
    {
      title: 'Worker Understanding',
      order_index: 3,
      fields: [
        {
          code: 'questions_asked',
          label: 'Were questions asked by workers?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'questions_details',
          label: 'Questions and Responses',
          field_type: 'textarea',
          placeholder: 'Document any questions asked and how they were answered...',
          conditional_logic: {
            field_code: 'questions_asked',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'understanding_confirmed',
          label: 'Did all workers confirm understanding?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Some did not'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'follow_up_required',
          label: 'Follow-up Required',
          field_type: 'textarea',
          placeholder: 'Note any follow-up training or communication needed...',
          conditional_logic: {
            field_code: 'understanding_confirmed',
            operator: 'not_equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 4,
      fields: [
        {
          code: 'communicator_signature',
          label: 'Communicator Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
