/**
 * PPE Training Sign-Off
 * COR Element 6: Personal Protective Equipment
 * 
 * Document PPE training and worker acknowledgment.
 */

import type { FormConfig } from '../../import-forms';

export const ppeTrainingSignoff: FormConfig = {
  code: 'ppe_training_signoff',
  name: 'PPE Training Sign-Off',
  description: 'Document PPE training completion and worker acknowledgment of proper use, care, and limitations.',
  cor_element: 6,
  frequency: 'as_needed',
  estimated_time_minutes: 15,
  icon: 'GraduationCap',
  color: '#10B981',
  is_mandatory: true,

  sections: [
    {
      title: 'Training Details',
      order_index: 0,
      fields: [
        {
          code: 'training_date',
          label: 'Training Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'trainer',
          label: 'Trainer',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'trainee',
          label: 'Trainee',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'training_type',
          label: 'Training Type',
          field_type: 'dropdown',
          options: [
            { value: 'initial', label: 'Initial Training' },
            { value: 'refresher', label: 'Refresher Training' },
            { value: 'new_equipment', label: 'New Equipment Training' },
            { value: 'job_specific', label: 'Job-Specific Training' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'duration_minutes',
          label: 'Training Duration (minutes)',
          field_type: 'number',
          validation_rules: { required: true, min_value: 5 },
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'PPE Covered',
      description: 'Select all PPE types covered in this training',
      order_index: 1,
      fields: [
        {
          code: 'ppe_types',
          label: 'PPE Types',
          field_type: 'multiselect',
          options: [
            { value: 'hard_hat', label: 'Hard Hat' },
            { value: 'safety_glasses', label: 'Safety Glasses' },
            { value: 'face_shield', label: 'Face Shield' },
            { value: 'welding_helmet', label: 'Welding Helmet' },
            { value: 'hearing_plugs', label: 'Hearing Plugs' },
            { value: 'hearing_muffs', label: 'Hearing Muffs' },
            { value: 'half_face_respirator', label: 'Half-Face Respirator' },
            { value: 'full_face_respirator', label: 'Full-Face Respirator' },
            { value: 'n95', label: 'N95 Disposable Respirator' },
            { value: 'leather_gloves', label: 'Leather Gloves' },
            { value: 'chemical_gloves', label: 'Chemical-Resistant Gloves' },
            { value: 'cut_resistant_gloves', label: 'Cut-Resistant Gloves' },
            { value: 'safety_boots', label: 'Safety Boots' },
            { value: 'metatarsal_guards', label: 'Metatarsal Guards' },
            { value: 'fall_harness', label: 'Fall Protection Harness' },
            { value: 'lanyard', label: 'Lanyard/SRL' },
            { value: 'hi_vis_vest', label: 'High-Visibility Vest' },
            { value: 'coveralls', label: 'Coveralls' },
            { value: 'chemical_suit', label: 'Chemical-Resistant Suit' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
    {
      title: 'Training Topics Covered',
      order_index: 2,
      fields: [
        {
          code: 'when_required',
          label: 'When PPE is required',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'proper_fit',
          label: 'Proper fit and adjustment',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'donning_doffing',
          label: 'Donning and doffing procedures',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'limitations',
          label: 'Limitations of PPE',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'care_maintenance',
          label: 'Care and maintenance',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'inspection',
          label: 'How to inspect PPE',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'storage',
          label: 'Proper storage',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'replacement',
          label: 'When to replace/report defects',
          field_type: 'radio',
          options: ['Covered', 'N/A'],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
        {
          code: 'hands_on',
          label: 'Hands-on demonstration completed',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 8,
          width: 'full',
        },
        {
          code: 'additional_topics',
          label: 'Additional Topics Covered',
          field_type: 'textarea',
          order_index: 9,
          width: 'full',
        },
      ],
    },
    {
      title: 'Competency Verification',
      order_index: 3,
      fields: [
        {
          code: 'demonstrated_understanding',
          label: 'Did trainee demonstrate understanding?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Partially'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'can_properly_use',
          label: 'Can trainee properly use PPE?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Needs more practice'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'follow_up_needed',
          label: 'Is follow-up training needed?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'follow_up_notes',
          label: 'Follow-up Notes',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'follow_up_needed',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'next_training_date',
          label: 'Next Training/Refresher Date',
          field_type: 'date',
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Acknowledgment',
      description: 'Trainee acknowledgment of training completion',
      order_index: 4,
      fields: [
        {
          code: 'acknowledgment_text',
          label: 'Trainee Acknowledgment',
          field_type: 'checkbox',
          options: [
            'I have received training on the proper selection, use, care, and limitations of the PPE identified above. I understand that I am required to use this PPE when performing tasks that require it, and to report any defects or damage immediately.',
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'trainer_signature',
          label: 'Trainer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'trainee_signature',
          label: 'Trainee Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
