/**
 * PPE Maintenance Log
 * COR Element 6: Personal Protective Equipment
 * 
 * Track maintenance, inspection, and replacement of PPE.
 */

import type { FormConfig } from '../../import-forms';

export const ppeMaintenanceLog: FormConfig = {
  code: 'ppe_maintenance_log',
  name: 'PPE Maintenance Log',
  description: 'Track maintenance, inspection, cleaning, and replacement of personal protective equipment.',
  cor_element: 6,
  frequency: 'weekly',
  estimated_time_minutes: 10,
  icon: 'Wrench',
  color: '#F97316',
  is_mandatory: true,

  sections: [
    {
      title: 'Entry Details',
      order_index: 0,
      fields: [
        {
          code: 'entry_date',
          label: 'Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'technician',
          label: 'Performed By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'action_type',
          label: 'Action Type',
          field_type: 'dropdown',
          options: [
            { value: 'inspection', label: 'Inspection' },
            { value: 'cleaning', label: 'Cleaning' },
            { value: 'repair', label: 'Repair' },
            { value: 'replacement', label: 'Replacement' },
            { value: 'calibration', label: 'Calibration' },
            { value: 'certification', label: 'Certification' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'ppe_category',
          label: 'PPE Category',
          field_type: 'dropdown',
          options: [
            { value: 'head_protection', label: 'Head Protection' },
            { value: 'eye_face', label: 'Eye/Face Protection' },
            { value: 'hearing', label: 'Hearing Protection' },
            { value: 'respiratory', label: 'Respiratory Protection' },
            { value: 'hand', label: 'Hand Protection' },
            { value: 'foot', label: 'Foot Protection' },
            { value: 'fall_protection', label: 'Fall Protection' },
            { value: 'body', label: 'Body Protection' },
            { value: 'high_visibility', label: 'High Visibility' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Equipment Details',
      order_index: 1,
      fields: [
        {
          code: 'ppe_description',
          label: 'PPE Description',
          field_type: 'text',
          placeholder: 'e.g., 3M 6800 Full Face Respirator',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'asset_id',
          label: 'Asset/Serial Number',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'assigned_to',
          label: 'Assigned To',
          field_type: 'worker_select',
          order_index: 2,
          width: 'half',
        },
        {
          code: 'manufacturer',
          label: 'Manufacturer',
          field_type: 'text',
          order_index: 3,
          width: 'half',
        },
        {
          code: 'manufacture_date',
          label: 'Manufacture Date',
          field_type: 'date',
          order_index: 4,
          width: 'half',
        },
        {
          code: 'expiry_date',
          label: 'Expiry Date',
          field_type: 'date',
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Inspection Results',
      description: 'Complete if performing an inspection',
      order_index: 2,
      conditional_logic: {
        field_code: 'action_type',
        operator: 'equals',
        value: 'inspection',
      },
      fields: [
        {
          code: 'physical_condition',
          label: 'Physical Condition',
          field_type: 'radio',
          options: ['Good', 'Acceptable', 'Poor', 'Failed'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'cleanliness',
          label: 'Cleanliness',
          field_type: 'radio',
          options: ['Clean', 'Needs Cleaning', 'Heavily Soiled'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'damage_found',
          label: 'Any Damage Found?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'damage_description',
          label: 'Damage Description',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'damage_found',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'fit_for_use',
          label: 'Fit for Continued Use?',
          field_type: 'radio',
          options: ['Yes', 'Yes with restrictions', 'No - Needs repair', 'No - Replace'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Maintenance Details',
      description: 'Complete if performing maintenance/repair',
      order_index: 3,
      conditional_logic: {
        field_code: 'action_type',
        operator: 'not_equals',
        value: 'inspection',
      },
      fields: [
        {
          code: 'work_description',
          label: 'Work Performed',
          field_type: 'textarea',
          placeholder: 'Describe the maintenance/repair work performed...',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'parts_replaced',
          label: 'Parts Replaced',
          field_type: 'textarea',
          placeholder: 'List any parts that were replaced...',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'work_status',
          label: 'Work Status',
          field_type: 'dropdown',
          options: [
            { value: 'completed', label: 'Completed' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'waiting_parts', label: 'Waiting for Parts' },
            { value: 'sent_out', label: 'Sent Out for Service' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'return_to_service',
          label: 'Can be Returned to Service?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Replacement Details',
      description: 'Complete if replacing PPE',
      order_index: 4,
      conditional_logic: {
        field_code: 'action_type',
        operator: 'equals',
        value: 'replacement',
      },
      fields: [
        {
          code: 'replacement_reason',
          label: 'Reason for Replacement',
          field_type: 'dropdown',
          options: [
            { value: 'damaged', label: 'Damaged' },
            { value: 'expired', label: 'Expired' },
            { value: 'worn', label: 'Worn Out' },
            { value: 'lost', label: 'Lost' },
            { value: 'fit', label: 'No Longer Fits' },
            { value: 'upgrade', label: 'Upgrade/Improvement' },
            { value: 'regulatory', label: 'Regulatory Requirement' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'new_asset_id',
          label: 'New Asset/Serial Number',
          field_type: 'text',
          order_index: 1,
          width: 'half',
        },
        {
          code: 'old_ppe_disposed',
          label: 'Old PPE Disposed?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'disposal_method',
          label: 'Disposal Method',
          field_type: 'dropdown',
          options: [
            { value: 'standard', label: 'Standard Waste' },
            { value: 'recycling', label: 'Recycling' },
            { value: 'hazardous', label: 'Hazardous Waste' },
            { value: 'returned', label: 'Returned to Manufacturer' },
          ],
          conditional_logic: {
            field_code: 'old_ppe_disposed',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Next Actions',
      order_index: 5,
      fields: [
        {
          code: 'next_inspection_date',
          label: 'Next Inspection Due',
          field_type: 'date',
          order_index: 0,
          width: 'half',
        },
        {
          code: 'follow_up_required',
          label: 'Follow-up Required?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          order_index: 1,
          width: 'half',
        },
        {
          code: 'comments',
          label: 'Comments',
          field_type: 'textarea',
          order_index: 2,
          width: 'full',
        },
        {
          code: 'photos',
          label: 'Photos',
          field_type: 'photo',
          help_text: 'Photos of damage, repairs, or condition',
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 6,
      fields: [
        {
          code: 'technician_signature',
          label: 'Technician Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
