/**
 * PPE Fit Test Record
 * COR Element 6: Personal Protective Equipment
 * 
 * Document fit testing for respirators and other PPE.
 */

import type { FormConfig } from '../../import-forms';

export const ppeFitTestRecord: FormConfig = {
  code: 'ppe_fit_test_record',
  name: 'PPE Fit Test Record',
  description: 'Document fit testing for respirators and other size-dependent PPE to ensure proper protection.',
  cor_element: 6,
  frequency: 'annual',
  estimated_time_minutes: 15,
  icon: 'Shield',
  color: '#8B5CF6',
  is_mandatory: true,

  sections: [
    {
      title: 'Test Information',
      order_index: 0,
      fields: [
        {
          code: 'test_date',
          label: 'Test Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'tester',
          label: 'Test Conducted By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'employee',
          label: 'Employee Being Tested',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'ppe_type',
          label: 'PPE Type',
          field_type: 'dropdown',
          options: [
            { value: 'half_face_respirator', label: 'Half-Face Respirator' },
            { value: 'full_face_respirator', label: 'Full-Face Respirator' },
            { value: 'n95_respirator', label: 'N95 Respirator' },
            { value: 'papr', label: 'PAPR (Powered Air-Purifying)' },
            { value: 'scba', label: 'SCBA (Self-Contained Breathing Apparatus)' },
            { value: 'fall_harness', label: 'Fall Protection Harness' },
            { value: 'hearing_protection', label: 'Custom Hearing Protection' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'ppe_manufacturer',
          label: 'Manufacturer',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'ppe_model',
          label: 'Model',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'ppe_size',
          label: 'Size',
          field_type: 'dropdown',
          options: [
            { value: 'xs', label: 'Extra Small' },
            { value: 's', label: 'Small' },
            { value: 'm', label: 'Medium' },
            { value: 'l', label: 'Large' },
            { value: 'xl', label: 'Extra Large' },
            { value: 'xxl', label: 'XXL' },
          ],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
      ],
    },
    {
      title: 'Pre-Test Requirements',
      description: 'Verify employee meets pre-test requirements',
      order_index: 1,
      fields: [
        {
          code: 'medical_clearance',
          label: 'Medical clearance on file?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Not Required'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'clean_shaven',
          label: 'Is employee clean-shaven in seal area?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          help_text: 'Required for tight-fitting respirators',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'no_eating_smoking',
          label: 'Employee refrained from eating/smoking/gum 30 min prior?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'training_completed',
          label: 'Has employee completed respirator training?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Fit Test Protocol',
      order_index: 2,
      fields: [
        {
          code: 'test_method',
          label: 'Fit Test Method',
          field_type: 'dropdown',
          options: [
            { value: 'saccharin', label: 'Qualitative - Saccharin' },
            { value: 'bitrex', label: 'Qualitative - Bitrex' },
            { value: 'irritant_smoke', label: 'Qualitative - Irritant Smoke' },
            { value: 'quantitative', label: 'Quantitative (PortaCount)' },
            { value: 'controlled_negative_pressure', label: 'Controlled Negative Pressure' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'normal_breathing',
          label: 'Normal Breathing Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'deep_breathing',
          label: 'Deep Breathing Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'head_side_to_side',
          label: 'Head Side-to-Side Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'head_up_down',
          label: 'Head Up-and-Down Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'talking_test',
          label: 'Talking Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'grimace_test',
          label: 'Grimace Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'bending_over',
          label: 'Bending Over Test',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
        {
          code: 'normal_breathing_2',
          label: 'Normal Breathing (Final)',
          field_type: 'radio',
          options: ['Pass', 'Fail'],
          validation_rules: { required: true },
          order_index: 8,
          width: 'half',
        },
        {
          code: 'fit_factor',
          label: 'Fit Factor (if quantitative)',
          field_type: 'number',
          help_text: 'Minimum 100 for half-face, 500 for full-face',
          order_index: 9,
          width: 'half',
        },
      ],
    },
    {
      title: 'Test Results',
      order_index: 3,
      fields: [
        {
          code: 'overall_result',
          label: 'Overall Fit Test Result',
          field_type: 'dropdown',
          options: [
            { value: 'pass', label: 'Pass' },
            { value: 'fail', label: 'Fail' },
            { value: 'retest_required', label: 'Retest Required' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'next_test_date',
          label: 'Next Fit Test Due',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'failure_reason',
          label: 'Reason for Failure (if applicable)',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'overall_result',
            operator: 'not_equals',
            value: 'pass',
          },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'alternative_ppe',
          label: 'Alternative PPE Assigned',
          field_type: 'text',
          help_text: 'If original PPE did not fit, what was assigned?',
          conditional_logic: {
            field_code: 'overall_result',
            operator: 'equals',
            value: 'fail',
          },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'comments',
          label: 'Comments',
          field_type: 'textarea',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 4,
      fields: [
        {
          code: 'tester_signature',
          label: 'Tester Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'employee_signature',
          label: 'Employee Signature',
          field_type: 'signature',
          help_text: 'I confirm I was properly fitted and trained on this equipment',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'supervisor',
    notify_roles: ['admin'],
    sync_priority: 3,
    requires_approval: false,
  },
};
