/**
 * KPI Review Form
 * COR Element 14: Management System
 * 
 * Review safety Key Performance Indicators.
 */

import type { FormConfig } from '../../import-forms';

export const kpiReview: FormConfig = {
  code: 'kpi_review',
  name: 'Safety KPI Review',
  description: 'Regular review of safety Key Performance Indicators (KPIs) against targets.',
  cor_element: 14,
  frequency: 'monthly',
  estimated_time_minutes: 30,
  icon: 'Target',
  color: '#10B981',
  is_mandatory: true,

  sections: [
    {
      title: 'Review Information',
      order_index: 0,
      fields: [
        {
          code: 'review_date',
          label: 'Review Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'reviewer',
          label: 'Reviewed By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'review_period',
          label: 'Review Period',
          field_type: 'dropdown',
          options: [
            { value: 'monthly', label: 'Monthly' },
            { value: 'quarterly', label: 'Quarterly' },
            { value: 'ytd', label: 'Year-to-Date' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'period_end_date',
          label: 'Period End Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Lagging Indicators',
      description: 'Outcome-based metrics',
      order_index: 1,
      fields: [
        {
          code: 'trir_actual',
          label: 'TRIR - Actual',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'trir_target',
          label: 'TRIR - Target',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'trir_status',
          label: 'TRIR Status',
          field_type: 'dropdown',
          options: [
            { value: 'on_target', label: 'On Target' },
            { value: 'above_target', label: 'Above Target (worse)' },
            { value: 'below_target', label: 'Below Target (better)' },
          ],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'ltir_actual',
          label: 'LTIR - Actual',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'ltir_target',
          label: 'LTIR - Target',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 4,
          width: 'quarter',
        },
        {
          code: 'ltir_status',
          label: 'LTIR Status',
          field_type: 'dropdown',
          options: [
            { value: 'on_target', label: 'On Target' },
            { value: 'above_target', label: 'Above Target (worse)' },
            { value: 'below_target', label: 'Below Target (better)' },
          ],
          order_index: 5,
          width: 'half',
        },
        {
          code: 'severity_rate_actual',
          label: 'Severity Rate - Actual',
          field_type: 'number',
          order_index: 6,
          width: 'quarter',
        },
        {
          code: 'severity_rate_target',
          label: 'Severity Rate - Target',
          field_type: 'number',
          order_index: 7,
          width: 'quarter',
        },
        {
          code: 'days_since_lti',
          label: 'Days Since Last LTI',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 8,
          width: 'half',
        },
      ],
    },
    {
      title: 'Leading Indicators',
      description: 'Proactive metrics',
      order_index: 2,
      fields: [
        {
          code: 'inspection_completion_actual',
          label: 'Inspection Completion % - Actual',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'inspection_completion_target',
          label: 'Inspection Completion % - Target',
          field_type: 'number',
          default_value: '100',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'inspection_status',
          label: 'Status',
          field_type: 'dropdown',
          options: [
            { value: 'meeting', label: 'Meeting Target' },
            { value: 'below', label: 'Below Target' },
          ],
          order_index: 2,
          width: 'half',
        },
        {
          code: 'training_compliance_actual',
          label: 'Training Compliance % - Actual',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 3,
          width: 'quarter',
        },
        {
          code: 'training_compliance_target',
          label: 'Training Compliance % - Target',
          field_type: 'number',
          default_value: '100',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 4,
          width: 'quarter',
        },
        {
          code: 'training_status',
          label: 'Status',
          field_type: 'dropdown',
          options: [
            { value: 'meeting', label: 'Meeting Target' },
            { value: 'below', label: 'Below Target' },
          ],
          order_index: 5,
          width: 'half',
        },
        {
          code: 'hazard_closure_actual',
          label: 'Hazard Closure Rate % - Actual',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 6,
          width: 'quarter',
        },
        {
          code: 'hazard_closure_target',
          label: 'Hazard Closure Rate % - Target',
          field_type: 'number',
          default_value: '95',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 7,
          width: 'quarter',
        },
        {
          code: 'near_miss_reports',
          label: 'Near Miss Reports',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 8,
          width: 'quarter',
        },
        {
          code: 'safety_observations',
          label: 'Safety Observations',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 9,
          width: 'quarter',
        },
        {
          code: 'toolbox_talks',
          label: 'Toolbox Talks Conducted',
          field_type: 'number',
          validation_rules: { min_value: 0 },
          order_index: 10,
          width: 'half',
        },
      ],
    },
    {
      title: 'Corrective Action Metrics',
      order_index: 3,
      fields: [
        {
          code: 'ca_open',
          label: 'Open Corrective Actions',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'ca_overdue',
          label: 'Overdue Corrective Actions',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'ca_closed_period',
          label: 'Closed This Period',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'ca_on_time_closure',
          label: 'On-Time Closure Rate %',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 3,
          width: 'quarter',
        },
      ],
    },
    {
      title: 'Analysis & Commentary',
      order_index: 4,
      fields: [
        {
          code: 'overall_assessment',
          label: 'Overall KPI Assessment',
          field_type: 'dropdown',
          options: [
            { value: 'excellent', label: 'Excellent - All targets met' },
            { value: 'good', label: 'Good - Most targets met' },
            { value: 'satisfactory', label: 'Satisfactory - Some targets met' },
            { value: 'needs_improvement', label: 'Needs Improvement - Targets not met' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'positive_trends',
          label: 'Positive Trends/Achievements',
          field_type: 'textarea',
          placeholder: 'Note positive trends and achievements...',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'areas_of_concern',
          label: 'Areas of Concern',
          field_type: 'textarea',
          placeholder: 'Identify areas where targets are not being met...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'root_cause_analysis',
          label: 'Root Cause Analysis for Variances',
          field_type: 'textarea',
          placeholder: 'What are the root causes for any significant variances?',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'recommended_actions',
          label: 'Recommended Actions',
          field_type: 'textarea',
          placeholder: 'What actions are recommended to improve performance?',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'target_revisions',
          label: 'Are target revisions recommended?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 5,
          width: 'full',
        },
        {
          code: 'revision_details',
          label: 'Target Revision Details',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'target_revisions',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 6,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 5,
      fields: [
        {
          code: 'reviewer_signature',
          label: 'Reviewer Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Review',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    sync_priority: 3,
    requires_approval: false,
  },
};
