/**
 * Management Action Plan
 * COR Element 14: Management System
 * 
 * Document management actions and improvements.
 */

import type { FormConfig } from '../../import-forms';

export const managementActionPlan: FormConfig = {
  code: 'management_action_plan',
  name: 'Management Action Plan',
  description: 'Document and track management actions for safety improvements and system enhancements.',
  cor_element: 14,
  frequency: 'as_needed',
  estimated_time_minutes: 25,
  icon: 'ClipboardList',
  color: '#8B5CF6',
  is_mandatory: true,

  sections: [
    {
      title: 'Plan Information',
      order_index: 0,
      fields: [
        {
          code: 'plan_date',
          label: 'Plan Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'plan_reference',
          label: 'Plan Reference Number',
          field_type: 'text',
          placeholder: 'MAP-2025-001',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'prepared_by',
          label: 'Prepared By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'plan_owner',
          label: 'Plan Owner/Sponsor',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'source',
          label: 'Source of Action Plan',
          field_type: 'dropdown',
          options: [
            { value: 'management_review', label: 'Management Review' },
            { value: 'audit', label: 'Audit Findings' },
            { value: 'incident', label: 'Incident Investigation' },
            { value: 'inspection', label: 'Inspection Findings' },
            { value: 'regulatory', label: 'Regulatory Requirement' },
            { value: 'improvement', label: 'Continuous Improvement Initiative' },
            { value: 'worker_feedback', label: 'Worker Feedback' },
            { value: 'other', label: 'Other' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'source_reference',
          label: 'Source Reference',
          field_type: 'text',
          placeholder: 'e.g., Audit Report #123',
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Objective',
      order_index: 1,
      fields: [
        {
          code: 'plan_title',
          label: 'Action Plan Title',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'objective',
          label: 'Objective/Goal',
          field_type: 'textarea',
          placeholder: 'What is this action plan intended to achieve?',
          validation_rules: { required: true, min_length: 50 },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'background',
          label: 'Background/Context',
          field_type: 'textarea',
          placeholder: 'Provide background information...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'scope',
          label: 'Scope',
          field_type: 'textarea',
          placeholder: 'What is included/excluded from this plan?',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'priority',
          label: 'Priority',
          field_type: 'dropdown',
          options: [
            { value: 'critical', label: 'Critical - Immediate' },
            { value: 'high', label: 'High - Within 30 days' },
            { value: 'medium', label: 'Medium - Within 90 days' },
            { value: 'low', label: 'Low - Within 180 days' },
          ],
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'target_completion',
          label: 'Target Completion Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
      ],
    },
    {
      title: 'Action Items',
      description: 'Detailed action items',
      order_index: 2,
      is_repeatable: true,
      fields: [
        {
          code: 'action_number',
          label: 'Action #',
          field_type: 'number',
          validation_rules: { required: true, min_value: 1 },
          order_index: 0,
          width: 'quarter',
        },
        {
          code: 'action_description',
          label: 'Action Description',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'deliverable',
          label: 'Deliverable/Output',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'responsible_person',
          label: 'Responsible Person',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'support_required',
          label: 'Support/Resources Required',
          field_type: 'text',
          order_index: 4,
          width: 'half',
        },
        {
          code: 'start_date',
          label: 'Start Date',
          field_type: 'date',
          order_index: 5,
          width: 'half',
        },
        {
          code: 'due_date',
          label: 'Due Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 6,
          width: 'half',
        },
        {
          code: 'status',
          label: 'Status',
          field_type: 'dropdown',
          options: [
            { value: 'not_started', label: 'Not Started' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'on_hold', label: 'On Hold' },
            { value: 'completed', label: 'Completed' },
            { value: 'cancelled', label: 'Cancelled' },
          ],
          validation_rules: { required: true },
          order_index: 7,
          width: 'half',
        },
        {
          code: 'percent_complete',
          label: '% Complete',
          field_type: 'dropdown',
          options: [
            { value: '0', label: '0%' },
            { value: '25', label: '25%' },
            { value: '50', label: '50%' },
            { value: '75', label: '75%' },
            { value: '100', label: '100%' },
          ],
          order_index: 8,
          width: 'half',
        },
        {
          code: 'notes',
          label: 'Notes/Comments',
          field_type: 'text',
          order_index: 9,
          width: 'full',
        },
      ],
    },
    {
      title: 'Resources & Budget',
      order_index: 3,
      fields: [
        {
          code: 'budget_required',
          label: 'Is budget required?',
          field_type: 'radio',
          options: ['Yes', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'estimated_budget',
          label: 'Estimated Budget',
          field_type: 'text',
          placeholder: '$0.00',
          conditional_logic: {
            field_code: 'budget_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'budget_approved',
          label: 'Budget Approved?',
          field_type: 'radio',
          options: ['Yes', 'No', 'Pending'],
          conditional_logic: {
            field_code: 'budget_required',
            operator: 'equals',
            value: 'Yes',
          },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'personnel_resources',
          label: 'Personnel Resources Required',
          field_type: 'textarea',
          order_index: 3,
          width: 'full',
        },
        {
          code: 'external_resources',
          label: 'External Resources/Contractors Required',
          field_type: 'textarea',
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Success Measures',
      order_index: 4,
      fields: [
        {
          code: 'success_criteria',
          label: 'Success Criteria',
          field_type: 'textarea',
          placeholder: 'How will success be measured?',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'kpis',
          label: 'Key Performance Indicators',
          field_type: 'textarea',
          placeholder: 'What KPIs will be monitored?',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'review_frequency',
          label: 'Progress Review Frequency',
          field_type: 'dropdown',
          options: [
            { value: 'weekly', label: 'Weekly' },
            { value: 'bi_weekly', label: 'Bi-Weekly' },
            { value: 'monthly', label: 'Monthly' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'next_review_date',
          label: 'Next Review Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
      ],
    },
    {
      title: 'Plan Status',
      order_index: 5,
      fields: [
        {
          code: 'overall_status',
          label: 'Overall Plan Status',
          field_type: 'dropdown',
          options: [
            { value: 'draft', label: 'Draft' },
            { value: 'approved', label: 'Approved' },
            { value: 'in_progress', label: 'In Progress' },
            { value: 'on_track', label: 'In Progress - On Track' },
            { value: 'at_risk', label: 'In Progress - At Risk' },
            { value: 'completed', label: 'Completed' },
            { value: 'closed', label: 'Closed' },
          ],
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'overall_percent',
          label: 'Overall % Complete',
          field_type: 'number',
          validation_rules: { min_value: 0, max_value: 100 },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'status_comments',
          label: 'Status Comments',
          field_type: 'textarea',
          order_index: 2,
          width: 'full',
        },
        {
          code: 'risks_issues',
          label: 'Risks/Issues',
          field_type: 'textarea',
          placeholder: 'Note any risks or issues affecting the plan...',
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 6,
      fields: [
        {
          code: 'prepared_by_signature',
          label: 'Prepared By',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'owner_signature',
          label: 'Plan Owner Approval',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'management_signature',
          label: 'Management Approval',
          field_type: 'signature',
          order_index: 2,
          width: 'full',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    creates_task: true,
    task_template: {
      title: 'Execute Management Action Plan',
      priority: 'high',
      due_hours: 168,
    },
    sync_priority: 3,
    requires_approval: true,
  },
};
