/**
 * Management Review Minutes
 * COR Element 14: Management System
 * 
 * Document management review of the safety management system.
 */

import type { FormConfig } from '../../import-forms';

export const managementReviewMinutes: FormConfig = {
  code: 'management_review_minutes',
  name: 'Management Review Minutes',
  description: 'Document management review meetings of the occupational health and safety management system.',
  cor_element: 14,
  frequency: 'quarterly',
  estimated_time_minutes: 45,
  icon: 'Users',
  color: '#6366F1',
  is_mandatory: true,

  sections: [
    {
      title: 'Meeting Information',
      order_index: 0,
      fields: [
        {
          code: 'meeting_date',
          label: 'Meeting Date',
          field_type: 'date',
          default_value: 'today',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'meeting_time',
          label: 'Meeting Time',
          field_type: 'time',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'meeting_type',
          label: 'Meeting Type',
          field_type: 'dropdown',
          options: [
            { value: 'quarterly', label: 'Quarterly Review' },
            { value: 'annual', label: 'Annual Review' },
            { value: 'special', label: 'Special Meeting' },
          ],
          validation_rules: { required: true },
          order_index: 2,
          width: 'half',
        },
        {
          code: 'location',
          label: 'Meeting Location',
          field_type: 'text',
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'chairperson',
          label: 'Chairperson',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 4,
          width: 'half',
        },
        {
          code: 'minute_taker',
          label: 'Minutes Taken By',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 5,
          width: 'half',
        },
        {
          code: 'attendees',
          label: 'Attendees',
          field_type: 'worker_select',
          validation_rules: { required: true },
          order_index: 6,
          width: 'full',
        },
        {
          code: 'absentees',
          label: 'Absent Members',
          field_type: 'text',
          order_index: 7,
          width: 'full',
        },
      ],
    },
    {
      title: 'Previous Meeting Review',
      order_index: 1,
      fields: [
        {
          code: 'previous_minutes_reviewed',
          label: 'Were previous minutes reviewed?',
          field_type: 'radio',
          options: ['Yes', 'No', 'N/A'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'previous_actions_status',
          label: 'Status of Previous Action Items',
          field_type: 'textarea',
          placeholder: 'Summarize status of action items from previous meeting...',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'outstanding_items',
          label: 'Outstanding Items',
          field_type: 'textarea',
          placeholder: 'List any items still outstanding...',
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Safety Performance Review',
      order_index: 2,
      fields: [
        {
          code: 'performance_summary',
          label: 'Safety Performance Summary',
          field_type: 'textarea',
          placeholder: 'Summarize safety performance for the period...',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'incidents_reviewed',
          label: 'Incidents Reviewed',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 1,
          width: 'quarter',
        },
        {
          code: 'near_misses_reviewed',
          label: 'Near Misses Reviewed',
          field_type: 'number',
          validation_rules: { required: true, min_value: 0 },
          order_index: 2,
          width: 'quarter',
        },
        {
          code: 'kpi_review',
          label: 'KPI Performance Discussion',
          field_type: 'textarea',
          placeholder: 'Discuss performance against key safety indicators...',
          validation_rules: { required: true },
          order_index: 3,
          width: 'full',
        },
        {
          code: 'targets_met',
          label: 'Are safety targets being met?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
        {
          code: 'target_variance',
          label: 'Target Variance Discussion',
          field_type: 'textarea',
          conditional_logic: {
            field_code: 'targets_met',
            operator: 'not_equals',
            value: 'Yes',
          },
          order_index: 5,
          width: 'full',
        },
      ],
    },
    {
      title: 'System Effectiveness Review',
      order_index: 3,
      fields: [
        {
          code: 'audit_findings',
          label: 'Audit Findings/Results',
          field_type: 'textarea',
          placeholder: 'Summarize any audit findings or results...',
          order_index: 0,
          width: 'full',
        },
        {
          code: 'inspection_findings',
          label: 'Inspection Trends',
          field_type: 'textarea',
          placeholder: 'Summarize inspection findings and trends...',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'corrective_action_status',
          label: 'Corrective Action Status',
          field_type: 'textarea',
          placeholder: 'Review status of corrective actions...',
          validation_rules: { required: true },
          order_index: 2,
          width: 'full',
        },
        {
          code: 'system_effectiveness',
          label: 'Overall System Effectiveness',
          field_type: 'dropdown',
          options: [
            { value: 'effective', label: 'Effective - Meeting objectives' },
            { value: 'needs_improvement', label: 'Needs Improvement' },
            { value: 'ineffective', label: 'Ineffective - Requires changes' },
          ],
          validation_rules: { required: true },
          order_index: 3,
          width: 'half',
        },
        {
          code: 'improvement_opportunities',
          label: 'Improvement Opportunities',
          field_type: 'textarea',
          placeholder: 'Identify opportunities for improvement...',
          validation_rules: { required: true },
          order_index: 4,
          width: 'full',
        },
      ],
    },
    {
      title: 'Resource Review',
      order_index: 4,
      fields: [
        {
          code: 'resource_adequacy',
          label: 'Are safety resources adequate?',
          field_type: 'radio',
          options: ['Yes', 'Partially', 'No'],
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'resource_needs',
          label: 'Resource Needs Identified',
          field_type: 'textarea',
          placeholder: 'List any additional resource needs...',
          conditional_logic: {
            field_code: 'resource_adequacy',
            operator: 'not_equals',
            value: 'Yes',
          },
          order_index: 1,
          width: 'full',
        },
        {
          code: 'budget_review',
          label: 'Safety Budget Review',
          field_type: 'textarea',
          placeholder: 'Review safety budget status and needs...',
          order_index: 2,
          width: 'full',
        },
        {
          code: 'training_status',
          label: 'Training Program Status',
          field_type: 'textarea',
          placeholder: 'Review training program effectiveness and needs...',
          order_index: 3,
          width: 'full',
        },
      ],
    },
    {
      title: 'External Factors',
      order_index: 5,
      fields: [
        {
          code: 'regulatory_changes',
          label: 'Regulatory Changes Discussed',
          field_type: 'textarea',
          placeholder: 'Note any regulatory changes reviewed...',
          order_index: 0,
          width: 'full',
        },
        {
          code: 'industry_best_practices',
          label: 'Industry Best Practices',
          field_type: 'textarea',
          placeholder: 'Note any industry best practices discussed...',
          order_index: 1,
          width: 'full',
        },
        {
          code: 'stakeholder_feedback',
          label: 'Stakeholder Feedback',
          field_type: 'textarea',
          placeholder: 'Note any feedback from workers, contractors, or others...',
          order_index: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Decisions & Action Items',
      order_index: 6,
      is_repeatable: true,
      fields: [
        {
          code: 'action_description',
          label: 'Action Item/Decision',
          field_type: 'textarea',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'action_type',
          label: 'Type',
          field_type: 'dropdown',
          options: [
            { value: 'decision', label: 'Decision' },
            { value: 'action', label: 'Action Item' },
            { value: 'recommendation', label: 'Recommendation' },
          ],
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'responsible_person',
          label: 'Responsible Person',
          field_type: 'worker_select',
          order_index: 2,
          width: 'half',
        },
        {
          code: 'due_date',
          label: 'Due Date',
          field_type: 'date',
          order_index: 3,
          width: 'half',
        },
        {
          code: 'priority',
          label: 'Priority',
          field_type: 'dropdown',
          options: [
            { value: 'high', label: 'High' },
            { value: 'medium', label: 'Medium' },
            { value: 'low', label: 'Low' },
          ],
          order_index: 4,
          width: 'half',
        },
      ],
    },
    {
      title: 'Meeting Closure',
      order_index: 7,
      fields: [
        {
          code: 'meeting_summary',
          label: 'Meeting Summary',
          field_type: 'textarea',
          placeholder: 'Summarize key points from the meeting...',
          validation_rules: { required: true },
          order_index: 0,
          width: 'full',
        },
        {
          code: 'next_meeting_date',
          label: 'Next Meeting Date',
          field_type: 'date',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
        {
          code: 'meeting_end_time',
          label: 'Meeting End Time',
          field_type: 'time',
          order_index: 2,
          width: 'half',
        },
      ],
    },
    {
      title: 'Sign-Off',
      order_index: 8,
      fields: [
        {
          code: 'chairperson_signature',
          label: 'Chairperson Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 0,
          width: 'half',
        },
        {
          code: 'minute_taker_signature',
          label: 'Minutes Taker Signature',
          field_type: 'signature',
          validation_rules: { required: true },
          order_index: 1,
          width: 'half',
        },
      ],
    },
  ],

  workflow: {
    submit_to_role: 'admin',
    notify_roles: ['internal_auditor'],
    sync_priority: 3,
    requires_approval: false,
  },
};
